<use f='tvm/src/target/llvm/codegen_llvm.h' l='148' c='_ZN3tvm7codegen11CodeGenLLVM6FinishEv'/>
<use f='tvm/src/target/llvm/codegen_llvm.h' l='172' c='_ZN3tvm7codegen11CodeGenLLVM13AddLinkModuleEOSt10unique_ptrIN4llvm6ModuleESt14default_deleteIS4_EE'/>
<use f='tvm/src/target/llvm/codegen_llvm.h' l='484'/>
<use f='tvm/src/target/llvm/codegen_llvm.h' l='505'/>
<use f='tvm/src/target/llvm/codegen_llvm.h' l='547' c='_ZN3tvm7codegen11CodeGenLLVM15CreateDebugInfoEPN4llvm6ModuleE'/>
<use f='tvm/src/target/llvm/llvm_instance.h' l='114' c='_ZNK3tvm7codegen12LLVMInstance7ParseIRERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE'/>
<use f='tvm/src/target/llvm/llvm_instance.h' l='124' c='_ZNK3tvm7codegen12LLVMInstance6LoadIRERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE'/>
<use f='tvm/src/target/llvm/llvm_instance.h' l='127' c='_ZNK3tvm7codegen12LLVMInstance11ParseBufferERKN4llvm12MemoryBufferE'/>
<use f='tvm/src/target/llvm/llvm_instance.h' l='345' c='_ZN3tvm7codegen10LLVMTarget17GetTargetMetadataB5cxx11ERKN4llvm6ModuleE'/>
<use f='tvm/src/target/llvm/llvm_instance.h' l='350' c='_ZNK3tvm7codegen10LLVMTarget17SetTargetMetadataEPN4llvm6ModuleE'/>
<use f='tvm/src/target/llvm/codegen_amdgpu.cc' l='274' c='_ZN3tvm7codegen11BuildAMDGPUENS_8IRModuleENS_6TargetE'/>
<use f='tvm/src/target/llvm/codegen_amdgpu.cc' l='284' c='_ZN3tvm7codegen11BuildAMDGPUENS_8IRModuleENS_6TargetE'/>
<use f='tvm/src/target/llvm/codegen_amdgpu.cc' l='295' c='_ZN3tvm7codegen11BuildAMDGPUENS_8IRModuleENS_6TargetE'/>
<use f='tvm/src/target/llvm/codegen_amdgpu.cc' l='296' c='_ZN3tvm7codegen11BuildAMDGPUENS_8IRModuleENS_6TargetE'/>
<size>800</size>
<use f='tvm/src/target/llvm/codegen_cpu.h' l='71' c='_ZN3tvm7codegen10CodeGenCPU6FinishEv'/>
<size>800</size>
<use f='tvm/src/target/llvm/codegen_blob.h' l='50' c='_ZN3tvm7codegen11CodeGenBlobERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEbPNS0_10LLVMTargetE'/>
<use f='tvm/src/target/llvm/codegen_blob.cc' l='60' c='_ZN3tvm7codegen11CodeGenBlobERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEbPNS0_10LLVMTargetE'/>
<use f='tvm/src/target/llvm/codegen_blob.cc' l='66' c='_ZN3tvm7codegen11CodeGenBlobERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEbPNS0_10LLVMTargetE'/>
<size>800</size>
<use f='tvm/src/target/llvm/codegen_cpu.cc' l='327' c='_ZN3tvm7codegen10CodeGenCPU6FinishEv'/>
<use f='tvm/src/target/llvm/codegen_cpu.cc' l='1259'/>
<size>800</size>
<use f='tvm/src/target/llvm/codegen_hexagon.cc' l='85' c='_ZNK3tvm7codegen14CodeGenHexagon12GetModulePtrEv'/>
<use f='tvm/src/target/llvm/codegen_hexagon.cc' l='481' c='_ZN3tvm7codegen12_GLOBAL__N_1lsERSoRKN4llvm6ModuleE'/>
<use f='tvm/src/target/llvm/codegen_hexagon.cc' l='572' c='_ZN3tvm7codegen12BuildHexagonENS_8IRModuleENS_6TargetE'/>
<use f='tvm/src/target/llvm/codegen_hexagon.cc' l='576' c='_ZN3tvm7codegen12BuildHexagonENS_8IRModuleENS_6TargetE'/>
<use f='tvm/src/target/llvm/codegen_hexagon.cc' l='595' c='_ZN3tvm7codegen12BuildHexagonENS_8IRModuleENS_6TargetE'/>
<size>800</size>
<use f='tvm/src/target/llvm/codegen_llvm.cc' l='139' c='_ZN3tvm7codegen11CodeGenLLVM4InitERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEPNS0_10LLVMTargetEbbb'/>
<use f='tvm/src/target/llvm/codegen_llvm.cc' l='308' c='_ZN3tvm7codegen11CodeGenLLVM6FinishEv'/>
<use f='tvm/src/target/llvm/codegen_llvm.cc' l='322' c='_ZN3tvm7codegen11CodeGenLLVM12HandleImportERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE'/>
<use f='tvm/src/target/llvm/codegen_llvm.cc' l='341' c='_ZN3tvm7codegen11CodeGenLLVM13AddLinkModuleEOSt10unique_ptrIN4llvm6ModuleESt14default_deleteIS4_EE'/>
<use f='tvm/src/target/llvm/codegen_llvm.cc' l='413' c='_ZN3tvm7codegen12FPassManagerC1EPN4llvm6ModuleE'/>
<use f='tvm/src/target/llvm/codegen_llvm.cc' l='657' c='_ZN3tvm7codegen11CodeGenLLVM15CreateDebugInfoEPN4llvm6ModuleE'/>
<use f='tvm/src/target/llvm/codegen_llvm.cc' l='978' c='_ZN3tvm7codegen11CodeGenLLVM16GetIntrinsicDeclEjPN4llvm4TypeENS2_8ArrayRefIS4_EE'/>
<size>800</size>
<use f='tvm/src/target/llvm/codegen_nvptx.cc' l='323' c='_ZN3tvm7codegen10BuildNVPTXENS_8IRModuleENS_6TargetE'/>
<use f='tvm/src/target/llvm/codegen_nvptx.cc' l='329' c='_ZN3tvm7codegen10BuildNVPTXENS_8IRModuleENS_6TargetE'/>
<size>800</size>
<use f='tvm/src/target/llvm/llvm_instance.cc' l='117' c='_ZNK3tvm7codegen12LLVMInstance7ParseIRERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE'/>
<use f='tvm/src/target/llvm/llvm_instance.cc' l='123' c='_ZNK3tvm7codegen12LLVMInstance6LoadIRERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE'/>
<use f='tvm/src/target/llvm/llvm_instance.cc' l='132' c='_ZNK3tvm7codegen12LLVMInstance11ParseBufferERKN4llvm12MemoryBufferE'/>
<use f='tvm/src/target/llvm/llvm_instance.cc' l='134' c='_ZNK3tvm7codegen12LLVMInstance11ParseBufferERKN4llvm12MemoryBufferE'/>
<use f='tvm/src/target/llvm/llvm_instance.cc' l='701' c='_ZN3tvm7codegen10LLVMTarget17GetTargetMetadataB5cxx11ERKN4llvm6ModuleE'/>
<use f='tvm/src/target/llvm/llvm_instance.cc' l='712' c='_ZNK3tvm7codegen10LLVMTarget17SetTargetMetadataEPN4llvm6ModuleE'/>
<size>800</size>
<use f='tvm/src/target/llvm/llvm_module.cc' l='101' c='_ZN3tvm7codegen14LLVMModuleNode4InitESt10unique_ptrIN4llvm6ModuleESt14default_deleteIS4_EES2_INS0_12LLVMInstanceES5_IS8_EE'/>
<use f='tvm/src/target/llvm/llvm_module.cc' l='120'/>
<use f='tvm/src/target/llvm/llvm_module.cc' l='123'/>
<use f='tvm/src/target/llvm/llvm_module.cc' l='185' c='_ZN3tvm7codegen14LLVMModuleNode10SaveToFileERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES9_'/>
<use f='tvm/src/target/llvm/llvm_module.cc' l='205' c='_ZN3tvm7codegen14LLVMModuleNode10SaveToFileERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES9_'/>
<use f='tvm/src/target/llvm/llvm_module.cc' l='251' c='_ZN3tvm7codegen14LLVMModuleNode9GetSourceERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE'/>
<use f='tvm/src/target/llvm/llvm_module.cc' l='336' c='_ZN3tvm7codegen14LLVMModuleNode4InitESt10unique_ptrIN4llvm6ModuleESt14default_deleteIS4_EES2_INS0_12LLVMInstanceES5_IS8_EE'/>
<use f='tvm/src/target/llvm/llvm_module.cc' l='345' c='_ZN3tvm7codegen14LLVMModuleNode6LoadIRERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE'/>
<use f='tvm/src/target/llvm/llvm_module.cc' l='436'/>
<use f='tvm/src/target/llvm/llvm_module.cc' l='489'/>
<size>800</size>
