<dec f='include/c++/10/bits/stl_queue.h' l='498' type='_Compare'/>
<use f='include/c++/10/bits/stl_queue.h' l='515' u='w' c='_ZNSt14priority_queueC1Ev'/>
<use f='include/c++/10/bits/stl_queue.h' l='519' u='w' c='_ZNSt14priority_queueC1ERKT1_RKT0_'/>
<use f='include/c++/10/bits/stl_queue.h' l='520' c='_ZNSt14priority_queueC1ERKT1_RKT0_'/>
<use f='include/c++/10/bits/stl_queue.h' l='524' u='w' c='_ZNSt14priority_queueC1ERKT1_OT0_'/>
<use f='include/c++/10/bits/stl_queue.h' l='525' c='_ZNSt14priority_queueC1ERKT1_OT0_'/>
<use f='include/c++/10/bits/stl_queue.h' l='530' u='w' c='_ZNSt14priority_queueC1ERKTL0__'/>
<use f='include/c++/10/bits/stl_queue.h' l='534' u='w' c='_ZNSt14priority_queueC1ERKT1_RKTL0__'/>
<use f='include/c++/10/bits/stl_queue.h' l='541' u='w' c='_ZNSt14priority_queueC1ERKT1_RKT0_RKTL0__'/>
<use f='include/c++/10/bits/stl_queue.h' l='542' c='_ZNSt14priority_queueC1ERKT1_RKT0_RKTL0__'/>
<use f='include/c++/10/bits/stl_queue.h' l='546' u='w' c='_ZNSt14priority_queueC1ERKT1_OT0_RKTL0__'/>
<use f='include/c++/10/bits/stl_queue.h' l='547' c='_ZNSt14priority_queueC1ERKT1_OT0_RKTL0__'/>
<use f='include/c++/10/bits/stl_queue.h' l='551' u='w' c='_ZNSt14priority_queueC1ERKSt14priority_queueIT_T0_T1_ERKTL0__'/>
<use f='include/c++/10/bits/stl_queue.h' l='555' u='w' c='_ZNSt14priority_queueC1EOSt14priority_queueIT_T0_T1_ERKTL0__'/>
<use f='include/c++/10/bits/stl_queue.h' l='589' u='w' c='_ZNSt14priority_queueC1ETL0__S0_RKT1_RKT0_'/>
<use f='include/c++/10/bits/stl_queue.h' l='593' c='_ZNSt14priority_queueC1ETL0__S0_RKT1_RKT0_'/>
<use f='include/c++/10/bits/stl_queue.h' l='600' u='w' c='_ZNSt14priority_queueC1ETL0__S0_RKT1_OT0_'/>
<use f='include/c++/10/bits/stl_queue.h' l='604' c='_ZNSt14priority_queueC1ETL0__S0_RKT1_OT0_'/>
<use f='include/c++/10/bits/stl_queue.h' l='643' c='_ZNSt14priority_queue4pushERKNT0_10value_typeE'/>
<use f='include/c++/10/bits/stl_queue.h' l='651' c='_ZNSt14priority_queue4pushEONT0_10value_typeE'/>
<use f='include/c++/10/bits/stl_queue.h' l='659' c='_ZNSt14priority_queue7emplaceEDpOTL0__'/>
<use f='include/c++/10/bits/stl_queue.h' l='678' c='_ZNSt14priority_queue3popEv'/>
<use f='include/c++/10/bits/stl_queue.h' l='696' c='_ZNSt14priority_queue4swapERSt14priority_queueIT_T0_T1_E'/>
