<inh f='tvm/include/tvm/ir/expr.h' l='112' c='tvm::PrimExpr'/>
<def f='tvm/include/tvm/tir/expr.h' l='180' ll='184'/>
<use f='tvm/include/tvm/tir/expr.h' l='183' c='_ZN3tvm3tir3SubC1ERKS1_'/>
<use f='tvm/include/tvm/tir/expr.h' l='183' c='_ZN3tvm3tir3SubC1EOS1_'/>
<use f='tvm/include/tvm/tir/expr.h' l='183' c='_ZN3tvm3tir3SubaSERKS1_'/>
<use f='tvm/include/tvm/tir/expr.h' l='183' c='_ZN3tvm3tir3SubaSERKS1_'/>
<use f='tvm/include/tvm/tir/expr.h' l='183' c='_ZN3tvm3tir3SubaSEOS1_'/>
<use f='tvm/include/tvm/tir/expr.h' l='183' c='_ZN3tvm3tir3SubaSEOS1_'/>
<size>8</size>
<doc f='tvm/include/tvm/tir/expr.h' l='176'>/*!
 * \brief Managed reference to SubNode
 * \sa SubNode
 */</doc>
<fun r='_ZN3tvm3tir3SubC1ENS_8PrimExprES2_NS_4SpanE'/>
<fun r='_ZN3tvm3tir3SubC1Ev'/>
<fun r='_ZN3tvm3tir3SubC1ENS_7runtime9ObjectPtrINS2_6ObjectEEE'/>
<fun r='_ZN3tvm3tir3SubC1ERKS1_'/>
<fun r='_ZN3tvm3tir3SubC1EOS1_'/>
<fun r='_ZNK3tvm3tir3Sub3getEv'/>
<use f='tvm/src/arith/const_fold.h' l='156' c='_ZN3tvm5arith12TryConstFoldENS_8PrimExprES1_'/>
<size>8</size>
<use f='tvm/src/arith/pattern_match.h' l='391' c='_ZN3tvm5arithmiERKNS0_7PatternIT_EERKNS1_IT0_EE'/>
<use f='tvm/src/arith/pattern_match.h' l='391' c='_ZN3tvm5arithmiERKNS0_7PatternIT_EERKNS1_IT0_EE'/>
<use f='tvm/src/arith/pattern_match.h' l='391' c='_ZN3tvm5arithmiERKNS0_7PatternIT_EEl'/>
<use f='tvm/src/arith/pattern_match.h' l='391' c='_ZN3tvm5arithmiElRKNS0_7PatternIT_EE'/>
<use f='tvm/src/arith/canonical_simplify.cc' l='743' c='_ZN3tvm5arith19CanonicalSimplifier4Impl10VisitExpr_EPKNS_3tir7SubNodeE'/>
<size>8</size>
<use f='tvm/src/arith/int_set.cc' l='145' c='_ZN3tvm5arith7CombineEPNS0_8AnalyzerENS0_11IntervalSetES3_NS_7runtime8DataTypeE'/>
<use f='tvm/src/arith/int_set.cc' l='429' c='_ZN3tvm5arith20IntervalSetEvaluator10VisitExpr_EPKNS_3tir7SubNodeE'/>
<size>8</size>
<use f='tvm/src/arith/iter_affine_map.cc' l='1242' c='_ZN3tvm5arith15IterMapRewriter10VisitExpr_EPKNS_3tir7SubNodeE'/>
<use f='tvm/src/arith/iter_affine_map.cc' l='1249' c='_ZN3tvm5arith15IterMapRewriter10VisitExpr_EPKNS_3tir7SubNodeE'/>
<size>8</size>
<use f='tvm/src/arith/rewrite_simplify.cc' l='260' c='_ZN3tvm5arith17RewriteSimplifier4Impl10VisitExpr_EPKNS_3tir7SubNodeE'/>
<size>8</size>
<use f='tvm/src/relay/backend/contrib/example_target_hooks/relay_to_tir.cc' l='138' c='_ZN3tvm5relay7contrib20example_target_hooks12_GLOBAL__N_120ConvertAddToSubtract30ReplaceAddWithSubtractPrimFuncERKNS0_8FunctionE'/>
<use f='tvm/src/relay/backend/contrib/example_target_hooks/relay_to_tir.cc' l='138' c='_ZN3tvm5relay7contrib20example_target_hooks12_GLOBAL__N_120ConvertAddToSubtract30ReplaceAddWithSubtractPrimFuncERKNS0_8FunctionE'/>
<use f='tvm/src/relay/backend/contrib/example_target_hooks/relay_to_tir.cc' l='141' c='_ZN3tvm5relay7contrib20example_target_hooks12_GLOBAL__N_120ConvertAddToSubtract30ReplaceAddWithSubtractPrimFuncERKNS0_8FunctionE'/>
<size>8</size>
<use f='tvm/src/te/autodiff/ad_simplify.cc' l='200' c='_ZN3tvm2te23NonzeroConditionFunctor10VisitExpr_EPKNS_3tir7SubNodeE'/>
<size>8</size>
<use f='tvm/src/te/autodiff/jacobian.cc' l='103' c='_ZN3tvm2te15JacobianMutator10VisitExpr_EPKNS_3tir8CallNodeE'/>
<use f='tvm/src/te/autodiff/jacobian.cc' l='107' c='_ZN3tvm2te15JacobianMutator10VisitExpr_EPKNS_3tir8CallNodeE'/>
<use f='tvm/src/te/autodiff/jacobian.cc' l='128' c='_ZN3tvm2te15JacobianMutator10VisitExpr_EPKNS_3tir7SubNodeE'/>
<use f='tvm/src/te/autodiff/jacobian.cc' l='135' c='_ZN3tvm2te15JacobianMutator10VisitExpr_EPKNS_3tir7DivNodeE'/>
<use f='tvm/src/te/autodiff/jacobian.cc' l='141' c='_ZN3tvm2te15JacobianMutator10VisitExpr_EPKNS_3tir12FloorDivNodeE'/>
<size>8</size>
<use f='tvm/src/tir/ir/expr.cc' l='261'/>
<size>8</size>
<fun r='_ZN3tvm3tir3SubC1ENS_8PrimExprES2_NS_4SpanE'/>
<use f='tvm/src/tir/ir/expr_functor.cc' l='193' c='_ZN3tvm3tir11ExprMutator10VisitExpr_EPKNS0_7SubNodeE'/>
<size>8</size>
<use f='tvm/src/tir/op/op.cc' l='351' c='_ZN3tvm3subENS_8PrimExprES0_NS_4SpanE'/>
<use f='tvm/src/tir/op/op.cc' l='352' c='_ZN3tvm3subENS_8PrimExprES0_NS_4SpanE'/>
<size>8</size>
