<inh f='tvm/include/tvm/runtime/object.h' l='511' c='tvm::runtime::ObjectRef'/>
<def f='tvm/include/tvm/runtime/module.h' l='50' ll='89'/>
<use f='tvm/include/tvm/runtime/module.h' l='73' c='_ZN3tvm7runtime6Module6ImportES1_'/>
<use f='tvm/include/tvm/runtime/module.h' l='85' c='_ZN3tvm7runtime6Module12LoadFromFileERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES9_'/>
<use f='tvm/include/tvm/runtime/module.h' l='183' c='_ZN3tvm7runtime10ModuleNode6ImportENS0_6ModuleE'/>
<use f='tvm/include/tvm/runtime/module.h' l='193' c='_ZNK3tvm7runtime10ModuleNode7importsEv'/>
<use f='tvm/include/tvm/runtime/module.h' l='230'/>
<use f='tvm/include/tvm/runtime/module.h' l='233'/>
<use f='tvm/include/tvm/runtime/module.h' l='276' c='_ZN3tvm7runtime6Module6ImportES1_'/>
<use f='tvm/include/tvm/runtime/module.h' l='284' c='_ZN3tvm7runtimelsERSoRKNS0_6ModuleE'/>
<use f='tvm/include/tvm/runtime/packed_func.h' l='592' c='_ZNK3tvm7runtime12TVMPODValue_cvNS0_6ModuleEEv'/>
<use f='tvm/include/tvm/runtime/packed_func.h' l='594' c='_ZNK3tvm7runtime12TVMPODValue_cvNS0_6ModuleEEv'/>
<use f='tvm/include/tvm/runtime/packed_func.h' l='597' c='_ZNK3tvm7runtime12TVMPODValue_cvNS0_6ModuleEEv'/>
<use f='tvm/include/tvm/runtime/packed_func.h' l='920' c='_ZN3tvm7runtime11TVMRetValueaSENS0_6ModuleE'/>
<use f='tvm/include/tvm/runtime/packed_func.h' l='1905' c='_ZN3tvm7runtime11TVMRetValueaSET_'/>
<size>8</size>
<doc f='tvm/include/tvm/runtime/module.h' l='47'>/*!
 * \brief Module container of TVM.
 */</doc>
<fun r='_ZN3tvm7runtime6ModuleC1Ev'/>
<fun r='_ZN3tvm7runtime6ModuleC1ENS0_9ObjectPtrINS0_6ObjectEEE'/>
<fun r='_ZN3tvm7runtime6Module11GetFunctionERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEb'/>
<fun r='_ZN3tvm7runtime6Module6ImportES1_'/>
<fun r='_ZN3tvm7runtime6ModuleptEv'/>
<fun r='_ZNK3tvm7runtime6ModuleptEv'/>
<fun r='_ZN3tvm7runtime6Module12LoadFromFileERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES9_'/>
<fun r='_ZN3tvm7runtime6Module6ImportES1_'/>
<fun r='_ZN3tvm7runtime6ModuleptEv'/>
<fun r='_ZNK3tvm7runtime6ModuleptEv'/>
<fun r='_ZN3tvm7runtime6Module11GetFunctionERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEb'/>
<use f='tvm/include/tvm/target/target_kind.h' l='77'/>
<size>8</size>
<use f='tvm/include/tvm/driver/driver_api.h' l='150' c='_ZN3tvm5buildERKNS_8IRModuleERKNS_6TargetES5_'/>
<use f='tvm/include/tvm/driver/driver_api.h' l='162' c='_ZN3tvm5buildERKNS_7runtime3MapINS_6TargetENS_8IRModuleEvvEERKS2_'/>
<use f='tvm/include/tvm/driver/driver_api.h' l='173' c='_ZN3tvm5buildERKNS_7runtime3MapINS0_6StringENS_8IRModuleEvvEERKNS_6TargetE'/>
<size>8</size>
<use f='tvm/include/tvm/target/codegen.h' l='48' c='_ZN3tvm7codegen5BuildENS_8IRModuleENS_6TargetE'/>
<use f='tvm/include/tvm/target/codegen.h' l='60' c='_ZN3tvm7codegen14PackImportsToCB5cxx11ERKNS_7runtime6ModuleEb'/>
<use f='tvm/include/tvm/target/codegen.h' l='73' c='_ZN3tvm7codegen17PackImportsToLLVMERKNS_7runtime6ModuleEbRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE'/>
<use f='tvm/include/tvm/target/codegen.h' l='73' c='_ZN3tvm7codegen17PackImportsToLLVMERKNS_7runtime6ModuleEbRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE'/>
<size>8</size>
<use f='tvm/src/driver/driver_api.cc' l='413' c='_ZN3tvm12TIRToRuntimeERKNS_7runtime3MapINS_6TargetENS_8IRModuleEvvEERKS2_'/>
<use f='tvm/src/driver/driver_api.cc' l='417' c='_ZN3tvm12TIRToRuntimeERKNS_7runtime3MapINS_6TargetENS_8IRModuleEvvEERKS2_'/>
<use f='tvm/src/driver/driver_api.cc' l='479' c='_ZN3tvm12TIRToRuntimeERKNS_7runtime3MapINS_6TargetENS_8IRModuleEvvEERKS2_'/>
<use f='tvm/src/driver/driver_api.cc' l='497' c='_ZN3tvm5buildERKNS_7runtime3MapINS_6TargetENS_8IRModuleEvvEERKS2_'/>
<use f='tvm/src/driver/driver_api.cc' l='502' c='_ZN3tvm5buildERKNS_7runtime3MapINS0_6StringENS_8IRModuleEvvEERKNS_6TargetE'/>
<use f='tvm/src/driver/driver_api.cc' l='518' c='_ZN3tvm5buildERKNS_8IRModuleERKNS_6TargetES5_'/>
<size>8</size>
<use f='tvm/src/runtime/meta_data.h' l='60' c='_ZN3tvm7runtime20MetadataModuleCreateENS0_8metadata8MetadataE'/>
<size>8</size>
<use f='tvm/include/tvm/runtime/profiling.h' l='537' c='_ZN3tvm7runtime9profiling15ProfileFunctionENS0_6ModuleENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEiiiNS0_5ArrayINS1_15MetricCollectorEvEE'/>
<size>8</size>
<use f='tvm/src/relay/backend/utils.h' l='298'/>
<size>8</size>
<use f='tvm/src/target/source/codegen_source_base.h' l='142' c='_ZN3tvm7codegen18SourceModuleCreateENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES6_'/>
<use f='tvm/src/target/source/codegen_source_base.h' l='152' c='_ZN3tvm7codegen19CSourceModuleCreateERKNS_7runtime6StringES4_RKNS1_5ArrayIS2_vEES8_'/>
<use f='tvm/src/target/source/codegen_source_base.h' l='166' c='_ZN3tvm7codegen20CreateMetadataModuleERKSt13unordered_mapINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_7runtime7NDArrayESt4hashIS7_ESt8equal1760940'/>
<use f='tvm/src/target/source/codegen_source_base.h' l='167' c='_ZN3tvm7codegen20CreateMetadataModuleERKSt13unordered_mapINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_7runtime7NDArrayESt4hashIS7_ESt8equal1760940'/>
<use f='tvm/src/target/source/codegen_source_base.h' l='168' c='_ZN3tvm7codegen20CreateMetadataModuleERKSt13unordered_mapINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_7runtime7NDArrayESt4hashIS7_ESt8equal1760940'/>
<use f='tvm/src/target/source/codegen_source_base.h' l='178' c='_ZN3tvm7codegen24DeviceSourceModuleCreateENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES6_St13unordered_mapIS6_NS_7runtime12FunctionInfoESt4has3715380'/>
<use f='tvm/src/target/source/codegen_source_base.h' l='189' c='_ZN3tvm7codegen30CreateCSourceCrtMetadataModuleERKNS_7runtime5ArrayINS1_6ModuleEvEENS_6TargetENS1_8metadata8MetadataE'/>
<use f='tvm/src/target/source/codegen_source_base.h' l='189' c='_ZN3tvm7codegen30CreateCSourceCrtMetadataModuleERKNS_7runtime5ArrayINS1_6ModuleEvEENS_6TargetENS1_8metadata8MetadataE'/>
<use f='tvm/src/relay/backend/te_compiler.h' l='105' c='_ZN3tvm5relay3tec14TECompilerNode22LowerExternalFunctionsEv'/>
<use f='tvm/src/relay/backend/aot_executor_codegen.cc' l='986'/>
<use f='tvm/src/relay/backend/aot_executor_codegen.cc' l='1037' c='_ZN3tvm5relay7backend18AOTExecutorCodegenC1EPNS_7runtime6ModuleERKNS3_5ArrayINS_6TargetEvEE'/>
<use f='tvm/src/relay/backend/aot_executor_codegen.cc' l='1229' c='_ZN3tvm5relay7backend18AOTExecutorCodegen7CodegenENS_8IRModuleENS0_8FunctionENS_7runtime6StringE'/>
<use f='tvm/src/relay/backend/aot_executor_codegen.cc' l='1356' c='_ZN3tvm5relay7backend24AOTExecutorCodegenModule4initEPvRKNS_7runtime5ArrayINS_6TargetEvEE'/>
<use f='tvm/src/relay/backend/aot_executor_codegen.cc' l='1373' c='_ZN3tvm5relay7backend24AOTExecutorCodegenModule20get_external_modulesEv'/>
<use f='tvm/src/relay/backend/aot_executor_codegen.cc' l='1381' c='_ZN3tvm5relay7backend27CreateAOTExecutorCodegenModEv'/>
<use f='tvm/src/relay/backend/aot_executor_codegen.cc' l='1383' c='_ZN3tvm5relay7backend27CreateAOTExecutorCodegenModEv'/>
<size>8</size>
<use f='tvm/src/driver/internal_driver_api.h' l='44' c='_ZN3tvm12TIRToRuntimeERKNS_7runtime3MapINS_6TargetENS_8IRModuleEvvEERKS2_'/>
<use f='tvm/src/target/metadata_module.h' l='55' c='_ZN3tvm7codegen20CreateMetadataModuleERKSt13unordered_mapINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_7runtime7NDArrayESt4hashIS7_ESt8equal6263688'/>
<use f='tvm/src/target/metadata_module.h' l='56' c='_ZN3tvm7codegen20CreateMetadataModuleERKSt13unordered_mapINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_7runtime7NDArrayESt4hashIS7_ESt8equal6263688'/>
<use f='tvm/src/target/metadata_module.h' l='57' c='_ZN3tvm7codegen20CreateMetadataModuleERKSt13unordered_mapINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_7runtime7NDArrayESt4hashIS7_ESt8equal6263688'/>
<use f='tvm/src/relay/backend/build_module.cc' l='59'/>
<use f='tvm/src/relay/backend/build_module.cc' l='64' c='_ZN3tvm5relay7backend15ExecutorCodegen4InitEPNS_7runtime6ModuleERKNS3_5ArrayINS_6TargetEvEE'/>
<use f='tvm/src/relay/backend/build_module.cc' l='89' c='_ZN3tvm5relay7backend15ExecutorCodegen18GetExternalModulesEv'/>
<use f='tvm/src/relay/backend/build_module.cc' l='90' c='_ZN3tvm5relay7backend15ExecutorCodegen18GetExternalModulesEv'/>
<use f='tvm/src/relay/backend/build_module.cc' l='105'/>
<use f='tvm/src/relay/backend/build_module.cc' l='243' c='_ZN3tvm5relay7backend16RelayBuildModule9GetModuleEv'/>
<use f='tvm/src/relay/backend/build_module.cc' l='466' c='_ZN3tvm5relay7backend16RelayBuildModule10BuildRelayENS_8IRModuleERKNS_7runtime6StringE'/>
<use f='tvm/src/relay/backend/build_module.cc' l='499' c='_ZN3tvm5relay7backend16RelayBuildCreateEv'/>
<use f='tvm/src/relay/backend/build_module.cc' l='501' c='_ZN3tvm5relay7backend16RelayBuildCreateEv'/>
<size>8</size>
<use f='tvm/src/relay/backend/contrib/codegen_c/codegen_c.h' l='68' c='_ZN3tvm5relay7contrib24CSourceModuleCodegenBase19CreateCSourceModuleERKNS_7runtime9ObjectRefE'/>
<use f='tvm/src/relay/backend/contrib/codegen_c/codegen.cc' l='247' c='_ZN3tvm5relay7contrib14CodegenCModule19CreateCSourceModuleEv'/>
<use f='tvm/src/relay/backend/contrib/codegen_c/codegen.cc' l='331' c='_ZN3tvm5relay7contrib14CodegenCModule8FinalizeEv'/>
<use f='tvm/src/relay/backend/contrib/codegen_c/codegen.cc' l='373' c='_ZN3tvm5relay7contrib13CCompilerImplEv'/>
<use f='tvm/src/relay/backend/contrib/codegen_c/codegen.cc' l='376' c='_ZN3tvm5relay7contrib13CCompilerImplEv'/>
<use f='tvm/src/relay/backend/contrib/codegen_c/codegen.cc' l='377' c='_ZN3tvm5relay7contrib13CCompilerImplEv'/>
<size>8</size>
<use f='tvm/src/relay/backend/contrib/example_target_hooks/target.cc' l='29' c='_ZN3tvm5relay7contrib20example_target_hooks12TIRToRuntimeENS_8IRModuleENS_6TargetE'/>
<size>8</size>
<use f='tvm/src/relay/backend/contrib/example_target_hooks/tir_to_runtime.cc' l='47' c='_ZN3tvm5relay7contrib20example_target_hooks12TIRToRuntimeENS_8IRModuleENS_6TargetE'/>
<size>8</size>
<use f='tvm/src/relay/backend/graph_executor_codegen.cc' l='193' c='_ZN3tvm5relay7backend20GraphExecutorCodegenC1EPNS_7runtime6ModuleERKNS3_5ArrayINS_6TargetEvEE'/>
<use f='tvm/src/relay/backend/graph_executor_codegen.cc' l='265' c='_ZN3tvm5relay7backend20GraphExecutorCodegen7CodegenENS_8IRModuleENS0_8FunctionENS_7runtime6StringE'/>
<use f='tvm/src/relay/backend/graph_executor_codegen.cc' l='613'/>
<use f='tvm/src/relay/backend/graph_executor_codegen.cc' l='646' c='_ZN3tvm5relay7backend26GraphExecutorCodegenModule11GetFunctionERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKNS_7runtime9ObjectPtrINSB_6ObjectEEE'/>
<use f='tvm/src/relay/backend/graph_executor_codegen.cc' l='703' c='_ZN3tvm5relay7backend21CreateGraphCodegenModEv'/>
<use f='tvm/src/relay/backend/graph_executor_codegen.cc' l='705' c='_ZN3tvm5relay7backend21CreateGraphCodegenModEv'/>
<size>8</size>
<use f='tvm/src/relay/backend/interpreter.cc' l='407' c='_ZN3tvm5relay11Interpreter15TIRToPackedFuncERKNS_9GlobalVarERKNS_7runtime5ArrayIS2_vEENS_6TargetE'/>
<size>8</size>
<use f='tvm/src/relay/backend/te_compiler.cc' l='262' c='_ZN3tvm5relay3tec14TECompilerImpl22LowerExternalFunctionsEv'/>
<use f='tvm/src/relay/backend/te_compiler.cc' l='263' c='_ZN3tvm5relay3tec14TECompilerImpl22LowerExternalFunctionsEv'/>
<use f='tvm/src/relay/backend/te_compiler.cc' l='287' c='_ZN3tvm5relay3tec14TECompilerImpl22LowerExternalFunctionsEv'/>
<use f='tvm/src/relay/backend/te_compiler.cc' l='1220' c='_ZN3tvm5relay3tec7LowerTEERKNS_8IRModuleERKNS_7runtime6StringESt8functionIFvNS_8BaseFuncEEENS_17CompilationConfigE'/>
<use f='tvm/src/relay/backend/te_compiler.cc' l='1221' c='_ZN3tvm5relay3tec7LowerTEERKNS_8IRModuleERKNS_7runtime6StringESt8functionIFvNS_8BaseFuncEEENS_17CompilationConfigE'/>
<use f='tvm/src/relay/backend/te_compiler.cc' l='1222' c='_ZN3tvm5relay3tec7LowerTEERKNS_8IRModuleERKNS_7runtime6StringESt8functionIFvNS_8BaseFuncEEENS_17CompilationConfigE'/>
<size>8</size>
<use f='tvm/include/tvm/runtime/vm/executable.h' l='111' c='_ZN3tvm7runtime2vm10Executable4LoadERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS0_6ModuleE'/>
<use f='tvm/include/tvm/runtime/vm/executable.h' l='111' c='_ZN3tvm7runtime2vm10Executable4LoadERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS0_6ModuleE'/>
<use f='tvm/include/tvm/runtime/vm/executable.h' l='220' c='_ZNK3tvm7runtime2vm10Executable6GetLibEv'/>
<use f='tvm/include/tvm/runtime/vm/executable.h' l='232' c='_ZN3tvm7runtime2vm10Executable6SetLibERKNS0_6ModuleE'/>
<use f='tvm/src/relay/backend/vm/compiler.h' l='136' c='_ZNK3tvm5relay2vm10VMCompiler13GetExecutableEv'/>
<use f='tvm/src/relay/backend/vm/compiler.cc' l='888' c='_ZNK3tvm5relay2vm10VMCompiler13GetExecutableEv'/>
<use f='tvm/src/relay/backend/vm/compiler.cc' l='895' c='_ZNK3tvm5relay2vm10VMCompiler13GetExecutableEv'/>
<use f='tvm/src/relay/backend/vm/compiler.cc' l='1172' c='_ZN3tvm5relay2vm10VMCompiler7CodegenEv'/>
<use f='tvm/src/relay/backend/vm/compiler.cc' l='1173' c='_ZN3tvm5relay2vm10VMCompiler7CodegenEv'/>
<use f='tvm/src/relay/backend/vm/compiler.cc' l='1191' c='_ZN3tvm5relay2vm10VMCompiler7CodegenEv'/>
<use f='tvm/src/relay/backend/vm/compiler.cc' l='1208' c='_ZN3tvm5relay2vm16CreateVMCompilerEv'/>
<use f='tvm/src/relay/backend/vm/compiler.cc' l='1210' c='_ZN3tvm5relay2vm16CreateVMCompilerEv'/>
<size>8</size>
<use f='tvm/src/runtime/aot_executor/aot_executor.h' l='63' c='_ZN3tvm7runtime11AotExecutorC1ENS0_6ModuleERKSt6vectorI8DLDeviceSaIS4_EE'/>
<use f='tvm/src/runtime/aot_executor/aot_executor.h' l='135'/>
<use f='tvm/src/runtime/aot_executor/aot_executor.cc' l='39' c='_ZN3tvm7runtime11AotExecutorC1ENS0_6ModuleERKSt6vectorI8DLDeviceSaIS4_EE'/>
<size>8</size>
<use f='tvm/src/runtime/aot_executor/aot_executor_factory.h' l='80' c='_ZN3tvm7runtime18AotExecutorFactory14ExecutorCreateERKSt6vectorI8DLDeviceSaIS3_EE'/>
<use f='tvm/src/runtime/aot_executor/aot_executor_factory.cc' l='65' c='_ZN3tvm7runtime18AotExecutorFactory11GetFunctionERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKNS0_9ObjectPtrINS0_6ObjectEEE'/>
<use f='tvm/src/runtime/aot_executor/aot_executor_factory.cc' l='89' c='_ZN3tvm7runtime18AotExecutorFactory14ExecutorCreateERKSt6vectorI8DLDeviceSaIS3_EE'/>
<use f='tvm/src/runtime/aot_executor/aot_executor_factory.cc' l='93' c='_ZN3tvm7runtime18AotExecutorFactory14ExecutorCreateERKSt6vectorI8DLDeviceSaIS3_EE'/>
<use f='tvm/src/runtime/aot_executor/aot_executor_factory.cc' l='96' c='_ZN3tvm7runtime34AotExecutorFactoryModuleLoadBinaryEPv'/>
<use f='tvm/src/runtime/aot_executor/aot_executor_factory.cc' l='112' c='_ZN3tvm7runtime34AotExecutorFactoryModuleLoadBinaryEPv'/>
<use f='tvm/src/runtime/aot_executor/aot_executor_factory.cc' l='130'/>
<size>8</size>
<use f='tvm/src/runtime/c_runtime_api.cc' l='401' c='TVMModImport'/>
<size>8</size>
<use f='tvm/src/runtime/const_loader_module.cc' l='84' c='_ZN3tvm7runtime21ConstLoaderModuleNode11GetFunctionERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKNS0_9ObjectPtrINS0_6ObjectEEE'/>
<use f='tvm/src/runtime/const_loader_module.cc' l='126' c='_ZN3tvm7runtime21ConstLoaderModuleNode13InitSubModuleERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE'/>
<use f='tvm/src/runtime/const_loader_module.cc' l='175' c='_ZN3tvm7runtime21ConstLoaderModuleNode14LoadFromBinaryEPv'/>
<use f='tvm/src/runtime/const_loader_module.cc' l='217' c='_ZN3tvm7runtime21ConstLoaderModuleNode14LoadFromBinaryEPv'/>
<use f='tvm/src/runtime/const_loader_module.cc' l='232' c='_ZN3tvm7runtime23ConstLoaderModuleCreateERKSt13unordered_mapINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS0_7NDArrayESt4hashIS7_ESt8equal_toI7376922'/>
<use f='tvm/src/runtime/const_loader_module.cc' l='236' c='_ZN3tvm7runtime23ConstLoaderModuleCreateERKSt13unordered_mapINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS0_7NDArrayESt4hashIS7_ESt8equal_toI7376922'/>
<size>8</size>
<use f='tvm/src/runtime/library_module.h' l='45' c='_ZN3tvm7runtime20LoadModuleFromBinaryERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEPN4dmlc6StreamE'/>
<use f='tvm/src/runtime/library_module.h' l='109' c='_ZN3tvm7runtime23CreateModuleFromLibraryENS0_9ObjectPtrINS0_7LibraryEEESt8functionIFNS0_10PackedFuncEPFiP8TVMValuePiiS7_S8_PvERKNS1_INS0_6ObjectEEEEE'/>
<size>8</size>
<use f='tvm/src/runtime/rpc/rpc_session.h' l='269' c='_ZN3tvm7runtime22CreateRPCSessionModuleESt10shared_ptrINS0_10RPCSessionEE'/>
<use f='tvm/src/runtime/rpc/rpc_session.h' l='290' c='_ZN3tvm7runtime22CreateRPCSessionModuleESt10shared_ptrINS0_10RPCSessionEE'/>
<use f='tvm/src/runtime/rpc/rpc_session.h' l='297' c='_ZN3tvm7runtime19RPCModuleGetSessionENS0_6ModuleE'/>
<use f='tvm/src/runtime/graph_executor/graph_executor.h' l='104' c='_ZN3tvm7runtime13GraphExecutor4InitERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS0_6ModuleERKSt6vectorI8DLDeviceSaISC_EENS0_10PackedFuncE'/>
<use f='tvm/src/runtime/graph_executor/graph_executor.h' l='461'/>
<use f='tvm/src/runtime/graph_executor/debug/graph_executor_debug.cc' l='471' c='_ZN3tvm7runtime24GraphExecutorDebugCreateERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKNS0_6ModuleERKSt6vectorI8DLDeviceSaISD_EENS0_10PackedFuncE'/>
<use f='tvm/src/runtime/graph_executor/debug/graph_executor_debug.cc' l='471' c='_ZN3tvm7runtime24GraphExecutorDebugCreateERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKNS0_6ModuleERKSt6vectorI8DLDeviceSaISD_EENS0_10PackedFuncE'/>
<use f='tvm/src/runtime/graph_executor/debug/graph_executor_debug.cc' l='476' c='_ZN3tvm7runtime24GraphExecutorDebugCreateERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKNS0_6ModuleERKSt6vectorI8DLDeviceSaISD_EENS0_10PackedFuncE'/>
<size>8</size>
<use f='tvm/src/runtime/graph_executor/graph_executor.cc' l='77' c='_ZN3tvm7runtime13GraphExecutor4InitERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS0_6ModuleERKSt6vectorI8DLDeviceSaISC_EENS0_10PackedFuncE'/>
<use f='tvm/src/runtime/graph_executor/graph_executor.cc' l='326' c='_ZN3tvm7runtime13GraphExecutor24DefaultLookupLinkedParamENS0_7TVMArgsEPNS0_11TVMRetValueE'/>
<use f='tvm/src/runtime/graph_executor/graph_executor.cc' l='690' c='_ZN3tvm7runtime19GraphExecutorCreateERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKNS0_6ModuleERKSt6vectorI8DLDeviceSaISD_EENS0_10PackedFuncE'/>
<use f='tvm/src/runtime/graph_executor/graph_executor.cc' l='690' c='_ZN3tvm7runtime19GraphExecutorCreateERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKNS0_6ModuleERKSt6vectorI8DLDeviceSaISD_EENS0_10PackedFuncE'/>
<use f='tvm/src/runtime/graph_executor/graph_executor.cc' l='695' c='_ZN3tvm7runtime19GraphExecutorCreateERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKNS0_6ModuleERKSt6vectorI8DLDeviceSaISD_EENS0_10PackedFuncE'/>
<size>8</size>
<use f='tvm/src/runtime/graph_executor/graph_executor_factory.h' l='82' c='_ZN3tvm7runtime20GraphExecutorFactory14ExecutorCreateERKSt6vectorI8DLDeviceSaIS3_EE'/>
<use f='tvm/src/runtime/graph_executor/graph_executor_factory.h' l='90' c='_ZN3tvm7runtime20GraphExecutorFactory19DebugExecutorCreateERKSt6vectorI8DLDeviceSaIS3_EE'/>
<use f='tvm/src/runtime/graph_executor/graph_executor_factory.h' l='98' c='_ZN3tvm7runtime20GraphExecutorFactory23CudaGraphExecutorCreateERKSt6vectorI8DLDeviceSaIS3_EE'/>
<use f='tvm/src/runtime/graph_executor/graph_executor_factory.cc' l='86' c='_ZN3tvm7runtime20GraphExecutorFactory11GetFunctionERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKNS0_9ObjectPtrINS0_6ObjectEEE'/>
<use f='tvm/src/runtime/graph_executor/graph_executor_factory.cc' l='119' c='_ZN3tvm7runtime20GraphExecutorFactory14ExecutorCreateERKSt6vectorI8DLDeviceSaIS3_EE'/>
<use f='tvm/src/runtime/graph_executor/graph_executor_factory.cc' l='124' c='_ZN3tvm7runtime20GraphExecutorFactory14ExecutorCreateERKSt6vectorI8DLDeviceSaIS3_EE'/>
<use f='tvm/src/runtime/graph_executor/graph_executor_factory.cc' l='127' c='_ZN3tvm7runtime20GraphExecutorFactory19DebugExecutorCreateERKSt6vectorI8DLDeviceSaIS3_EE'/>
<use f='tvm/src/runtime/graph_executor/graph_executor_factory.cc' l='148' c='_ZN3tvm7runtime20GraphExecutorFactory19DebugExecutorCreateERKSt6vectorI8DLDeviceSaIS3_EE'/>
<use f='tvm/src/runtime/graph_executor/graph_executor_factory.cc' l='154' c='_ZN3tvm7runtime20GraphExecutorFactory23CudaGraphExecutorCreateERKSt6vectorI8DLDeviceSaIS3_EE'/>
<use f='tvm/src/runtime/graph_executor/graph_executor_factory.cc' l='174' c='_ZN3tvm7runtime20GraphExecutorFactory23CudaGraphExecutorCreateERKSt6vectorI8DLDeviceSaIS3_EE'/>
<use f='tvm/src/runtime/graph_executor/graph_executor_factory.cc' l='179' c='_ZN3tvm7runtime36GraphExecutorFactoryModuleLoadBinaryEPv'/>
<use f='tvm/src/runtime/graph_executor/graph_executor_factory.cc' l='197' c='_ZN3tvm7runtime36GraphExecutorFactoryModuleLoadBinaryEPv'/>
<use f='tvm/src/runtime/graph_executor/graph_executor_factory.cc' l='216'/>
<use f='tvm/src/runtime/graph_executor/graph_executor_factory.cc' l='222' c='_ZN3tvm7runtime35GraphRuntimeFactoryModuleLoadBinaryEPv'/>
<size>8</size>
<use f='tvm/src/runtime/library_module.cc' l='71' c='_ZN3tvm7runtime14ModuleInternal14GetImportsAddrEPNS0_10ModuleNodeE'/>
<use f='tvm/src/runtime/library_module.cc' l='104' c='_ZN3tvm7runtime20LoadModuleFromBinaryERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEPN4dmlc6StreamE'/>
<use f='tvm/src/runtime/library_module.cc' l='134' c='_ZN3tvm7runtime17ProcessModuleBlobEPKcNS0_9ObjectPtrINS0_7LibraryEEESt8functionIFNS0_10PackedFuncEPFiP8TVMValuePiiS9_SA_PvERKNS3_INS0_6ObjectEEEEEPNS015931685'/>
<use f='tvm/src/runtime/library_module.cc' l='147' c='_ZN3tvm7runtime17ProcessModuleBlobEPKcNS0_9ObjectPtrINS0_7LibraryEEESt8functionIFNS0_10PackedFuncEPFiP8TVMValuePiiS9_SA_PvERKNS3_INS0_6ObjectEEEEEPNS015931685'/>
<use f='tvm/src/runtime/library_module.cc' l='158' c='_ZN3tvm7runtime17ProcessModuleBlobEPKcNS0_9ObjectPtrINS0_7LibraryEEESt8functionIFNS0_10PackedFuncEPFiP8TVMValuePiiS9_SA_PvERKNS3_INS0_6ObjectEEEEEPNS015931685'/>
<use f='tvm/src/runtime/library_module.cc' l='182' c='_ZN3tvm7runtime17ProcessModuleBlobEPKcNS0_9ObjectPtrINS0_7LibraryEEESt8functionIFNS0_10PackedFuncEPFiP8TVMValuePiiS9_SA_PvERKNS3_INS0_6ObjectEEEEEPNS015931685'/>
<use f='tvm/src/runtime/library_module.cc' l='200' c='_ZN3tvm7runtime23CreateModuleFromLibraryENS0_9ObjectPtrINS0_7LibraryEEESt8functionIFNS0_10PackedFuncEPFiP8TVMValuePiiS7_S8_PvERKNS1_INS0_6ObjectEEEEE'/>
<use f='tvm/src/runtime/library_module.cc' l='207' c='_ZN3tvm7runtime23CreateModuleFromLibraryENS0_9ObjectPtrINS0_7LibraryEEESt8functionIFNS0_10PackedFuncEPFiP8TVMValuePiiS7_S8_PvERKNS1_INS0_6ObjectEEEEE'/>
<use f='tvm/src/runtime/library_module.cc' l='213' c='_ZN3tvm7runtime23CreateModuleFromLibraryENS0_9ObjectPtrINS0_7LibraryEEESt8functionIFNS0_10PackedFuncEPFiP8TVMValuePiiS7_S8_PvERKNS1_INS0_6ObjectEEEEE'/>
<size>8</size>
<use f='tvm/src/runtime/metadata.cc' l='91' c='_ZN3tvm7runtime18MetadataModuleNode14LoadFromBinaryEv'/>
<use f='tvm/src/runtime/metadata.cc' l='92' c='_ZN3tvm7runtime18MetadataModuleNode14LoadFromBinaryEv'/>
<use f='tvm/src/runtime/metadata.cc' l='133' c='_ZN3tvm7runtime20MetadataModuleCreateENS0_8metadata8MetadataE'/>
<use f='tvm/src/runtime/metadata.cc' l='134' c='_ZN3tvm7runtime20MetadataModuleCreateENS0_8metadata8MetadataE'/>
<size>8</size>
<use f='tvm/src/runtime/module.cc' l='36' c='_ZN3tvm7runtime10ModuleNode6ImportENS0_6ModuleE'/>
<use f='tvm/src/runtime/module.cc' l='44' c='_ZN3tvm7runtime10ModuleNode6ImportENS0_6ModuleE'/>
<use f='tvm/src/runtime/module.cc' l='53' c='_ZN3tvm7runtime10ModuleNode6ImportENS0_6ModuleE'/>
<use f='tvm/src/runtime/module.cc' l='69' c='_ZN3tvm7runtime10ModuleNode11GetFunctionERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEb'/>
<use f='tvm/src/runtime/module.cc' l='79' c='_ZN3tvm7runtime6Module12LoadFromFileERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES9_'/>
<use f='tvm/src/runtime/module.cc' l='92' c='_ZN3tvm7runtime6Module12LoadFromFileERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES9_'/>
<use f='tvm/src/runtime/module.cc' l='114' c='_ZN3tvm7runtime10ModuleNode14GetFuncFromEnvERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE'/>
<use f='tvm/src/runtime/module.cc' l='179'/>
<use f='tvm/src/runtime/module.cc' l='183'/>
<use f='tvm/src/runtime/module.cc' l='187'/>
<use f='tvm/src/runtime/module.cc' l='191'/>
<use f='tvm/src/runtime/module.cc' l='195'/>
<use f='tvm/src/runtime/module.cc' l='202'/>
<use f='tvm/src/runtime/module.cc' l='204'/>
<use f='tvm/src/runtime/module.cc' l='209'/>
<size>8</size>
<fun r='_ZN3tvm7runtime6Module12LoadFromFileERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES9_'/>
<use f='tvm/src/runtime/profiling.cc' l='802' c='_ZN3tvm7runtime9profiling15ProfileFunctionENS0_6ModuleENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEiiiNS0_5ArrayINS1_15MetricCollectorEvEE'/>
<use f='tvm/src/runtime/profiling.cc' l='848'/>
<use f='tvm/src/runtime/profiling.cc' l='849'/>
<size>8</size>
<use f='tvm/src/runtime/rpc/rpc_endpoint.cc' l='537' c='_ZN3tvm7runtime11RPCEndpoint12EventHandler16HandleInitServerEv'/>
<size>8</size>
<use f='tvm/src/runtime/rpc/rpc_module.cc' l='184' c='_ZN3tvm7runtime13RPCModuleNode11GetFunctionERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKNS0_9ObjectPtrINS0_6ObjectEEE'/>
<use f='tvm/src/runtime/rpc/rpc_module.cc' l='204' c='_ZN3tvm7runtime13RPCModuleNode16GetTimeEvaluatorERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE8DLDeviceiiiiiiS9_'/>
<use f='tvm/src/runtime/rpc/rpc_module.cc' l='209' c='_ZN3tvm7runtime13RPCModuleNode16GetTimeEvaluatorERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE8DLDeviceiiiiiiS9_'/>
<use f='tvm/src/runtime/rpc/rpc_module.cc' l='216' c='_ZN3tvm7runtime13RPCModuleNode10LoadModuleENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE'/>
<use f='tvm/src/runtime/rpc/rpc_module.cc' l='221' c='_ZN3tvm7runtime13RPCModuleNode12ImportModuleENS0_6ModuleE'/>
<use f='tvm/src/runtime/rpc/rpc_module.cc' l='223' c='_ZN3tvm7runtime13RPCModuleNode12ImportModuleENS0_6ModuleE'/>
<use f='tvm/src/runtime/rpc/rpc_module.cc' l='250'/>
<use f='tvm/src/runtime/rpc/rpc_module.cc' l='254'/>
<use f='tvm/src/runtime/rpc/rpc_module.cc' l='256'/>
<use f='tvm/src/runtime/rpc/rpc_module.cc' l='258'/>
<use f='tvm/src/runtime/rpc/rpc_module.cc' l='258'/>
<use f='tvm/src/runtime/rpc/rpc_module.cc' l='263' c='_ZNK3tvm7runtime14RPCWrappedFunc25UnwrapRemoteValueToHandleERKNS0_11TVMArgValueE'/>
<use f='tvm/src/runtime/rpc/rpc_module.cc' l='290' c='_ZNK3tvm7runtime14RPCWrappedFunc23WrapRemoteReturnToValueENS0_7TVMArgsEPNS0_11TVMRetValueE'/>
<use f='tvm/src/runtime/rpc/rpc_module.cc' l='304' c='_ZN3tvm7runtime22CreateRPCSessionModuleESt10shared_ptrINS0_10RPCSessionEE'/>
<use f='tvm/src/runtime/rpc/rpc_module.cc' l='307' c='_ZN3tvm7runtime22CreateRPCSessionModuleESt10shared_ptrINS0_10RPCSessionEE'/>
<use f='tvm/src/runtime/rpc/rpc_module.cc' l='310' c='_ZN3tvm7runtime19RPCModuleGetSessionENS0_6ModuleE'/>
<use f='tvm/src/runtime/rpc/rpc_module.cc' l='368'/>
<use f='tvm/src/runtime/rpc/rpc_module.cc' l='376'/>
<use f='tvm/src/runtime/rpc/rpc_module.cc' l='418'/>
<use f='tvm/src/runtime/rpc/rpc_module.cc' l='418'/>
<use f='tvm/src/runtime/rpc/rpc_module.cc' l='423'/>
<use f='tvm/src/runtime/rpc/rpc_module.cc' l='428'/>
<use f='tvm/src/runtime/rpc/rpc_module.cc' l='434'/>
<use f='tvm/src/runtime/rpc/rpc_module.cc' l='434'/>
<use f='tvm/src/runtime/rpc/rpc_module.cc' l='441'/>
<use f='tvm/src/runtime/rpc/rpc_module.cc' l='448'/>
<size>8</size>
<use f='tvm/src/runtime/rpc/rpc_pipe_impl.cc' l='78' c='_ZN3tvm7runtime16CreatePipeClientESt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS7_EE'/>
<size>8</size>
<use f='tvm/src/runtime/rpc/rpc_socket_impl.cc' l='110' c='_ZN3tvm7runtime16RPCClientConnectENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEiS6_bNS0_7TVMArgsE'/>
<size>8</size>
<use f='tvm/src/runtime/stackvm/stackvm_module.h' l='43' c='_ZN3tvm7runtime19StackVMModuleCreateESt13unordered_mapINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS0_7StackVMESt4hashIS7_ESt8equal_toIS7_ESa5575980'/>
<use f='tvm/src/runtime/stackvm/stackvm_module.cc' l='73' c='_ZN3tvm7runtime17StackVMModuleNode10SaveToFileERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES9_'/>
<use f='tvm/src/runtime/stackvm/stackvm_module.cc' l='82' c='_ZN3tvm7runtime17StackVMModuleNode6CreateESt13unordered_mapINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS0_7StackVMESt4hashIS8_ESt8equal_toIS13003020'/>
<use f='tvm/src/runtime/stackvm/stackvm_module.cc' l='86' c='_ZN3tvm7runtime17StackVMModuleNode6CreateESt13unordered_mapINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS0_7StackVMESt4hashIS8_ESt8equal_toIS13003020'/>
<use f='tvm/src/runtime/stackvm/stackvm_module.cc' l='89' c='_ZN3tvm7runtime17StackVMModuleNode4LoadEPN4dmlc6StreamE'/>
<use f='tvm/src/runtime/stackvm/stackvm_module.cc' l='120' c='_ZN3tvm7runtime17StackVMModuleNode4LoadEPN4dmlc6StreamE'/>
<use f='tvm/src/runtime/stackvm/stackvm_module.cc' l='123' c='_ZN3tvm7runtime17StackVMModuleNode4LoadEPN4dmlc6StreamE'/>
<use f='tvm/src/runtime/stackvm/stackvm_module.cc' l='126' c='_ZN3tvm7runtime17StackVMModuleNode12LoadFromFileENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES7_'/>
<use f='tvm/src/runtime/stackvm/stackvm_module.cc' l='140' c='_ZN3tvm7runtime19StackVMModuleCreateESt13unordered_mapINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS0_7StackVMESt4hashIS7_ESt8equal_toIS7_ESa5575980'/>
<size>8</size>
<use f='tvm/src/runtime/static_library.h' l='45' c='_ZN3tvm7runtime17LoadStaticLibraryERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS0_5ArrayINS0_6StringEvEE'/>
<use f='tvm/src/runtime/static_library.cc' l='95' c='_ZN3tvm7runtime17LoadStaticLibraryERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS0_5ArrayINS0_6StringEvEE'/>
<use f='tvm/src/runtime/static_library.cc' l='100' c='_ZN3tvm7runtime17LoadStaticLibraryERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS0_5ArrayINS0_6StringEvEE'/>
<size>8</size>
<use f='tvm/src/runtime/vm/executable.cc' l='91' c='_ZN3tvm7runtime2vm10Executable11GetFunctionERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKNS0_9ObjectPtrINS0_6ObjectEEE'/>
<use f='tvm/src/runtime/vm/executable.cc' l='729' c='_ZNK3tvm7runtime2vm10Executable6GetLibEv'/>
<use f='tvm/src/runtime/vm/executable.cc' l='734' c='_ZNK3tvm7runtime2vm10Executable6GetLibEv'/>
<use f='tvm/src/runtime/vm/executable.cc' l='740' c='_ZN3tvm7runtime2vm10Executable6SetLibERKNS0_6ModuleE'/>
<use f='tvm/src/runtime/vm/executable.cc' l='751' c='_ZN3tvm7runtime2vm10Executable4LoadERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS0_6ModuleE'/>
<use f='tvm/src/runtime/vm/executable.cc' l='751' c='_ZN3tvm7runtime2vm10Executable4LoadERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS0_6ModuleE'/>
<use f='tvm/src/runtime/vm/executable.cc' l='781' c='_ZN3tvm7runtime2vm10Executable4LoadERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS0_6ModuleE'/>
<use f='tvm/src/runtime/vm/executable.cc' l='1059' c='_ZN3tvm7runtime2vm20ExecutableLoadBinaryEPv'/>
<use f='tvm/src/runtime/vm/executable.cc' l='1063' c='_ZN3tvm7runtime2vm20ExecutableLoadBinaryEPv'/>
<use f='tvm/src/runtime/vm/executable.cc' l='1078' c='_ZN3tvm7runtime2vm18ExecutableLoadFileERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES9_'/>
<use f='tvm/src/runtime/vm/executable.cc' l='1090'/>
<use f='tvm/src/runtime/vm/executable.cc' l='1097'/>
<use f='tvm/src/runtime/vm/executable.cc' l='1112'/>
<use f='tvm/src/runtime/vm/executable.cc' l='1119'/>
<use f='tvm/src/runtime/vm/executable.cc' l='1135'/>
<size>8</size>
<use f='tvm/src/runtime/vm/profiler/vm.cc' l='204' c='_ZN3tvm7runtime2vm25CreateVirtualMachineDebugEPNS1_10ExecutableE'/>
<use f='tvm/src/runtime/vm/profiler/vm.cc' l='207' c='_ZN3tvm7runtime2vm25CreateVirtualMachineDebugEPNS1_10ExecutableE'/>
<use f='tvm/src/runtime/vm/profiler/vm.cc' l='211'/>
<size>8</size>
<use f='tvm/src/runtime/vm/vm.cc' l='502' c='_ZN3tvm7runtime2vm14VirtualMachine14LoadExecutableERKNS0_9ObjectPtrINS1_10ExecutableEEE'/>
<use f='tvm/src/runtime/vm/vm.cc' l='993' c='_ZN3tvm7runtime2vm20CreateVirtualMachineEPNS1_10ExecutableE'/>
<use f='tvm/src/runtime/vm/vm.cc' l='996' c='_ZN3tvm7runtime2vm20CreateVirtualMachineEPNS1_10ExecutableE'/>
<use f='tvm/src/runtime/vm/vm.cc' l='1000'/>
<size>8</size>
<use f='tvm/src/support/ffi_testing.cc' l='156' c='_ZN3tvm21NewFrontendTestModuleEv'/>
<use f='tvm/src/support/ffi_testing.cc' l='158' c='_ZN3tvm21NewFrontendTestModuleEv'/>
<size>8</size>
<use f='tvm/src/target/codegen.cc' l='43' c='_ZN3tvm7codegen5BuildENS_8IRModuleENS_6TargetE'/>
<use f='tvm/src/target/codegen.cc' l='65' c='_ZN3tvm7codegen16ModuleSerializerC1ENS_7runtime6ModuleE'/>
<use f='tvm/src/target/codegen.cc' l='126' c='_ZN3tvm7codegen16ModuleSerializer17CreateModuleIndexEv'/>
<use f='tvm/src/target/codegen.cc' l='194' c='_ZN3tvm7codegen16ModuleSerializer16CreateImportTreeEv'/>
<use f='tvm/src/target/codegen.cc' l='222'/>
<use f='tvm/src/target/codegen.cc' l='232' c='_ZN3tvm7codegen12_GLOBAL__N_115SerializeModuleB5cxx11ERKNS_7runtime6ModuleE'/>
<use f='tvm/src/target/codegen.cc' l='244' c='_ZN3tvm7codegen14PackImportsToCB5cxx11ERKNS_7runtime6ModuleEb'/>
<use f='tvm/src/target/codegen.cc' l='293' c='_ZN3tvm7codegen17PackImportsToLLVMERKNS_7runtime6ModuleEbRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE'/>
<use f='tvm/src/target/codegen.cc' l='293' c='_ZN3tvm7codegen17PackImportsToLLVMERKNS_7runtime6ModuleEbRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE'/>
<size>8</size>
<use f='tvm/src/runtime/rocm/rocm_module.h' l='50' c='_ZN3tvm7runtime16ROCMModuleCreateENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES6_St13unordered_mapIS6_NS0_12FunctionInfoESt4hashIS6_ESt8equal_16434516'/>
<use f='tvm/src/target/llvm/codegen_amdgpu.cc' l='248' c='_ZN3tvm7codegen11BuildAMDGPUENS_8IRModuleENS_6TargetE'/>
<size>8</size>
<use f='tvm/src/runtime/hexagon/hexagon_module.h' l='47' c='_ZN3tvm7runtime19HexagonModuleCreateENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES6_St13unordered_mapIS6_NS0_12FunctionInfoESt4hashIS6_ESt8equ7579053'/>
<use f='tvm/src/target/llvm/codegen_hexagon.cc' l='479' c='_ZN3tvm7codegen12BuildHexagonENS_8IRModuleENS_6TargetE'/>
<size>8</size>
<use f='tvm/src/runtime/cuda/cuda_module.h' l='50' c='_ZN3tvm7runtime16CUDAModuleCreateENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES6_St13unordered_mapIS6_NS0_12FunctionInfoESt4hashIS6_ESt8equal_12001223'/>
<use f='tvm/src/target/llvm/codegen_nvptx.cc' l='301' c='_ZN3tvm7codegen10BuildNVPTXENS_8IRModuleENS_6TargetE'/>
<size>8</size>
<use f='tvm/src/target/llvm/llvm_module.h' l='39' c='_ZN3tvm7codegen27CreateLLVMCppMetadataModuleENS_7runtime8metadata8MetadataENS_6TargetENS_5relay7RuntimeE'/>
<use f='tvm/src/target/llvm/llvm_module.h' l='42' c='_ZN3tvm7codegen27CreateLLVMCrtMetadataModuleERKNS_7runtime5ArrayINS1_6ModuleEvEENS_6TargetENS_5relay7RuntimeE'/>
<use f='tvm/src/target/llvm/llvm_module.h' l='42' c='_ZN3tvm7codegen27CreateLLVMCrtMetadataModuleERKNS_7runtime5ArrayINS1_6ModuleEvEENS_6TargetENS_5relay7RuntimeE'/>
<use f='tvm/src/target/llvm/llvm_module.cc' l='424'/>
<use f='tvm/src/target/llvm/llvm_module.cc' l='427'/>
<use f='tvm/src/target/llvm/llvm_module.cc' l='431'/>
<use f='tvm/src/target/llvm/llvm_module.cc' l='441'/>
<use f='tvm/src/target/llvm/llvm_module.cc' l='469'/>
<use f='tvm/src/target/llvm/llvm_module.cc' l='472'/>
<use f='tvm/src/target/llvm/llvm_module.cc' l='485'/>
<use f='tvm/src/target/llvm/llvm_module.cc' l='491'/>
<use f='tvm/src/target/llvm/llvm_module.cc' l='494' c='_ZN3tvm7codegen27CreateLLVMCppMetadataModuleENS_7runtime8metadata8MetadataENS_6TargetENS_5relay7RuntimeE'/>
<use f='tvm/src/target/llvm/llvm_module.cc' l='523' c='_ZN3tvm7codegen27CreateLLVMCppMetadataModuleENS_7runtime8metadata8MetadataENS_6TargetENS_5relay7RuntimeE'/>
<use f='tvm/src/target/llvm/llvm_module.cc' l='527' c='_ZN3tvm7codegen27CreateLLVMCrtMetadataModuleERKNS_7runtime5ArrayINS1_6ModuleEvEENS_6TargetENS_5relay7RuntimeE'/>
<use f='tvm/src/target/llvm/llvm_module.cc' l='527' c='_ZN3tvm7codegen27CreateLLVMCrtMetadataModuleERKNS_7runtime5ArrayINS1_6ModuleEvEENS_6TargetENS_5relay7RuntimeE'/>
<use f='tvm/src/target/llvm/llvm_module.cc' l='530' c='_ZN3tvm7codegen27CreateLLVMCrtMetadataModuleERKNS_7runtime5ArrayINS1_6ModuleEvEENS_6TargetENS_5relay7RuntimeE'/>
<use f='tvm/src/target/llvm/llvm_module.cc' l='570' c='_ZN3tvm7codegen27CreateLLVMCrtMetadataModuleERKNS_7runtime5ArrayINS1_6ModuleEvEENS_6TargetENS_5relay7RuntimeE'/>
<size>8</size>
<use f='tvm/src/runtime/const_loader_module.h' l='46' c='_ZN3tvm7runtime23ConstLoaderModuleCreateERKSt13unordered_mapINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS0_7NDArrayESt4hashIS7_ESt8equal_toI7376922'/>
<use f='tvm/src/target/source/source_module.h' l='49' c='_ZN3tvm7codegen30CreateCSourceCrtMetadataModuleERKNS_7runtime5ArrayINS1_6ModuleEvEENS_6TargetENS_5relay7RuntimeENS8_7backend23ExecutorCodegenMetadataE13615150'/>
<use f='tvm/src/target/source/source_module.h' l='49' c='_ZN3tvm7codegen30CreateCSourceCrtMetadataModuleERKNS_7runtime5ArrayINS1_6ModuleEvEENS_6TargetENS_5relay7RuntimeENS8_7backend23ExecutorCodegenMetadataE13615150'/>
<use f='tvm/src/target/source/source_module.h' l='58' c='_ZN3tvm7codegen30CreateCSourceCppMetadataModuleENS_7runtime8metadata8MetadataE'/>
<use f='tvm/src/target/metadata_module.cc' l='42' c='_ZN3tvm7codegenL23CreateCrtMetadataModuleENS_7runtime6ModuleENS_6TargetENS_5relay7RuntimeENS4_8ExecutorENS4_7backend23ExecutorCodegenMetadataENS1_5Arr9893529'/>
<use f='tvm/src/target/metadata_module.cc' l='43' c='_ZN3tvm7codegenL23CreateCrtMetadataModuleENS_7runtime6ModuleENS_6TargetENS_5relay7RuntimeENS4_8ExecutorENS4_7backend23ExecutorCodegenMetadataENS1_5Arr9893529'/>
<use f='tvm/src/target/metadata_module.cc' l='45' c='_ZN3tvm7codegenL23CreateCrtMetadataModuleENS_7runtime6ModuleENS_6TargetENS_5relay7RuntimeENS4_8ExecutorENS4_7backend23ExecutorCodegenMetadataENS1_5Arr9893529'/>
<use f='tvm/src/target/metadata_module.cc' l='46' c='_ZN3tvm7codegenL23CreateCrtMetadataModuleENS_7runtime6ModuleENS_6TargetENS_5relay7RuntimeENS4_8ExecutorENS4_7backend23ExecutorCodegenMetadataENS1_5Arr9893529'/>
<use f='tvm/src/target/metadata_module.cc' l='143' c='_ZN3tvm7codegenL23CreateCppMetadataModuleENS_7runtime6ModuleENS_6TargetENS_5relay7RuntimeENS4_7backend23ExecutorCodegenMetadataERKSt13unordered_mapINS7644820'/>
<use f='tvm/src/target/metadata_module.cc' l='144' c='_ZN3tvm7codegenL23CreateCppMetadataModuleENS_7runtime6ModuleENS_6TargetENS_5relay7RuntimeENS4_7backend23ExecutorCodegenMetadataERKSt13unordered_mapINS7644820'/>
<use f='tvm/src/target/metadata_module.cc' l='147' c='_ZN3tvm7codegenL23CreateCppMetadataModuleENS_7runtime6ModuleENS_6TargetENS_5relay7RuntimeENS4_7backend23ExecutorCodegenMetadataERKSt13unordered_mapINS7644820'/>
<use f='tvm/src/target/metadata_module.cc' l='148' c='_ZN3tvm7codegenL23CreateCppMetadataModuleENS_7runtime6ModuleENS_6TargetENS_5relay7RuntimeENS4_7backend23ExecutorCodegenMetadataERKSt13unordered_mapINS7644820'/>
<use f='tvm/src/target/metadata_module.cc' l='151' c='_ZN3tvm7codegenL23CreateCppMetadataModuleENS_7runtime6ModuleENS_6TargetENS_5relay7RuntimeENS4_7backend23ExecutorCodegenMetadataERKSt13unordered_mapINS7644820'/>
<use f='tvm/src/target/metadata_module.cc' l='194' c='_ZN3tvm7codegen20CreateMetadataModuleERKSt13unordered_mapINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_7runtime7NDArrayESt4hashIS7_ESt8equal6263688'/>
<use f='tvm/src/target/metadata_module.cc' l='196' c='_ZN3tvm7codegen20CreateMetadataModuleERKSt13unordered_mapINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_7runtime7NDArrayESt4hashIS7_ESt8equal6263688'/>
<use f='tvm/src/target/metadata_module.cc' l='196' c='_ZN3tvm7codegen20CreateMetadataModuleERKSt13unordered_mapINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_7runtime7NDArrayESt4hashIS7_ESt8equal6263688'/>
<use f='tvm/src/target/metadata_module.cc' l='203' c='_ZN3tvm7codegen20CreateMetadataModuleERKSt13unordered_mapINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_7runtime7NDArrayESt4hashIS7_ESt8equal6263688'/>
<use f='tvm/src/target/metadata_module.cc' l='204' c='_ZN3tvm7codegen20CreateMetadataModuleERKSt13unordered_mapINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_7runtime7NDArrayESt4hashIS7_ESt8equal6263688'/>
<use f='tvm/src/target/metadata_module.cc' l='210' c='_ZN3tvm7codegen20CreateMetadataModuleERKSt13unordered_mapINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_7runtime7NDArrayESt4hashIS7_ESt8equal6263688'/>
<size>8</size>
<use f='tvm/src/runtime/opencl/opencl_module.h' l='45' c='_ZN3tvm7runtime18OpenCLModuleCreateENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES6_St13unordered_mapIS6_NS0_12FunctionInfoESt4hashIS6_ESt8equa16518601'/>
<use f='tvm/src/target/opt/build_aocl_off.cc' l='29' c='_ZN3tvm7runtime16AOCLModuleCreateENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES6_St13unordered_mapIS6_NS0_12FunctionInfoESt4hashIS6_ESt8equal_6085770'/>
<size>8</size>
<use f='tvm/src/target/opt/build_cuda_off.cc' l='27' c='_ZN3tvm7runtime16CUDAModuleCreateENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES6_St13unordered_mapIS6_NS0_12FunctionInfoESt4hashIS6_ESt8equal_12001223'/>
<use f='tvm/src/target/opt/build_cuda_off.cc' l='31' c='_ZN3tvm7runtime16CUDAModuleCreateENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES6_St13unordered_mapIS6_NS0_12FunctionInfoESt4hashIS6_ESt8equal_12001223'/>
<size>8</size>
<use f='tvm/src/target/opt/build_hexagon_off.cc' l='25' c='_ZN3tvm7runtime19HexagonModuleCreateENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES6_St13unordered_mapIS6_NS0_12FunctionInfoESt4hashIS6_ESt8equ7579053'/>
<size>8</size>
<use f='tvm/src/runtime/metal/metal_module.h' l='49' c='_ZN3tvm7runtime17MetalModuleCreateENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES6_St13unordered_mapIS6_NS0_12FunctionInfoESt4hashIS6_ESt8equal13134753'/>
<use f='tvm/src/target/opt/build_metal_off.cc' l='29' c='_ZN3tvm7runtime17MetalModuleCreateENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES6_St13unordered_mapIS6_NS0_12FunctionInfoESt4hashIS6_ESt8equal13134753'/>
<size>8</size>
<use f='tvm/src/target/opt/build_opencl_off.cc' l='29' c='_ZN3tvm7runtime18OpenCLModuleCreateENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES6_St13unordered_mapIS6_NS0_12FunctionInfoESt4hashIS6_ESt8equa16518601'/>
<size>8</size>
<use f='tvm/src/target/opt/build_rocm_off.cc' l='29' c='_ZN3tvm7runtime16ROCMModuleCreateENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES6_St13unordered_mapIS6_NS0_12FunctionInfoESt4hashIS6_ESt8equal_16434516'/>
<size>8</size>
<use f='tvm/src/target/opt/build_sdaccel_off.cc' l='29' c='_ZN3tvm7runtime19SDAccelModuleCreateENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES6_St13unordered_mapIS6_NS0_12FunctionInfoESt4hashIS6_ESt8equ2439372'/>
<size>8</size>
<use f='tvm/src/runtime/opencl/aocl/aocl_module.h' l='45' c='_ZN3tvm7runtime16AOCLModuleCreateENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES6_St13unordered_mapIS6_NS0_12FunctionInfoESt4hashIS6_ESt8equal_6085770'/>
<use f='tvm/src/target/source/codegen_aocl.cc' l='36' c='_ZN3tvm7codegen9BuildAOCLENS_8IRModuleENS_6TargetEb'/>
<use f='tvm/src/target/source/codegen_aocl.cc' l='83'/>
<use f='tvm/src/target/source/codegen_aocl.cc' l='88'/>
<size>8</size>
<use f='tvm/src/target/source/codegen_c_host.cc' l='390' c='_ZN3tvm7codegen10BuildCHostENS_8IRModuleENS_6TargetE'/>
<size>8</size>
<use f='tvm/src/target/source/codegen_metal.cc' l='335' c='_ZN3tvm7codegen10BuildMetalENS_8IRModuleENS_6TargetE'/>
<size>8</size>
<use f='tvm/src/target/source/codegen_opencl.cc' l='586' c='_ZN3tvm7codegen11BuildOpenCLENS_8IRModuleENS_6TargetE'/>
<size>8</size>
<use f='tvm/src/runtime/opencl/sdaccel/sdaccel_module.h' l='45' c='_ZN3tvm7runtime19SDAccelModuleCreateENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES6_St13unordered_mapIS6_NS0_12FunctionInfoESt4hashIS6_ESt8equ2439372'/>
<use f='tvm/src/target/source/codegen_vhls.cc' l='140' c='_ZN3tvm7codegen12BuildSDAccelENS_8IRModuleENS_6TargetE'/>
<size>8</size>
<use f='tvm/src/target/source/interface_c.cc' l='282' c='_ZN3tvm7codegen16InterfaceCCreateENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_7runtime5ArrayINS7_6StringEvEESA_NS8_INS_3tir4usmp17Allocated16469513'/>
<use f='tvm/src/target/source/interface_c.cc' l='288' c='_ZN3tvm7codegen16InterfaceCCreateENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_7runtime5ArrayINS7_6StringEvEESA_NS8_INS_3tir4usmp17Allocated16469513'/>
<size>8</size>
<use f='tvm/src/target/source/source_module.cc' l='85' c='_ZN3tvm7codegen18SourceModuleCreateENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES6_'/>
<use f='tvm/src/target/source/source_module.cc' l='87' c='_ZN3tvm7codegen18SourceModuleCreateENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES6_'/>
<use f='tvm/src/target/source/source_module.cc' l='145' c='_ZN3tvm7codegen19CSourceModuleCreateERKNS_7runtime6StringES4_RKNS1_5ArrayIS2_vEES8_'/>
<use f='tvm/src/target/source/source_module.cc' l='150' c='_ZN3tvm7codegen19CSourceModuleCreateERKNS_7runtime6StringES4_RKNS1_5ArrayIS2_vEES8_'/>
<use f='tvm/src/target/source/source_module.cc' l='890' c='_ZN3tvm7codegen12_GLOBAL__N_123CreateAotMetadataModuleENS_7runtime8metadata8MetadataEb'/>
<use f='tvm/src/target/source/source_module.cc' l='927' c='_ZN3tvm7codegen30CreateCSourceCrtMetadataModuleERKNS_7runtime5ArrayINS1_6ModuleEvEENS_6TargetENS_5relay7RuntimeENS8_7backend23ExecutorCodegenMetadataE13615150'/>
<use f='tvm/src/target/source/source_module.cc' l='927' c='_ZN3tvm7codegen30CreateCSourceCrtMetadataModuleERKNS_7runtime5ArrayINS1_6ModuleEvEENS_6TargetENS_5relay7RuntimeENS8_7backend23ExecutorCodegenMetadataE13615150'/>
<use f='tvm/src/target/source/source_module.cc' l='931' c='_ZN3tvm7codegen30CreateCSourceCrtMetadataModuleERKNS_7runtime5ArrayINS1_6ModuleEvEENS_6TargetENS_5relay7RuntimeENS8_7backend23ExecutorCodegenMetadataE13615150'/>
<use f='tvm/src/target/source/source_module.cc' l='937' c='_ZN3tvm7codegen30CreateCSourceCrtMetadataModuleERKNS_7runtime5ArrayINS1_6ModuleEvEENS_6TargetENS_5relay7RuntimeENS8_7backend23ExecutorCodegenMetadataE13615150'/>
<use f='tvm/src/target/source/source_module.cc' l='948' c='_ZN3tvm7codegen30CreateCSourceCrtMetadataModuleERKNS_7runtime5ArrayINS1_6ModuleEvEENS_6TargetENS_5relay7RuntimeENS8_7backend23ExecutorCodegenMetadataE13615150'/>
<use f='tvm/src/target/source/source_module.cc' l='956' c='_ZN3tvm7codegen30CreateCSourceCppMetadataModuleENS_7runtime8metadata8MetadataE'/>
<use f='tvm/src/target/source/source_module.cc' l='1025' c='_ZN3tvm7codegen24DeviceSourceModuleCreateENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES6_St13unordered_mapIS6_NS_7runtime12FunctionInfoESt4has3715380'/>
<use f='tvm/src/target/source/source_module.cc' l='1029' c='_ZN3tvm7codegen24DeviceSourceModuleCreateENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES6_St13unordered_mapIS6_NS_7runtime12FunctionInfoESt4has3715380'/>
<use f='tvm/src/target/source/source_module.cc' l='1041'/>
<size>8</size>
<use f='tvm/src/target/stackvm/codegen_stackvm.cc' l='532' c='_ZN3tvm7codegen12BuildStackVMENS_8IRModuleENS_6TargetE'/>
<size>8</size>
