<def f='tvm/src/meta_schedule/feature_extractor/per_store_feature.cc' l='1114' ll='1143'/>
<use f='tvm/src/meta_schedule/feature_extractor/per_store_feature.cc' l='1240'/>
<use f='tvm/src/meta_schedule/feature_extractor/per_store_feature.cc' l='1272' c='_ZN3tvm3tir24PerStoreFeatureCollector7CollectEbllRKNS_8IRModuleE'/>
<use f='tvm/src/meta_schedule/feature_extractor/per_store_feature.cc' l='1318' c='_ZN3tvm3tir24PerStoreFeatureCollector17HandleBufferAllocERKNS0_6BufferE'/>
<size>24</size>
<doc f='tvm/src/meta_schedule/feature_extractor/per_store_feature.cc' l='1113'>/*! \brief Group 4 feature */</doc>
