<def f='tvm/src/meta_schedule/feature_extractor/per_store_feature.cc' l='1234' ll='1245'/>
<use f='tvm/src/meta_schedule/feature_extractor/per_store_feature.cc' l='1244' c='_ZNK3tvm3tir7FeatureltERKS1_'/>
<use f='tvm/src/meta_schedule/feature_extractor/per_store_feature.cc' l='1250' c='_ZN3tvm3tir24PerStoreFeatureCollector7CollectEbllRKNS_8IRModuleE'/>
<use f='tvm/src/meta_schedule/feature_extractor/per_store_feature.cc' l='1262' c='_ZN3tvm3tir24PerStoreFeatureCollector7CollectEbllRKNS_8IRModuleE'/>
<use f='tvm/src/meta_schedule/feature_extractor/per_store_feature.cc' l='1265' c='_ZN3tvm3tir24PerStoreFeatureCollector7CollectEbllRKNS_8IRModuleE'/>
<use f='tvm/src/meta_schedule/feature_extractor/per_store_feature.cc' l='1294' c='_ZN3tvm3tir24PerStoreFeatureCollector10VisitStmt_EPKNS0_15BufferStoreNodeE'/>
<use f='tvm/src/meta_schedule/feature_extractor/per_store_feature.cc' l='1317' c='_ZN3tvm3tir24PerStoreFeatureCollector17HandleBufferAllocERKNS0_6BufferE'/>
<use f='tvm/src/meta_schedule/feature_extractor/per_store_feature.cc' l='1334'/>
<use f='tvm/src/meta_schedule/feature_extractor/per_store_feature.cc' l='1361' c='_ZN3tvm13meta_schedule19PerStoreFeatureNode13ExtractSingleENS_8IRModuleEbPSt6vectorIS3_IdSaIdEESaIS5_EE'/>
<use f='tvm/src/meta_schedule/feature_extractor/per_store_feature.cc' l='1366' c='_ZN3tvm13meta_schedule19PerStoreFeatureNode13ExtractSingleENS_8IRModuleEbPSt6vectorIS3_IdSaIdEESaIS5_EE'/>
<size>72</size>
<doc f='tvm/src/meta_schedule/feature_extractor/per_store_feature.cc' l='1233'>/*! \brief The feature extracted */</doc>
