<def f='tvm/src/meta_schedule/feature_extractor/per_store_feature.cc' l='1150' ll='1171'/>
<use f='tvm/src/meta_schedule/feature_extractor/per_store_feature.cc' l='1241'/>
<use f='tvm/src/meta_schedule/feature_extractor/per_store_feature.cc' l='1306' c='_ZN3tvm3tir24PerStoreFeatureCollector10VisitStmt_EPKNS0_15BufferStoreNodeE'/>
<size>16</size>
<doc f='tvm/src/meta_schedule/feature_extractor/per_store_feature.cc' l='1149'>/*! \brief Group 5 feature */</doc>
