<dec f='tvm/include/tvm/script/printer/doc.h' l='997' type='Optional&lt;tvm::script::printer::ExprDoc&gt;'/>
<use f='tvm/include/tvm/script/printer/doc.h' l='1002' u='a' c='_ZN3tvm6script7printer13AssertDocNode10VisitAttrsEPNS_11AttrVisitorE'/>
<offset>448</offset>
<doc f='tvm/include/tvm/script/printer/doc.h' l='996'>/*! \brief The optional error message when assertion failed. */</doc>
<use f='tvm/src/script/printer/doc.cc' l='190' u='w' c='_ZN3tvm6script7printer9AssertDocC1ENS1_7ExprDocENS_7runtime8OptionalIS3_EE'/>
<use f='tvm/src/script/printer/python_doc_printer.cc' l='570' u='m' c='_ZN3tvm6script7printer16PythonDocPrinter13PrintTypedDocERKNS1_9AssertDocE'/>
<use f='tvm/src/script/printer/python_doc_printer.cc' l='572' u='m' c='_ZN3tvm6script7printer16PythonDocPrinter13PrintTypedDocERKNS1_9AssertDocE'/>
