<inh f='tvm/include/tvm/runtime/object.h' l='511' c='tvm::runtime::ObjectRef'/>
<def f='tvm/include/tvm/meta_schedule/builder.h' l='131' ll='140'/>
<use f='tvm/include/tvm/meta_schedule/builder.h' l='138' c='_ZN3tvm13meta_schedule7Builder9PyBuilderENS_7runtime15TypedPackedFuncIFNS2_5ArrayINS0_13BuilderResultEvEERKNS4_INS0_12BuilderInputEvEEEEE'/>
<use f='tvm/include/tvm/meta_schedule/builder.h' l='139' c='_ZN3tvm13meta_schedule7BuilderC1ERKS1_'/>
<use f='tvm/include/tvm/meta_schedule/builder.h' l='139' c='_ZN3tvm13meta_schedule7BuilderC1EOS1_'/>
<use f='tvm/include/tvm/meta_schedule/builder.h' l='139' c='_ZN3tvm13meta_schedule7BuilderaSERKS1_'/>
<use f='tvm/include/tvm/meta_schedule/builder.h' l='139' c='_ZN3tvm13meta_schedule7BuilderaSERKS1_'/>
<use f='tvm/include/tvm/meta_schedule/builder.h' l='139' c='_ZN3tvm13meta_schedule7BuilderaSEOS1_'/>
<use f='tvm/include/tvm/meta_schedule/builder.h' l='139' c='_ZN3tvm13meta_schedule7BuilderaSEOS1_'/>
<use f='tvm/include/tvm/meta_schedule/tune_context.h' l='108' c='_ZN3tvm13meta_schedule15TuneContextNode14_SendToBuilderERKNS0_7BuilderE'/>
<use f='tvm/include/tvm/meta_schedule/task_scheduler.h' l='79'/>
<use f='tvm/include/tvm/meta_schedule/task_scheduler.h' l='219' c='_ZN3tvm13meta_schedule13TaskScheduler10RoundRobinENS_7runtime5ArrayINS0_11TuneContextEvEENS0_7BuilderENS0_6RunnerENS2_8OptionalINS0_8DatabaseEEENS8_IN927609'/>
<use f='tvm/include/tvm/meta_schedule/task_scheduler.h' l='244' c='_ZN3tvm13meta_schedule13TaskScheduler13GradientBasedENS_7runtime5ArrayINS0_11TuneContextEvEENS3_INS_8FloatImmEvEENS0_7BuilderENS0_6RunnerENS2_8Optiona15111662'/>
<use f='tvm/include/tvm/meta_schedule/task_scheduler.h' l='273' c='_ZN3tvm13meta_schedule13TaskScheduler15PyTaskSchedulerENS_7runtime5ArrayINS0_11TuneContextEvEENS0_7BuilderENS0_6RunnerENS2_8OptionalINS0_8DatabaseEEEN15662921'/>
<size>8</size>
<doc f='tvm/include/tvm/meta_schedule/builder.h' l='127'>/*!
 * \brief Managed reference to BuilderNode
 * \sa BuilderNode
 */</doc>
<fun r='_ZN3tvm13meta_schedule7Builder9PyBuilderENS_7runtime15TypedPackedFuncIFNS2_5ArrayINS0_13BuilderResultEvEERKNS4_INS0_12BuilderInputEvEEEEE'/>
<fun r='_ZN3tvm13meta_schedule7BuilderC1ENS_7runtime9ObjectPtrINS2_6ObjectEEE'/>
<fun r='_ZN3tvm13meta_schedule7BuilderC1ERKS1_'/>
<fun r='_ZN3tvm13meta_schedule7BuilderC1EOS1_'/>
<fun r='_ZNK3tvm13meta_schedule7Builder3getEv'/>
<smbr r='tvm::meta_schedule::Builder::_type_is_nullable' t='const bool'/>
<use f='tvm/src/meta_schedule/builder/builder.cc' l='42' c='_ZN3tvm13meta_schedule7Builder9PyBuilderENS_7runtime15TypedPackedFuncIFNS2_5ArrayINS0_13BuilderResultEvEERKNS4_INS0_12BuilderInputEvEEEEE'/>
<use f='tvm/src/meta_schedule/builder/builder.cc' l='45' c='_ZN3tvm13meta_schedule7Builder9PyBuilderENS_7runtime15TypedPackedFuncIFNS2_5ArrayINS0_13BuilderResultEvEERKNS4_INS0_12BuilderInputEvEEEEE'/>
<use f='tvm/src/meta_schedule/builder/builder.cc' l='67'/>
<size>8</size>
<fun r='_ZN3tvm13meta_schedule7Builder9PyBuilderENS_7runtime15TypedPackedFuncIFNS2_5ArrayINS0_13BuilderResultEvEERKNS4_INS0_12BuilderInputEvEEEEE'/>
<use f='tvm/src/meta_schedule/task_scheduler/gradient_based.cc' l='190' c='_ZN3tvm13meta_schedule13TaskScheduler13GradientBasedENS_7runtime5ArrayINS0_11TuneContextEvEENS3_INS_8FloatImmEvEENS0_7BuilderENS0_6RunnerENS2_8Optiona15111662'/>
<size>8</size>
<use f='tvm/src/meta_schedule/task_scheduler/round_robin.cc' l='59' c='_ZN3tvm13meta_schedule13TaskScheduler10RoundRobinENS_7runtime5ArrayINS0_11TuneContextEvEENS0_7BuilderENS0_6RunnerENS2_8OptionalINS0_8DatabaseEEENS8_IN927609'/>
<size>8</size>
<use f='tvm/src/meta_schedule/task_scheduler/task_scheduler.cc' l='161' c='_ZN3tvm13meta_schedule13TaskScheduler15PyTaskSchedulerENS_7runtime5ArrayINS0_11TuneContextEvEENS0_7BuilderENS0_6RunnerENS2_8OptionalINS0_8DatabaseEEEN15662921'/>
<size>8</size>
<use f='tvm/src/meta_schedule/tune_context.cc' l='77' c='_ZN3tvm13meta_schedule15TuneContextNode14_SendToBuilderERKNS0_7BuilderE'/>
<size>8</size>
