<def f='tvm/src/meta_schedule/feature_extractor/per_store_feature.cc' l='1041' ll='1118'/>
<use f='tvm/src/meta_schedule/feature_extractor/per_store_feature.cc' l='1250'/>
<use f='tvm/src/meta_schedule/feature_extractor/per_store_feature.cc' l='1315' c='_ZN3tvm3tir24PerStoreFeatureCollector10VisitStmt_EPKNS0_15BufferStoreNodeE'/>
<size>24</size>
<doc f='tvm/src/meta_schedule/feature_extractor/per_store_feature.cc' l='1040'>/*! \brief Group 3 feature */</doc>
