<inh f='tvm/include/tvm/ir/expr.h' l='112' c='tvm::PrimExpr'/>
<def f='tvm/include/tvm/tir/expr.h' l='234' ll='238'/>
<use f='tvm/include/tvm/tir/expr.h' l='237' c='_ZN3tvm3tir3ModC1ERKS1_'/>
<use f='tvm/include/tvm/tir/expr.h' l='237' c='_ZN3tvm3tir3ModC1EOS1_'/>
<use f='tvm/include/tvm/tir/expr.h' l='237' c='_ZN3tvm3tir3ModaSERKS1_'/>
<use f='tvm/include/tvm/tir/expr.h' l='237' c='_ZN3tvm3tir3ModaSERKS1_'/>
<use f='tvm/include/tvm/tir/expr.h' l='237' c='_ZN3tvm3tir3ModaSEOS1_'/>
<use f='tvm/include/tvm/tir/expr.h' l='237' c='_ZN3tvm3tir3ModaSEOS1_'/>
<size>8</size>
<doc f='tvm/include/tvm/tir/expr.h' l='230'>/*!
 * \brief Managed reference to ModNode
 * \sa ModNode
 */</doc>
<fun r='_ZN3tvm3tir3ModC1ENS_8PrimExprES2_NS_4SpanE'/>
<fun r='_ZN3tvm3tir3ModC1Ev'/>
<fun r='_ZN3tvm3tir3ModC1ENS_7runtime9ObjectPtrINS2_6ObjectEEE'/>
<fun r='_ZN3tvm3tir3ModC1ERKS1_'/>
<fun r='_ZN3tvm3tir3ModC1EOS1_'/>
<fun r='_ZNK3tvm3tir3Mod3getEv'/>
<use f='tvm/src/arith/const_fold.h' l='259' c='_ZN3tvm5arith12TryConstFoldENS_8PrimExprES1_'/>
<size>8</size>
<use f='tvm/src/arith/pattern_match.h' l='387' c='_ZN3tvm5arithrmERKNS0_7PatternIT_EERKNS1_IT0_EE'/>
<use f='tvm/src/arith/pattern_match.h' l='387' c='_ZN3tvm5arithrmERKNS0_7PatternIT_EERKNS1_IT0_EE'/>
<use f='tvm/src/arith/pattern_match.h' l='387' c='_ZN3tvm5arithrmERKNS0_7PatternIT_EEl'/>
<use f='tvm/src/arith/pattern_match.h' l='387' c='_ZN3tvm5arithrmElRKNS0_7PatternIT_EE'/>
<use f='tvm/src/arith/pattern_match.h' l='397' c='_ZN3tvm5arith8truncmodERKNS0_7PatternIT_EERKNS1_IT0_EE'/>
<use f='tvm/src/arith/pattern_match.h' l='397' c='_ZN3tvm5arith8truncmodERKNS0_7PatternIT_EERKNS1_IT0_EE'/>
<use f='tvm/src/arith/pattern_match.h' l='397' c='_ZN3tvm5arith8truncmodERKNS0_7PatternIT_EEl'/>
<use f='tvm/src/arith/pattern_match.h' l='397' c='_ZN3tvm5arith8truncmodElRKNS0_7PatternIT_EE'/>
<use f='tvm/src/arith/canonical_simplify.cc' l='1036' c='_ZN3tvm5arith19CanonicalSimplifier4Impl10VisitExpr_EPKNS_3tir7ModNodeE'/>
<use f='tvm/src/arith/canonical_simplify.cc' l='1090' c='_ZN3tvm5arith19CanonicalSimplifier4Impl10VisitExpr_EPKNS_3tir7ModNodeE'/>
<size>8</size>
<use f='tvm/src/arith/int_set.cc' l='228' c='_ZN3tvm5arith7CombineEPNS0_8AnalyzerENS0_11IntervalSetES3_NS_7runtime8DataTypeE'/>
<use f='tvm/src/arith/int_set.cc' l='435' c='_ZN3tvm5arith20IntervalSetEvaluator10VisitExpr_EPKNS_3tir7ModNodeE'/>
<size>8</size>
<use f='tvm/src/arith/rewrite_simplify.cc' l='700' c='_ZN3tvm5arith17RewriteSimplifier4Impl10VisitExpr_EPKNS_3tir7ModNodeE'/>
<size>8</size>
<use f='tvm/src/target/source/codegen_cuda.cc' l='872' c='_ZZN3tvm7codegen11CodeGenCUDA10VisitExpr_EPKNS_3tir8CallNodeERSoEN16LowerFloorDivMod10VisitExpr_EPKNS2_12FloorModNodeE'/>
<size>8</size>
<use f='tvm/src/te/autodiff/ad_simplify.cc' l='203' c='_ZN3tvm2te23NonzeroConditionFunctor10VisitExpr_EPKNS_3tir7ModNodeE'/>
<size>8</size>
<use f='tvm/src/tir/ir/expr.cc' l='318'/>
<size>8</size>
<fun r='_ZN3tvm3tir3ModC1ENS_8PrimExprES2_NS_4SpanE'/>
<use f='tvm/src/tir/ir/expr_functor.cc' l='196' c='_ZN3tvm3tir11ExprMutator10VisitExpr_EPKNS0_7ModNodeE'/>
<size>8</size>
<use f='tvm/src/tir/op/op.cc' l='376' c='_ZN3tvm8truncmodENS_8PrimExprES0_NS_4SpanE'/>
<use f='tvm/src/tir/op/op.cc' l='377' c='_ZN3tvm8truncmodENS_8PrimExprES0_NS_4SpanE'/>
<size>8</size>
<use f='tvm/src/tir/transforms/vectorize_loop.cc' l='209' c='_ZN3tvm3tir10Vectorizer10VisitExpr_EPKNS0_7ModNodeE'/>
<size>8</size>
