<dec f='tvm/include/tvm/runtime/vm/bytecode.h' l='51' type='0'/>
<use f='tvm/src/relay/backend/vm/compiler.cc' l='317' c='_ZN3tvm5relay2vm18VMFunctionCompiler4EmitERKNS_7runtime2vm11InstructionE'/>
<use f='tvm/src/runtime/vm/bytecode.cc' l='49' c='_ZN3tvm7runtime2vm11InstructionC1ERKS2_'/>
<use f='tvm/src/runtime/vm/bytecode.cc' l='149' c='_ZN3tvm7runtime2vm11InstructionaSERKS2_'/>
<use f='tvm/src/runtime/vm/bytecode.cc' l='244' c='_ZN3tvm7runtime2vm11InstructionD1Ev'/>
<use f='tvm/src/runtime/vm/bytecode.cc' l='495' u='r' c='_ZN3tvm7runtime2vm11Instruction4MoveEll'/>
<use f='tvm/src/runtime/vm/bytecode.cc' l='538' c='_ZN3tvm7runtime2vm16InstructionPrintERSoRKNS1_11InstructionE'/>
<use f='tvm/src/runtime/vm/executable.cc' l='537' c='_ZN3tvm7runtime2vm20SerializeInstructionERKNS1_11InstructionE'/>
<use f='tvm/src/runtime/vm/executable.cc' l='831' c='_ZN3tvm7runtime2vm22DeserializeInstructionERKNS1_23VMInstructionSerializerE'/>
<use f='tvm/src/runtime/vm/vm.cc' l='638' c='_ZN3tvm7runtime2vm14VirtualMachine7RunLoopERKSt6vectorIlSaIlEE'/>
