<dec f='tvm/include/tvm/script/ir_builder/tir/frame.h' l='133' type='Optional&lt;tvm::tir::Stmt&gt;'/>
<use f='tvm/include/tvm/script/ir_builder/tir/frame.h' l='156' u='a' c='_ZN3tvm6script10ir_builder3tir14BlockFrameNode10VisitAttrsEPNS_11AttrVisitorE'/>
<use f='tvm/src/script/ir_builder/tir/frame.cc' l='63' u='r' c='_ZN3tvm6script10ir_builder3tir14BlockFrameNode13ExitWithScopeEv'/>
<use f='tvm/src/script/ir_builder/tir/frame.cc' l='77' u='m' c='_ZN3tvm6script10ir_builder3tir18BlockInitFrameNode14EnterWithScopeEv'/>
<use f='tvm/src/script/ir_builder/tir/frame.cc' l='86' u='w' c='_ZN3tvm6script10ir_builder3tir18BlockInitFrameNode13ExitWithScopeEv'/>
<offset>704</offset>
<doc f='tvm/include/tvm/script/ir_builder/tir/frame.h' l='132'>/*! \brief The init statement of the bolck. */</doc>
<use f='tvm/src/script/ir_builder/tir/ir.cc' l='145' u='w' c='_ZN3tvm6script10ir_builder3tir5BlockENS_7runtime6StringEb'/>
