<dec f='tvm/src/relay/backend/vm/compiler.h' l='68' type='tvm::IRModule'/>
<use f='tvm/src/relay/backend/vm/compiler.cc' l='240' u='r' c='_ZN3tvm5relay2vm18VMFunctionCompilerC1EPNS1_17VMCompilerContextENS_13VirtualDeviceE'/>
<use f='tvm/src/relay/backend/vm/compiler.cc' l='435' u='m' c='_ZN3tvm5relay2vm18VMFunctionCompiler10VisitExpr_EPKNS_13GlobalVarNodeE'/>
<use f='tvm/src/relay/backend/vm/compiler.cc' l='682' u='m' c='_ZN3tvm5relay2vm18VMFunctionCompiler21DeviceAwareVisitExpr_EPKNS0_8CallNodeE'/>
<use f='tvm/src/relay/backend/vm/compiler.cc' l='913' u='w' c='_ZN3tvm5relay2vm10VMCompiler9LowerImplENS_8IRModuleE'/>
<use f='tvm/src/relay/backend/vm/compiler.cc' l='923' u='m' c='_ZN3tvm5relay2vm10VMCompiler9LowerImplENS_8IRModuleE'/>
<use f='tvm/src/relay/backend/vm/compiler.cc' l='983' u='r' c='_ZN3tvm5relay2vm10VMCompiler9LowerImplENS_8IRModuleE'/>
<use f='tvm/src/relay/backend/vm/compiler.cc' l='1142' u='m' c='_ZN3tvm5relay2vm10VMCompiler17PopulateGlobalMapEv'/>
<use f='tvm/src/relay/backend/vm/compiler.cc' l='1154' u='m' c='_ZN3tvm5relay2vm10VMCompiler7CodegenEv'/>
<use f='tvm/src/relay/backend/vm/compiler.cc' l='1165' u='r' c='_ZN3tvm5relay2vm10VMCompiler7CodegenEv'/>
<use f='tvm/src/relay/backend/vm/compiler.cc' l='1173' u='m' c='_ZN3tvm5relay2vm10VMCompiler7CodegenEv'/>
<use f='tvm/src/relay/backend/vm/compiler.cc' l='1177' u='m' c='_ZN3tvm5relay2vm10VMCompiler7CodegenEv'/>
<offset>0</offset>
<doc f='tvm/src/relay/backend/vm/compiler.h' l='67'>// The module context for the compilation</doc>
