<def f='tvm/src/meta_schedule/feature_extractor/per_store_feature.cc' l='1161' ll='1182'/>
<use f='tvm/src/meta_schedule/feature_extractor/per_store_feature.cc' l='1252'/>
<use f='tvm/src/meta_schedule/feature_extractor/per_store_feature.cc' l='1317' c='_ZN3tvm3tir24PerStoreFeatureCollector10VisitStmt_EPKNS0_15BufferStoreNodeE'/>
<size>16</size>
<doc f='tvm/src/meta_schedule/feature_extractor/per_store_feature.cc' l='1160'>/*! \brief Group 5 feature */</doc>
