<dec f='tvm/src/relay/backend/vm/compiler.h' l='68' type='tvm::IRModule'/>
<use f='tvm/src/relay/backend/vm/compiler.cc' l='240' u='r' c='_ZN3tvm5relay2vm18VMFunctionCompilerC1EPNS1_17VMCompilerContextENS_13VirtualDeviceE'/>
<use f='tvm/src/relay/backend/vm/compiler.cc' l='435' u='m' c='_ZN3tvm5relay2vm18VMFunctionCompiler10VisitExpr_EPKNS_13GlobalVarNodeE'/>
<use f='tvm/src/relay/backend/vm/compiler.cc' l='682' u='m' c='_ZN3tvm5relay2vm18VMFunctionCompiler21DeviceAwareVisitExpr_EPKNS0_8CallNodeE'/>
<use f='tvm/src/relay/backend/vm/compiler.cc' l='912' u='w' c='_ZN3tvm5relay2vm10VMCompiler9LowerImplENS_8IRModuleE'/>
<use f='tvm/src/relay/backend/vm/compiler.cc' l='922' u='m' c='_ZN3tvm5relay2vm10VMCompiler9LowerImplENS_8IRModuleE'/>
<use f='tvm/src/relay/backend/vm/compiler.cc' l='982' u='r' c='_ZN3tvm5relay2vm10VMCompiler9LowerImplENS_8IRModuleE'/>
<use f='tvm/src/relay/backend/vm/compiler.cc' l='1141' u='m' c='_ZN3tvm5relay2vm10VMCompiler17PopulateGlobalMapEv'/>
<use f='tvm/src/relay/backend/vm/compiler.cc' l='1153' u='m' c='_ZN3tvm5relay2vm10VMCompiler7CodegenEv'/>
<use f='tvm/src/relay/backend/vm/compiler.cc' l='1164' u='r' c='_ZN3tvm5relay2vm10VMCompiler7CodegenEv'/>
<use f='tvm/src/relay/backend/vm/compiler.cc' l='1172' u='m' c='_ZN3tvm5relay2vm10VMCompiler7CodegenEv'/>
<use f='tvm/src/relay/backend/vm/compiler.cc' l='1176' u='m' c='_ZN3tvm5relay2vm10VMCompiler7CodegenEv'/>
<offset>0</offset>
<doc f='tvm/src/relay/backend/vm/compiler.h' l='67'>// The module context for the compilation</doc>
