<def f='tvm/src/meta_schedule/feature_extractor/per_store_feature.cc' l='1218' ll='1229'/>
<use f='tvm/src/meta_schedule/feature_extractor/per_store_feature.cc' l='1242'/>
<use f='tvm/src/meta_schedule/feature_extractor/per_store_feature.cc' l='1382' c='_ZN3tvm13meta_schedule19PerStoreFeatureNode11ExtractFromERKNS0_11TuneContextERKNS_7runtime5ArrayINS0_16MeasureCandidateEvEE'/>
<use f='tvm/src/meta_schedule/feature_extractor/per_store_feature.cc' l='1384' c='_ZN3tvm13meta_schedule19PerStoreFeatureNode11ExtractFromERKNS0_11TuneContextERKNS_7runtime5ArrayINS0_16MeasureCandidateEvEE'/>
<size>24</size>
<doc f='tvm/src/meta_schedule/feature_extractor/per_store_feature.cc' l='1217'>/*! \brief Group 6 feature */</doc>
