<dec f='tvm/include/tvm/script/ir_builder/tir/frame.h' l='136' type='Optional&lt;tvm::tir::Stmt&gt;'/>
<use f='tvm/include/tvm/script/ir_builder/tir/frame.h' l='159' u='a' c='_ZN3tvm6script10ir_builder3tir14BlockFrameNode10VisitAttrsEPNS_11AttrVisitorE'/>
<use f='tvm/src/script/ir_builder/tir/frame.cc' l='64' u='r' c='_ZN3tvm6script10ir_builder3tir14BlockFrameNode13ExitWithScopeEv'/>
<offset>704</offset>
<doc f='tvm/include/tvm/script/ir_builder/tir/frame.h' l='135'>/*! \brief The init statement of the bolck. */</doc>
<use f='tvm/src/script/ir_builder/tir/ir.cc' l='166' u='w' c='_ZN3tvm6script10ir_builder3tir5BlockENS_7runtime6StringEb'/>
