<def f='tvm/src/meta_schedule/feature_extractor/per_store_feature.cc' l='1245' ll='1256'/>
<use f='tvm/src/meta_schedule/feature_extractor/per_store_feature.cc' l='1255' c='_ZNK3tvm3tir7FeatureltERKS1_'/>
<use f='tvm/src/meta_schedule/feature_extractor/per_store_feature.cc' l='1261' c='_ZN3tvm3tir24PerStoreFeatureCollector7CollectEbllRKNS_8IRModuleE'/>
<use f='tvm/src/meta_schedule/feature_extractor/per_store_feature.cc' l='1273' c='_ZN3tvm3tir24PerStoreFeatureCollector7CollectEbllRKNS_8IRModuleE'/>
<use f='tvm/src/meta_schedule/feature_extractor/per_store_feature.cc' l='1276' c='_ZN3tvm3tir24PerStoreFeatureCollector7CollectEbllRKNS_8IRModuleE'/>
<use f='tvm/src/meta_schedule/feature_extractor/per_store_feature.cc' l='1305' c='_ZN3tvm3tir24PerStoreFeatureCollector10VisitStmt_EPKNS0_15BufferStoreNodeE'/>
<use f='tvm/src/meta_schedule/feature_extractor/per_store_feature.cc' l='1328' c='_ZN3tvm3tir24PerStoreFeatureCollector17HandleBufferAllocERKNS0_6BufferE'/>
<use f='tvm/src/meta_schedule/feature_extractor/per_store_feature.cc' l='1345'/>
<use f='tvm/src/meta_schedule/feature_extractor/per_store_feature.cc' l='1372' c='_ZN3tvm13meta_schedule19PerStoreFeatureNode13ExtractSingleENS_8IRModuleEbPSt6vectorIS3_IdSaIdEESaIS5_EE'/>
<use f='tvm/src/meta_schedule/feature_extractor/per_store_feature.cc' l='1377' c='_ZN3tvm13meta_schedule19PerStoreFeatureNode13ExtractSingleENS_8IRModuleEbPSt6vectorIS3_IdSaIdEESaIS5_EE'/>
<size>72</size>
<doc f='tvm/src/meta_schedule/feature_extractor/per_store_feature.cc' l='1244'>/*! \brief The feature extracted */</doc>
