<dec f='tvm/include/tvm/relay/attrs/algorithm.h' l='56' type='Optional&lt;tvm::Integer&gt;'/>
<use f='tvm/include/tvm/relay/attrs/algorithm.h' l='63' u='a' c='_ZN3tvm5relay9TopKAttrs15_tvm_VisitAttrsERT_'/>
<offset>192</offset>
<use f='tvm/src/relay/op/algorithm/topk.cc' l='87' u='m' c='_ZN3tvm5relay7TopKRelERKNS_7runtime5ArrayINS_4TypeEvEEiRKNS_5AttrsERKNS_12TypeReporterE'/>
<use f='tvm/src/relay/op/algorithm/topk.cc' l='111' u='w' c='_ZN3tvm5relay8MakeTopKENS_9RelayExprEiiNS_7runtime6StringEbNS2_8DataTypeE'/>
