<inh f='tvm/include/tvm/ir/expr.h' l='112' c='tvm::PrimExpr'/>
<def f='tvm/include/tvm/tir/expr.h' l='357' ll='362'/>
<use f='tvm/include/tvm/tir/expr.h' l='360' c='_ZN3tvm3tir2EQC1ERKS1_'/>
<use f='tvm/include/tvm/tir/expr.h' l='360' c='_ZN3tvm3tir2EQC1EOS1_'/>
<use f='tvm/include/tvm/tir/expr.h' l='360' c='_ZN3tvm3tir2EQaSERKS1_'/>
<use f='tvm/include/tvm/tir/expr.h' l='360' c='_ZN3tvm3tir2EQaSERKS1_'/>
<use f='tvm/include/tvm/tir/expr.h' l='360' c='_ZN3tvm3tir2EQaSEOS1_'/>
<use f='tvm/include/tvm/tir/expr.h' l='360' c='_ZN3tvm3tir2EQaSEOS1_'/>
<size>8</size>
<doc f='tvm/include/tvm/tir/expr.h' l='353'>/*!
 * \brief Managed reference to EQNode
 * \sa EQNode
 */</doc>
<fun r='_ZN3tvm3tir2EQC1ENS_8PrimExprES2_NS_4SpanE'/>
<fun r='_ZN3tvm3tir2EQC1Ev'/>
<fun r='_ZN3tvm3tir2EQC1ENS_7runtime9ObjectPtrINS2_6ObjectEEE'/>
<fun r='_ZN3tvm3tir2EQC1ERKS1_'/>
<fun r='_ZN3tvm3tir2EQC1EOS1_'/>
<fun r='_ZNK3tvm3tir2EQ3getEv'/>
<fun r='_ZN3tvm3tir2EQ11CopyOnWriteEv'/>
<use f='tvm/src/arith/const_fold.h' l='393' c='_ZN3tvm5arith12TryConstFoldENS_8PrimExprES1_'/>
<size>8</size>
<use f='tvm/src/arith/pattern_match.h' l='406' c='_ZN3tvm5aritheqERKNS0_7PatternIT_EERKNS1_IT0_EE'/>
<use f='tvm/src/arith/pattern_match.h' l='406' c='_ZN3tvm5aritheqERKNS0_7PatternIT_EERKNS1_IT0_EE'/>
<use f='tvm/src/arith/pattern_match.h' l='406' c='_ZN3tvm5aritheqERKNS0_7PatternIT_EEl'/>
<use f='tvm/src/arith/pattern_match.h' l='406' c='_ZN3tvm5aritheqElRKNS0_7PatternIT_EE'/>
<use f='tvm/src/arith/rewrite_simplify.h' l='152' c='_ZN3tvm5arith17RewriteSimplifier4Impl17ApplyRewriteRulesENS_3tir2EQE'/>
<size>8</size>
<use f='tvm/src/arith/int_set.cc' l='96'/>
<use f='tvm/src/arith/int_set.cc' l='445' c='_ZN3tvm5arith20IntervalSetEvaluator10VisitExpr_EPKNS_3tir6EQNodeE'/>
<size>8</size>
<use f='tvm/src/arith/rewrite_simplify.cc' l='1388' c='_ZN3tvm5arith17RewriteSimplifier4Impl10VisitExpr_EPKNS_3tir6EQNodeE'/>
<use f='tvm/src/arith/rewrite_simplify.cc' l='1388' c='_ZN3tvm5arith17RewriteSimplifier4Impl10VisitExpr_EPKNS_3tir6EQNodeE'/>
<use f='tvm/src/arith/rewrite_simplify.cc' l='1391' c='_ZN3tvm5arith17RewriteSimplifier4Impl10VisitExpr_EPKNS_3tir6EQNodeE'/>
<use f='tvm/src/arith/rewrite_simplify.cc' l='1401' c='_ZN3tvm5arith17RewriteSimplifier4Impl17ApplyRewriteRulesENS_3tir2EQE'/>
<use f='tvm/src/arith/rewrite_simplify.cc' l='1464' c='_ZN3tvm5arith17RewriteSimplifier4Impl10VisitExpr_EPKNS_3tir6NENodeE'/>
<use f='tvm/src/arith/rewrite_simplify.cc' l='1504' c='_ZN3tvm5arith17RewriteSimplifier4Impl10VisitExpr_EPKNS_3tir6LENodeE'/>
<size>8</size>
<use f='tvm/src/arith/solve_linear_inequality.cc' l='82' c='_ZN3tvm5arith20NormalizeComparisons10VisitExpr_EPKNS_3tir6EQNodeE'/>
<size>8</size>
<use f='tvm/src/te/autodiff/jacobian.cc' l='88' c='_ZN3tvm2te15JacobianMutator10VisitExpr_EPKNS_3tir16ProducerLoadNodeE'/>
<size>8</size>
<use f='tvm/src/tir/ir/expr.cc' l='405'/>
<size>8</size>
<fun r='_ZN3tvm3tir2EQC1ENS_8PrimExprES2_NS_4SpanE'/>
<use f='tvm/src/tir/ir/expr_functor.cc' l='200' c='_ZN3tvm3tir11ExprMutator10VisitExpr_EPKNS0_6EQNodeE'/>
<size>8</size>
<use f='tvm/src/tir/op/op.cc' l='501' c='_ZN3tvm5equalENS_8PrimExprES0_NS_4SpanE'/>
<use f='tvm/src/tir/op/op.cc' l='502' c='_ZN3tvm5equalENS_8PrimExprES0_NS_4SpanE'/>
<size>8</size>
<use f='tvm/src/tir/transforms/loop_partition.cc' l='320' c='_ZN3tvm3tir15PartitionFinder11InverseCondERKNS_8PrimExprE'/>
<size>8</size>
<use f='tvm/src/tir/transforms/vectorize_loop.cc' l='212' c='_ZN3tvm3tir10Vectorizer10VisitExpr_EPKNS0_6EQNodeE'/>
<size>8</size>
