<def f='tvm/src/meta_schedule/feature_extractor/per_store_feature.cc' l='1148' ll='1169'/>
<use f='tvm/src/meta_schedule/feature_extractor/per_store_feature.cc' l='1239'/>
<use f='tvm/src/meta_schedule/feature_extractor/per_store_feature.cc' l='1304' c='_ZN3tvm3tir24PerStoreFeatureCollector10VisitStmt_EPKNS0_15BufferStoreNodeE'/>
<size>16</size>
<doc f='tvm/src/meta_schedule/feature_extractor/per_store_feature.cc' l='1147'>/*! \brief Group 5 feature */</doc>
