<inh f='tvm/include/tvm/ir/expr.h' l='112' c='tvm::PrimExpr'/>
<def f='tvm/include/tvm/tir/expr.h' l='374' ll='379'/>
<use f='tvm/include/tvm/tir/expr.h' l='377' c='_ZN3tvm3tir2NEC1ERKS1_'/>
<use f='tvm/include/tvm/tir/expr.h' l='377' c='_ZN3tvm3tir2NEC1EOS1_'/>
<use f='tvm/include/tvm/tir/expr.h' l='377' c='_ZN3tvm3tir2NEaSERKS1_'/>
<use f='tvm/include/tvm/tir/expr.h' l='377' c='_ZN3tvm3tir2NEaSERKS1_'/>
<use f='tvm/include/tvm/tir/expr.h' l='377' c='_ZN3tvm3tir2NEaSEOS1_'/>
<use f='tvm/include/tvm/tir/expr.h' l='377' c='_ZN3tvm3tir2NEaSEOS1_'/>
<size>8</size>
<doc f='tvm/include/tvm/tir/expr.h' l='370'>/*!
 * \brief Managed reference to NENode
 * \sa NENode
 */</doc>
<fun r='_ZN3tvm3tir2NEC1ENS_8PrimExprES2_NS_4SpanE'/>
<fun r='_ZN3tvm3tir2NEC1Ev'/>
<fun r='_ZN3tvm3tir2NEC1ENS_7runtime9ObjectPtrINS2_6ObjectEEE'/>
<fun r='_ZN3tvm3tir2NEC1ERKS1_'/>
<fun r='_ZN3tvm3tir2NEC1EOS1_'/>
<fun r='_ZNK3tvm3tir2NE3getEv'/>
<fun r='_ZN3tvm3tir2NE11CopyOnWriteEv'/>
<use f='tvm/src/arith/const_fold.h' l='394' c='_ZN3tvm5arith12TryConstFoldENS_8PrimExprES1_'/>
<size>8</size>
<use f='tvm/src/arith/pattern_match.h' l='407' c='_ZN3tvm5arithneERKNS0_7PatternIT_EERKNS1_IT0_EE'/>
<use f='tvm/src/arith/pattern_match.h' l='407' c='_ZN3tvm5arithneERKNS0_7PatternIT_EERKNS1_IT0_EE'/>
<use f='tvm/src/arith/pattern_match.h' l='407' c='_ZN3tvm5arithneERKNS0_7PatternIT_EEl'/>
<use f='tvm/src/arith/pattern_match.h' l='407' c='_ZN3tvm5arithneElRKNS0_7PatternIT_EE'/>
<size>8</size>
<use f='tvm/src/arith/int_set.cc' l='97'/>
<use f='tvm/src/arith/int_set.cc' l='447' c='_ZN3tvm5arith20IntervalSetEvaluator10VisitExpr_EPKNS_3tir6NENodeE'/>
<size>8</size>
<use f='tvm/src/arith/rewrite_simplify.cc' l='1435' c='_ZN3tvm5arith17RewriteSimplifier4Impl10VisitExpr_EPKNS_3tir6NENodeE'/>
<size>8</size>
<use f='tvm/src/arith/solve_linear_inequality.cc' l='83' c='_ZN3tvm5arith20NormalizeComparisons10VisitExpr_EPKNS_3tir6NENodeE'/>
<size>8</size>
<use f='tvm/src/script/printer/tir/expr.cc' l='284'/>
<use f='tvm/src/script/printer/tir/expr.cc' l='284'/>
<size>8</size>
<use f='tvm/src/tir/ir/expr.cc' l='424'/>
<size>8</size>
<fun r='_ZN3tvm3tir2NEC1ENS_8PrimExprES2_NS_4SpanE'/>
<use f='tvm/src/tir/ir/expr_functor.cc' l='201' c='_ZN3tvm3tir11ExprMutator10VisitExpr_EPKNS0_6NENodeE'/>
<size>8</size>
<use f='tvm/src/tir/op/op.cc' l='508' c='_ZN3tvm9not_equalENS_8PrimExprES0_NS_4SpanE'/>
<use f='tvm/src/tir/op/op.cc' l='509' c='_ZN3tvm9not_equalENS_8PrimExprES0_NS_4SpanE'/>
<size>8</size>
<use f='tvm/src/tir/transforms/install_debug_spans.cc' l='114' macro='1' c='_ZN3tvm3tir18DebugInfoInstaller10VisitExpr_EPKNS0_6NENodeE'/>
<size>8</size>
<use f='tvm/src/tir/transforms/loop_partition.cc' l='317' c='_ZN3tvm3tir15PartitionFinder11InverseCondERKNS_8PrimExprE'/>
<size>8</size>
<use f='tvm/src/tir/transforms/vectorize_loop.cc' l='213' c='_ZN3tvm3tir10Vectorizer10VisitExpr_EPKNS0_6NENodeE'/>
<size>8</size>
