<inh f='tvm/include/tvm/runtime/object.h' l='511' c='tvm::runtime::ObjectRef'/>
<def f='tvm/include/tvm/meta_schedule/builder.h' l='131' ll='140'/>
<use f='tvm/include/tvm/meta_schedule/builder.h' l='138' c='_ZN3tvm13meta_schedule7Builder9PyBuilderENS_7runtime15TypedPackedFuncIFNS2_5ArrayINS0_13BuilderResultEvEERKNS4_INS0_12BuilderInputEvEEEEE'/>
<use f='tvm/include/tvm/meta_schedule/builder.h' l='139' c='_ZN3tvm13meta_schedule7BuilderC1ERKS1_'/>
<use f='tvm/include/tvm/meta_schedule/builder.h' l='139' c='_ZN3tvm13meta_schedule7BuilderC1EOS1_'/>
<use f='tvm/include/tvm/meta_schedule/builder.h' l='139' c='_ZN3tvm13meta_schedule7BuilderaSERKS1_'/>
<use f='tvm/include/tvm/meta_schedule/builder.h' l='139' c='_ZN3tvm13meta_schedule7BuilderaSERKS1_'/>
<use f='tvm/include/tvm/meta_schedule/builder.h' l='139' c='_ZN3tvm13meta_schedule7BuilderaSEOS1_'/>
<use f='tvm/include/tvm/meta_schedule/builder.h' l='139' c='_ZN3tvm13meta_schedule7BuilderaSEOS1_'/>
<use f='tvm/include/tvm/meta_schedule/task_scheduler.h' l='184' c='_ZN3tvm13meta_schedule17TaskSchedulerNode4TuneENS_7runtime5ArrayINS0_11TuneContextEvEENS3_INS_8FloatImmEvEEiiiNS0_7BuilderENS0_6RunnerENS3_INS0_15Meas9556795'/>
<use f='tvm/include/tvm/meta_schedule/task_scheduler.h' l='227'/>
<use f='tvm/include/tvm/meta_schedule/task_scheduler.h' l='250' c='_ZN3tvm13meta_schedule19PyTaskSchedulerNode4TuneENS_7runtime5ArrayINS0_11TuneContextEvEENS3_INS_8FloatImmEvEEiiiNS0_7BuilderENS0_6RunnerENS3_INS0_15Me9679234'/>
<size>8</size>
<doc f='tvm/include/tvm/meta_schedule/builder.h' l='127'>/*!
 * \brief Managed reference to BuilderNode
 * \sa BuilderNode
 */</doc>
<fun r='_ZN3tvm13meta_schedule7Builder9PyBuilderENS_7runtime15TypedPackedFuncIFNS2_5ArrayINS0_13BuilderResultEvEERKNS4_INS0_12BuilderInputEvEEEEE'/>
<fun r='_ZN3tvm13meta_schedule7BuilderC1ENS_7runtime9ObjectPtrINS2_6ObjectEEE'/>
<fun r='_ZN3tvm13meta_schedule7BuilderC1ERKS1_'/>
<fun r='_ZN3tvm13meta_schedule7BuilderC1EOS1_'/>
<fun r='_ZNK3tvm13meta_schedule7Builder3getEv'/>
<smbr r='tvm::meta_schedule::Builder::_type_is_nullable' t='const bool'/>
<use f='tvm/src/meta_schedule/builder/builder.cc' l='42' c='_ZN3tvm13meta_schedule7Builder9PyBuilderENS_7runtime15TypedPackedFuncIFNS2_5ArrayINS0_13BuilderResultEvEERKNS4_INS0_12BuilderInputEvEEEEE'/>
<use f='tvm/src/meta_schedule/builder/builder.cc' l='45' c='_ZN3tvm13meta_schedule7Builder9PyBuilderENS_7runtime15TypedPackedFuncIFNS2_5ArrayINS0_13BuilderResultEvEERKNS4_INS0_12BuilderInputEvEEEEE'/>
<use f='tvm/src/meta_schedule/builder/builder.cc' l='67'/>
<size>8</size>
<fun r='_ZN3tvm13meta_schedule7Builder9PyBuilderENS_7runtime15TypedPackedFuncIFNS2_5ArrayINS0_13BuilderResultEvEERKNS4_INS0_12BuilderInputEvEEEEE'/>
<use f='tvm/src/meta_schedule/task_scheduler/gradient_based.cc' l='48' c='_ZN3tvm13meta_schedule17GradientBasedNode4TuneENS_7runtime5ArrayINS0_11TuneContextEvEENS3_INS_8FloatImmEvEEiiiNS0_7BuilderENS0_6RunnerENS3_INS0_15Meas2489504'/>
<size>8</size>
<use f='tvm/src/meta_schedule/task_scheduler/task_scheduler.cc' l='41' c='_ZN3tvm13meta_schedule13SendToBuilderEPNS0_14TaskRecordNodeERKNS0_7BuilderE'/>
<use f='tvm/src/meta_schedule/task_scheduler/task_scheduler.cc' l='145' c='_ZN3tvm13meta_schedule17TaskSchedulerNode4TuneENS_7runtime5ArrayINS0_11TuneContextEvEENS3_INS_8FloatImmEvEEiiiNS0_7BuilderENS0_6RunnerENS3_INS0_15Meas9556795'/>
<use f='tvm/src/meta_schedule/task_scheduler/task_scheduler.cc' l='351' c='_ZN3tvm13meta_schedule19PyTaskSchedulerNode4TuneENS_7runtime5ArrayINS0_11TuneContextEvEENS3_INS_8FloatImmEvEEiiiNS0_7BuilderENS0_6RunnerENS3_INS0_15Me9679234'/>
<size>8</size>
