<dec f='tvm/include/tvm/ir/diagnostic.h' l='171' type='tvm::IRModule'/>
<use f='tvm/include/tvm/ir/diagnostic.h' l='180' u='a' c='_ZN3tvm21DiagnosticContextNode10VisitAttrsEPNS_11AttrVisitorE'/>
<use f='tvm/include/tvm/ir/diagnostic.h' l='185' u='r' c='_ZNK3tvm21DiagnosticContextNode12SEqualReduceEPKS0_NS_13SEqualReducerE'/>
<use f='tvm/include/tvm/ir/diagnostic.h' l='185' u='r' c='_ZNK3tvm21DiagnosticContextNode12SEqualReduceEPKS0_NS_13SEqualReducerE'/>
<offset>128</offset>
<doc f='tvm/include/tvm/ir/diagnostic.h' l='170'>/*! \brief The Module to report against. */</doc>
<use f='tvm/src/ir/diagnostic.cc' l='118' u='w' c='_ZN3tvm17DiagnosticContextC1ERKNS_8IRModuleERKNS_18DiagnosticRendererE'/>
<use f='tvm/src/ir/diagnostic.cc' l='233' u='m' c='_ZN3tvm8ReportAtERKNS_17DiagnosticContextERSoRKNS_4SpanERKNS_10DiagnosticE'/>
<use f='tvm/src/ir/diagnostic.cc' l='234' u='m' c='_ZN3tvm8ReportAtERKNS_17DiagnosticContextERSoRKNS_4SpanERKNS_10DiagnosticE'/>
<use f='tvm/src/ir/diagnostic.cc' l='237' u='m' c='_ZN3tvm8ReportAtERKNS_17DiagnosticContextERSoRKNS_4SpanERKNS_10DiagnosticE'/>
<use f='tvm/src/relay/analysis/type_solver.cc' l='531' u='r' c='_ZN3tvm5relay10TypeSolverC1ERKNS_9GlobalVarENS_17DiagnosticContextE'/>
