<def f='tvm/src/meta_schedule/feature_extractor/per_store_feature.cc' l='1125' ll='1154'/>
<use f='tvm/src/meta_schedule/feature_extractor/per_store_feature.cc' l='1251'/>
<use f='tvm/src/meta_schedule/feature_extractor/per_store_feature.cc' l='1283' c='_ZN3tvm3tir24PerStoreFeatureCollector7CollectEbllRKNS_8IRModuleE'/>
<use f='tvm/src/meta_schedule/feature_extractor/per_store_feature.cc' l='1329' c='_ZN3tvm3tir24PerStoreFeatureCollector17HandleBufferAllocERKNS0_6BufferE'/>
<size>24</size>
<doc f='tvm/src/meta_schedule/feature_extractor/per_store_feature.cc' l='1124'>/*! \brief Group 4 feature */</doc>
