<def f='tvm/src/meta_schedule/feature_extractor/per_store_feature.cc' l='407' ll='531'/>
<use f='tvm/src/meta_schedule/feature_extractor/per_store_feature.cc' l='1237'/>
<use f='tvm/src/meta_schedule/feature_extractor/per_store_feature.cc' l='1299' c='_ZN3tvm3tir24PerStoreFeatureCollector10VisitStmt_EPKNS0_15BufferStoreNodeE'/>
<size>288</size>
<doc f='tvm/src/meta_schedule/feature_extractor/per_store_feature.cc' l='406'>/*! \brief Group 1 features */</doc>
