<def f='tvm/src/meta_schedule/feature_extractor/per_store_feature.cc' l='1216' ll='1227'/>
<use f='tvm/src/meta_schedule/feature_extractor/per_store_feature.cc' l='1240'/>
<use f='tvm/src/meta_schedule/feature_extractor/per_store_feature.cc' l='1380' c='_ZN3tvm13meta_schedule19PerStoreFeatureNode11ExtractFromERKNS0_11TuneContextERKNS_7runtime5ArrayINS0_16MeasureCandidateEvEE'/>
<use f='tvm/src/meta_schedule/feature_extractor/per_store_feature.cc' l='1382' c='_ZN3tvm13meta_schedule19PerStoreFeatureNode11ExtractFromERKNS0_11TuneContextERKNS_7runtime5ArrayINS0_16MeasureCandidateEvEE'/>
<size>24</size>
<doc f='tvm/src/meta_schedule/feature_extractor/per_store_feature.cc' l='1215'>/*! \brief Group 6 feature */</doc>
