<inh f='tvm/include/tvm/tir/stmt.h' l='57' c='tvm::tir::Stmt'/>
<def f='tvm/include/tvm/tir/stmt.h' l='1012' ll='1020'/>
<use f='tvm/include/tvm/tir/stmt.h' l='1018' c='_ZN3tvm3tir3ForC1ERKS1_'/>
<use f='tvm/include/tvm/tir/stmt.h' l='1018' c='_ZN3tvm3tir3ForC1EOS1_'/>
<use f='tvm/include/tvm/tir/stmt.h' l='1018' c='_ZN3tvm3tir3ForaSERKS1_'/>
<use f='tvm/include/tvm/tir/stmt.h' l='1018' c='_ZN3tvm3tir3ForaSERKS1_'/>
<use f='tvm/include/tvm/tir/stmt.h' l='1018' c='_ZN3tvm3tir3ForaSEOS1_'/>
<use f='tvm/include/tvm/tir/stmt.h' l='1018' c='_ZN3tvm3tir3ForaSEOS1_'/>
<size>8</size>
<doc f='tvm/include/tvm/tir/stmt.h' l='1008'>/*!
 * \brief Managed reference to ForNode.
 * \sa ForNode
 */</doc>
<fun r='_ZN3tvm3tir3ForC1ENS0_3VarENS_8PrimExprES3_NS0_7ForKindENS0_4StmtENS_7runtime8OptionalINS0_7IterVarEEENS6_3MapINS6_6StringENS6_9ObjectRefEvvEENS_4SpanE'/>
<fun r='_ZN3tvm3tir3ForC1Ev'/>
<fun r='_ZN3tvm3tir3ForC1ENS_7runtime9ObjectPtrINS2_6ObjectEEE'/>
<fun r='_ZN3tvm3tir3ForC1ERKS1_'/>
<fun r='_ZN3tvm3tir3ForC1EOS1_'/>
<fun r='_ZNK3tvm3tir3For3getEv'/>
<fun r='_ZN3tvm3tir3For11CopyOnWriteEv'/>
<use f='tvm/src/auto_scheduler/feature.cc' l='637' c='_ZN3tvm14auto_scheduler24PerStoreFeatureExtractor10VisitStmt_EPKNS_3tir12AttrStmtNodeE'/>
<size>8</size>
<use f='tvm/include/tvm/tir/schedule/schedule.h' l='163' c='_ZNK3tvm3tir12ScheduleNode3GetERKNS0_6LoopRVE'/>
<use f='tvm/src/tir/schedule/analysis.h' l='579' c='_ZN3tvm3tir15SuggestIndexMapERKNS0_6BufferERKNS_7runtime5ArrayINS_8PrimExprEvEERKNS5_INS0_3ForEvEERKS6_PNS_5arith8AnalyzerE'/>
<use f='tvm/src/tir/schedule/analysis.h' l='734'/>
<use f='tvm/src/tir/schedule/analysis.h' l='736'/>
<use f='tvm/src/tir/schedule/error.h' l='59' c='_ZN3tvm3tir17LoopPositionErrorC1ENS_8IRModuleENS0_3ForENS0_5BlockERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE'/>
<use f='tvm/src/tir/schedule/error.h' l='80'/>
<use f='tvm/src/tir/schedule/utils.h' l='128' c='_ZN3tvm3tir15LoopSRefs2LoopsERKNS_7runtime5ArrayINS0_8StmtSRefEvEE'/>
<use f='tvm/src/tir/schedule/utils.h' l='129' c='_ZN3tvm3tir15LoopSRefs2LoopsERKNS_7runtime5ArrayINS0_8StmtSRefEvEE'/>
<use f='tvm/src/tir/schedule/utils.h' l='133' c='_ZN3tvm3tir15LoopSRefs2LoopsERKNS_7runtime5ArrayINS0_8StmtSRefEvEE'/>
<use f='tvm/src/tir/schedule/utils.h' l='232' c='_ZN3tvm3tir15IterVarFromLoopERKNS0_3ForENS_7runtime6StringENS0_11IterVarTypeE'/>
<size>8</size>
<use f='tvm/src/meta_schedule/postproc/rewrite_layout.cc' l='41' c='_ZN3tvm3tir22BufferReadPosCollector10VisitStmt_EPKNS0_7ForNodeE'/>
<use f='tvm/src/meta_schedule/postproc/rewrite_layout.cc' l='97'/>
<size>8</size>
<use f='tvm/src/meta_schedule/schedule_rule/cross_thread_reduction.cc' l='133' c='_ZN3tvm13meta_schedule24CrossThreadReductionNode13InThreadScopeERKNS_3tir8ScheduleERKNS2_7BlockRVE'/>
<size>8</size>
<use f='tvm/src/printer/tvmscript_printer.cc' l='195'/>
<use f='tvm/src/printer/tvmscript_printer.cc' l='197'/>
<use f='tvm/src/printer/tvmscript_printer.cc' l='319' c='_ZN3tvm3tir16TVMScriptPrinter9PrintLoopERKNS0_3ForE'/>
<use f='tvm/src/printer/tvmscript_printer.cc' l='1305' c='_ZN3tvm3tir16TVMScriptPrinter10VisitStmt_EPKNS0_7ForNodeE'/>
<use f='tvm/src/printer/tvmscript_printer.cc' l='1308' c='_ZN3tvm3tir16TVMScriptPrinter10VisitStmt_EPKNS0_7ForNodeE'/>
<use f='tvm/src/printer/tvmscript_printer.cc' l='1311' c='_ZN3tvm3tir16TVMScriptPrinter10VisitStmt_EPKNS0_7ForNodeE'/>
<use f='tvm/src/printer/tvmscript_printer.cc' l='1326' c='_ZN3tvm3tir16TVMScriptPrinter10VisitStmt_EPKNS0_7ForNodeE'/>
<use f='tvm/src/printer/tvmscript_printer.cc' l='1908' c='_ZN3tvm3tir16TVMScriptPrinter9PrintLoopERKNS0_3ForE'/>
<use f='tvm/src/printer/tvmscript_printer.cc' l='1980' c='_ZN3tvm3tir30TVMScriptPrinterWithDiagnostic9PrintLoopERKNS0_3ForE'/>
<use f='tvm/src/printer/tvmscript_printer.cc' l='1999' c='_ZN3tvm3tir30TVMScriptPrinterWithDiagnostic9PrintLoopERKNS0_3ForE'/>
<size>8</size>
<use f='tvm/src/relay/backend/aot/aot_lower_main.cc' l='696' c='_ZN3tvm5relay7backend3aot14AOTMainLowerer12CopyToOutputENS_8PrimExprES4_bm'/>
<size>8</size>
<use f='tvm/src/relay/backend/aot_executor_codegen.cc' l='516' c='_ZN3tvm5relay7backend18AOTExecutorCodegen12CopyToOutputENS_8PrimExprES3_bm'/>
<size>8</size>
<use f='tvm/src/relay/backend/contrib/example_target_hooks/relay_to_tir.cc' l='146' c='_ZN3tvm5relay7contrib20example_target_hooks12_GLOBAL__N_120ConvertAddToSubtract30ReplaceAddWithSubtractPrimFuncERKNS0_8FunctionE'/>
<size>8</size>
<use f='tvm/src/script/ir_builder/tir/ir.cc' l='320' c='_ZN3tvm6script10ir_builder3tir6SerialENS_8PrimExprES3_NS_7runtime8OptionalINS4_3MapINS4_6StringENS4_9ObjectRefEvvEEEE'/>
<use f='tvm/src/script/ir_builder/tir/ir.cc' l='320' c='_ZN3tvm6script10ir_builder3tir8ParallelENS_8PrimExprES3_NS_7runtime8OptionalINS4_3MapINS4_6StringENS4_9ObjectRefEvvEEEE'/>
<use f='tvm/src/script/ir_builder/tir/ir.cc' l='320' c='_ZN3tvm6script10ir_builder3tir10VectorizedENS_8PrimExprES3_NS_7runtime8OptionalINS4_3MapINS4_6StringENS4_9ObjectRefEvvEEEE'/>
<use f='tvm/src/script/ir_builder/tir/ir.cc' l='320' c='_ZN3tvm6script10ir_builder3tir6UnrollENS_8PrimExprES3_NS_7runtime8OptionalINS4_3MapINS4_6StringENS4_9ObjectRefEvvEEEE'/>
<use f='tvm/src/script/ir_builder/tir/ir.cc' l='342' c='_ZN3tvm6script10ir_builder3tir13ThreadBindingENS_8PrimExprES3_NS_7runtime6StringENS4_8OptionalINS4_3MapIS5_NS4_9ObjectRefEvvEEEE'/>
<use f='tvm/src/script/ir_builder/tir/ir.cc' l='347' c='_ZN3tvm6script10ir_builder3tir13ThreadBindingENS_8PrimExprES3_NS_7runtime6StringENS4_8OptionalINS4_3MapIS5_NS4_9ObjectRefEvvEEEE'/>
<use f='tvm/src/script/ir_builder/tir/ir.cc' l='369' c='_ZN3tvm6script10ir_builder3tir4GridENS_7runtime5ArrayINS_8PrimExprEvEE'/>
<size>8</size>
<use f='tvm/src/target/llvm/codegen_cpu.cc' l='1539' c='_ZN3tvm7codegen10CodeGenCPU10VisitStmt_EPKNS_3tir7ForNodeE'/>
<size>8</size>
<use f='tvm/src/te/operation/create_primfunc.cc' l='358' c='_ZN3tvm3tir23GenerateStmtFromComputeERKNS_2te9ComputeOpEPNS0_14CreateFuncInfoEPNS_5arith8AnalyzerE'/>
<size>8</size>
<use f='tvm/src/te/operation/hybrid_op.cc' l='236' c='_ZZN3tvm2te15ApplyLoopShapesERKNS0_5StageERKSt13unordered_mapINS_3tir7IterVarENS_5RangeESt4hashIS6_ESt8equal_toIS6_ESaISt4pairIKS6_S7_EEENS5_4StmtEEN114292304'/>
<use f='tvm/src/te/operation/hybrid_op.cc' l='238' c='_ZZN3tvm2te15ApplyLoopShapesERKNS0_5StageERKSt13unordered_mapINS_3tir7IterVarENS_5RangeESt4hashIS6_ESt8equal_toIS6_ESaISt4pairIKS6_S7_EEENS5_4StmtEEN114292304'/>
<use f='tvm/src/te/operation/hybrid_op.cc' l='280' c='_ZZN3tvm2te15ApplyLoopShapesERKNS0_5StageERKSt13unordered_mapINS_3tir7IterVarENS_5RangeESt4hashIS6_ESt8equal_toIS6_ESaISt4pairIKS6_S7_EEENS5_4StmtEEN95475935'/>
<use f='tvm/src/te/operation/hybrid_op.cc' l='334' c='_ZZN3tvm2te20ApplyLoopAnnotationsERKNS0_5StageERKSt13unordered_mapINS_3tir7IterVarES6_St4hashIS6_ESt8equal_toIS6_ESaISt4pairIKS6_S6_EEENS5_4StmtEEN13L7563757'/>
<use f='tvm/src/te/operation/hybrid_op.cc' l='417' c='_ZZN3tvm2te14ApplyLoopOrderERKNS0_5StageERKSt13unordered_mapINS_3tir7IterVarENS_5RangeESt4hashIS6_ESt8equal_toIS6_ESaISt4pairIKS6_S7_EEERKS4_IS6_S6_S92590662'/>
<size>8</size>
<use f='tvm/src/te/operation/op_utils.cc' l='135' c='_ZN3tvm2te12MakeLoopNestERKNS0_5StageERKSt13unordered_mapINS_3tir7IterVarENS_5RangeESt4hashIS6_ESt8equal_toIS6_ESaISt4pairIKS6_S7_EEEmbRKSt13unordered9689248'/>
<use f='tvm/src/te/operation/op_utils.cc' l='139' c='_ZN3tvm2te12MakeLoopNestERKNS0_5StageERKSt13unordered_mapINS_3tir7IterVarENS_5RangeESt4hashIS6_ESt8equal_toIS6_ESaISt4pairIKS6_S7_EEEmbRKSt13unordered9689248'/>
<size>8</size>
<use f='tvm/src/tir/ir/data_type_rewriter.cc' l='40' c='_ZN3tvm3tir17DataTypeLegalizer10VisitStmt_EPKNS0_7ForNodeE'/>
<use f='tvm/src/tir/ir/data_type_rewriter.cc' l='505' c='_ZN3tvm3tir21IndexDataTypeRewriter10VisitStmt_EPKNS0_7ForNodeE'/>
<use f='tvm/src/tir/ir/data_type_rewriter.cc' l='505' c='_ZN3tvm3tir21IndexDataTypeRewriter10VisitStmt_EPKNS0_7ForNodeE'/>
<size>8</size>
<use f='tvm/src/tir/ir/stmt.cc' l='185'/>
<size>8</size>
<fun r='_ZN3tvm3tir3ForC1ENS0_3VarENS_8PrimExprES3_NS0_7ForKindENS0_4StmtENS_7runtime8OptionalINS0_7IterVarEEENS6_3MapINS6_6StringENS6_9ObjectRefEvvEENS_4SpanE'/>
<use f='tvm/src/tir/schedule/analysis/analysis.cc' l='727' c='_ZZN3tvm3tir23CheckLoopStartsWithZeroERKNS0_13ScheduleStateERKNS0_8StmtSRefEPNS_5arith8AnalyzerEEN25LoopNotStartWithZeroErrorC1ENS_8IRModuleENS0_3ForE'/>
<use f='tvm/src/tir/schedule/analysis/analysis.cc' l='742' c='_ZN3tvm3tir23CheckLoopStartsWithZeroERKNS0_13ScheduleStateERKNS0_8StmtSRefEPNS_5arith8AnalyzerE'/>
<use f='tvm/src/tir/schedule/analysis/analysis.cc' l='746' c='_ZN3tvm3tir23CheckLoopStartsWithZeroERKNS0_13ScheduleStateERKNS0_8StmtSRefEPNS_5arith8AnalyzerE'/>
<use f='tvm/src/tir/schedule/analysis/analysis.cc' l='1811' c='_ZN3tvm3tir23GetTensorizeLoopMappingERKNS0_13ScheduleStateERKNS0_8StmtSRefERKNS0_8PrimFuncEb'/>
<use f='tvm/src/tir/schedule/analysis/analysis.cc' l='1817' c='_ZN3tvm3tir23GetTensorizeLoopMappingERKNS0_13ScheduleStateERKNS0_8StmtSRefERKNS0_8PrimFuncEb'/>
<size>8</size>
<use f='tvm/src/tir/schedule/analysis/layout.cc' l='128' c='_ZN3tvm3tir15SuggestIndexMapERKNS0_6BufferERKNS_7runtime5ArrayINS_8PrimExprEvEERKNS5_INS0_3ForEvEERKS6_PNS_5arith8AnalyzerE'/>
<use f='tvm/src/tir/schedule/analysis/layout.cc' l='137' c='_ZN3tvm3tir15SuggestIndexMapERKNS0_6BufferERKNS_7runtime5ArrayINS_8PrimExprEvEERKNS5_INS0_3ForEvEERKS6_PNS_5arith8AnalyzerE'/>
<use f='tvm/src/tir/schedule/analysis/layout.cc' l='242'/>
<size>8</size>
<use f='tvm/src/tir/schedule/concrete_schedule.h' l='75' c='_ZNK3tvm3tir20ConcreteScheduleNode3GetERKNS0_6LoopRVE'/>
<use f='tvm/src/tir/schedule/concrete_schedule.h' l='219' c='_ZNK3tvm3tir20ConcreteScheduleNode3GetERKNS0_6LoopRVE'/>
<use f='tvm/src/tir/schedule/concrete_schedule.h' l='222' c='_ZNK3tvm3tir20ConcreteScheduleNode3GetERKNS0_6LoopRVE'/>
<use f='tvm/src/tir/schedule/concrete_schedule.cc' l='391' c='_ZZN3tvm3tir20ConcreteScheduleNode5SplitERKNS0_6LoopRVERKNS_7runtime5ArrayINS5_8OptionalINS_8PrimExprEEEvEEbEN23WrongFactorProductErrorC1ENS_8IRModuleENS0_3ForE'/>
<use f='tvm/src/tir/schedule/concrete_schedule.cc' l='406' c='_ZN3tvm3tir20ConcreteScheduleNode5SplitERKNS0_6LoopRVERKNS_7runtime5ArrayINS5_8OptionalINS_8PrimExprEEEvEEb'/>
<use f='tvm/src/tir/schedule/concrete_schedule.cc' l='466' c='_ZN3tvm3tir20ConcreteScheduleNode5SplitERKNS0_6LoopRVERKNS_7runtime5ArrayINS5_8OptionalINS_8PrimExprEEEvEEb'/>
<size>8</size>
<use f='tvm/src/tir/schedule/primitive/annotate.cc' l='46' c='_ZN3tvm3tir8AnnotateENS0_13ScheduleStateERKNS0_8StmtSRefERKNS_7runtime6StringERKNS5_9ObjectRefE'/>
<use f='tvm/src/tir/schedule/primitive/annotate.cc' l='77' c='_ZN3tvm3tir10UnannotateENS0_13ScheduleStateERKNS0_8StmtSRefERKNS_7runtime6StringE'/>
<size>8</size>
<use f='tvm/src/tir/schedule/primitive/blockize_tensorize.cc' l='49' c='_ZN3tvm3tir25SubspaceNotDivisibleErrorC1ENS_8IRModuleENS0_3ForENS0_5BlockE'/>
<use f='tvm/src/tir/schedule/primitive/blockize_tensorize.cc' l='69'/>
<use f='tvm/src/tir/schedule/primitive/blockize_tensorize.cc' l='339' c='_ZN3tvm3tir17GenerateOuterInitERKNS0_4StmtERKNS0_12BlockRealizeERKSt6vectorIPKNS0_7ForNodeESaISA_EENS_7runtime6StringE'/>
<use f='tvm/src/tir/schedule/primitive/blockize_tensorize.cc' l='427' c='_ZN3tvm3tir12MakeLoopNestENS0_4StmtERKSt6vectorIPKNS0_7ForNodeESaIS5_EE'/>
<use f='tvm/src/tir/schedule/primitive/blockize_tensorize.cc' l='445' c='_ZN3tvm3tir12BlockizeImplERKNS0_13ScheduleStateERKNS0_8StmtSRefEPNS_7runtime3MapINS0_5BlockES9_vvEEPNS_5arith8AnalyzerEb'/>
<size>8</size>
<use f='tvm/src/tir/schedule/primitive/cache_index.cc' l='287' c='_ZN3tvm3tir19MakeIndexCacheStageEPNS0_9IndexInfoE'/>
<size>8</size>
<use f='tvm/src/tir/schedule/primitive/cache_read_write.cc' l='157' c='_ZN3tvm3tir14MakeCacheStageERKNS0_12BufferRegionEPNS0_14CacheStageInfoERKNS_7runtime6StringE'/>
<use f='tvm/src/tir/schedule/primitive/cache_read_write.cc' l='267' c='_ZN3tvm3tir16MakeReIndexStageERKNS0_5BlockEPNS0_14CacheStageInfoERKSt13unordered_setINS0_3VarENS_7runtime13ObjectPtrHashENS8_14ObjectPtrEqualESaIS7_EE4253367'/>
<size>8</size>
<use f='tvm/src/tir/schedule/primitive/compute_at.cc' l='114' c='_ZN3tvm3tir19NotInSameScopeErrorC1ENS_8IRModuleERKNS0_8StmtSRefES5_'/>
<use f='tvm/src/tir/schedule/primitive/compute_at.cc' l='118'/>
<use f='tvm/src/tir/schedule/primitive/compute_at.cc' l='237' c='_ZN3tvm3tir18ScopeReconstructorC1ENS0_5BlockES2_NS0_3ForE'/>
<use f='tvm/src/tir/schedule/primitive/compute_at.cc' l='290' c='_ZN3tvm3tir18ScopeReconstructor11MakeNewLoopEiSt6vectorINS0_18BlockVarDomainInfoESaIS3_EEPNS_5arith8AnalyzerEb'/>
<use f='tvm/src/tir/schedule/primitive/compute_at.cc' l='300' c='_ZN3tvm3tir18ScopeReconstructor11MakeNewLoopEiSt6vectorINS0_18BlockVarDomainInfoESaIS3_EEPNS_5arith8AnalyzerEb'/>
<use f='tvm/src/tir/schedule/primitive/compute_at.cc' l='330'/>
<use f='tvm/src/tir/schedule/primitive/compute_at.cc' l='332'/>
<use f='tvm/src/tir/schedule/primitive/compute_at.cc' l='600' c='_ZN3tvm3tir31ComputeAtOrReverseComputeAtImplENS0_13ScheduleStateERKNS0_8StmtSRefES4_bPNS_5arith8AnalyzerEbi'/>
<size>8</size>
<use f='tvm/src/tir/schedule/primitive/decompose_padding.cc' l='197' c='_ZN3tvm3tirL16CreateConstBlockEPKNS0_16BlockRealizeNodeERKNS0_16PaddingBlockInfoERKNS_7runtime5ArrayINS0_3ForEvEERKNS0_4StmtEPNS_5arith8AnalyzerE'/>
<use f='tvm/src/tir/schedule/primitive/decompose_padding.cc' l='233' c='_ZN3tvm3tirL16CreateConstBlockEPKNS0_16BlockRealizeNodeERKNS0_16PaddingBlockInfoERKNS_7runtime5ArrayINS0_3ForEvEERKNS0_4StmtEPNS_5arith8AnalyzerE'/>
<use f='tvm/src/tir/schedule/primitive/decompose_padding.cc' l='254' c='_ZN3tvm3tirL16CreateConstBlockEPKNS0_16BlockRealizeNodeERKNS0_16PaddingBlockInfoERKNS_7runtime5ArrayINS0_3ForEvEERKNS0_4StmtEPNS_5arith8AnalyzerE'/>
<use f='tvm/src/tir/schedule/primitive/decompose_padding.cc' l='256' c='_ZN3tvm3tirL16CreateConstBlockEPKNS0_16BlockRealizeNodeERKNS0_16PaddingBlockInfoERKNS_7runtime5ArrayINS0_3ForEvEERKNS0_4StmtEPNS_5arith8AnalyzerE'/>
<use f='tvm/src/tir/schedule/primitive/decompose_padding.cc' l='266' c='_ZN3tvm3tirL18CreateInBoundBlockEPKNS0_16BlockRealizeNodeERKNS0_16PaddingBlockInfoERKNS_7runtime5ArrayINS0_3ForEvEERKNS0_4StmtEPNS_5arith8AnalyzerE'/>
<use f='tvm/src/tir/schedule/primitive/decompose_padding.cc' l='275' c='_ZN3tvm3tirL18CreateInBoundBlockEPKNS0_16BlockRealizeNodeERKNS0_16PaddingBlockInfoERKNS_7runtime5ArrayINS0_3ForEvEERKNS0_4StmtEPNS_5arith8AnalyzerE'/>
<use f='tvm/src/tir/schedule/primitive/decompose_padding.cc' l='339' c='_ZN3tvm3tirL18CreateInBoundBlockEPKNS0_16BlockRealizeNodeERKNS0_16PaddingBlockInfoERKNS_7runtime5ArrayINS0_3ForEvEERKNS0_4StmtEPNS_5arith8AnalyzerE'/>
<use f='tvm/src/tir/schedule/primitive/decompose_padding.cc' l='343' c='_ZN3tvm3tirL18CreateInBoundBlockEPKNS0_16BlockRealizeNodeERKNS0_16PaddingBlockInfoERKNS_7runtime5ArrayINS0_3ForEvEERKNS0_4StmtEPNS_5arith8AnalyzerE'/>
<use f='tvm/src/tir/schedule/primitive/decompose_padding.cc' l='360'/>
<use f='tvm/src/tir/schedule/primitive/decompose_padding.cc' l='362'/>
<use f='tvm/src/tir/schedule/primitive/decompose_padding.cc' l='434' c='_ZN3tvm3tir20DecomposePaddingImplENS0_13ScheduleStateERKNS0_8StmtSRefES4_b'/>
<use f='tvm/src/tir/schedule/primitive/decompose_padding.cc' l='437' c='_ZN3tvm3tir20DecomposePaddingImplENS0_13ScheduleStateERKNS0_8StmtSRefES4_b'/>
<use f='tvm/src/tir/schedule/primitive/decompose_padding.cc' l='437' c='_ZN3tvm3tir20DecomposePaddingImplENS0_13ScheduleStateERKNS0_8StmtSRefES4_b'/>
<use f='tvm/src/tir/schedule/primitive/decompose_padding.cc' l='438' c='_ZN3tvm3tir20DecomposePaddingImplENS0_13ScheduleStateERKNS0_8StmtSRefES4_b'/>
<use f='tvm/src/tir/schedule/primitive/decompose_padding.cc' l='440' c='_ZN3tvm3tir20DecomposePaddingImplENS0_13ScheduleStateERKNS0_8StmtSRefES4_b'/>
<use f='tvm/src/tir/schedule/primitive/decompose_padding.cc' l='440' c='_ZN3tvm3tir20DecomposePaddingImplENS0_13ScheduleStateERKNS0_8StmtSRefES4_b'/>
<size>8</size>
<use f='tvm/src/tir/schedule/primitive/for_kind.cc' l='121' c='_ZN3tvm3tir22CheckParallelizabilityERKNS0_13ScheduleStateERKNS0_3ForENS0_7ForKindENS_7runtime11ThreadScopeE'/>
<use f='tvm/src/tir/schedule/primitive/for_kind.cc' l='164' c='_ZN3tvm3tir22ParallelizeComputationERKNS0_13ScheduleStateERKNS0_8StmtSRefENS0_7ForKindENS_7runtime8OptionalINS0_7IterVarEEE'/>
<use f='tvm/src/tir/schedule/primitive/for_kind.cc' l='173' c='_ZN3tvm3tir22ParallelizeComputationERKNS0_13ScheduleStateERKNS0_8StmtSRefENS0_7ForKindENS_7runtime8OptionalINS0_7IterVarEEE'/>
<use f='tvm/src/tir/schedule/primitive/for_kind.cc' l='193' c='_ZN3tvm3tir6UnrollENS0_13ScheduleStateERKNS0_8StmtSRefE'/>
<size>8</size>
<use f='tvm/src/tir/schedule/primitive/layout_transformation.cc' l='75'/>
<use f='tvm/src/tir/schedule/primitive/layout_transformation.cc' l='113'/>
<use f='tvm/src/tir/schedule/primitive/layout_transformation.cc' l='125' c='_ZN3tvm3tir22TransformLayoutPlanner10VisitStmt_EPKNS0_7ForNodeE'/>
<use f='tvm/src/tir/schedule/primitive/layout_transformation.cc' l='180' c='_ZN3tvm3tir22TransformLayoutPlanner10VisitStmt_EPKNS0_15BufferStoreNodeE'/>
<use f='tvm/src/tir/schedule/primitive/layout_transformation.cc' l='489' c='_ZNK3tvm3tir22TransformLayoutPlanner20FinalizeProloguePlanENS0_6BufferENS0_8IndexMapES3_NS_8PrimExprENS_7runtime8OptionalIS3_EE'/>
<use f='tvm/src/tir/schedule/primitive/layout_transformation.cc' l='521' c='_ZNK3tvm3tir22TransformLayoutPlanner23FinalizeReplacementPlanENS0_6BufferENS0_8IndexMapES3_NS_8PrimExprENS_7runtime8OptionalIS3_EE'/>
<use f='tvm/src/tir/schedule/primitive/layout_transformation.cc' l='527' c='_ZNK3tvm3tir22TransformLayoutPlanner23FinalizeReplacementPlanENS0_6BufferENS0_8IndexMapES3_NS_8PrimExprENS_7runtime8OptionalIS3_EE'/>
<use f='tvm/src/tir/schedule/primitive/layout_transformation.cc' l='579' c='_ZNK3tvm3tir22TransformLayoutPlanner20FinalizeEpiloguePlanENS0_6BufferENS0_8IndexMapES3_NS_8PrimExprENS_7runtime8OptionalIS3_EE'/>
<use f='tvm/src/tir/schedule/primitive/layout_transformation.cc' l='596' c='_ZN3tvm3tir22TransformLayoutPlanner11BindLoopVarC1EPS1_NS0_3ForE'/>
<use f='tvm/src/tir/schedule/primitive/layout_transformation.cc' l='679'/>
<use f='tvm/src/tir/schedule/primitive/layout_transformation.cc' l='788' c='_ZN3tvm3tir23TransformLayoutRewriter10VisitStmt_EPKNS0_7ForNodeE'/>
<use f='tvm/src/tir/schedule/primitive/layout_transformation.cc' l='788' c='_ZN3tvm3tir23TransformLayoutRewriter10VisitStmt_EPKNS0_7ForNodeE'/>
<use f='tvm/src/tir/schedule/primitive/layout_transformation.cc' l='1392' c='_ZN3tvm3tir20TransformBlockLayoutENS0_13ScheduleStateERKNS0_8StmtSRefERKNS0_8IndexMapE'/>
<size>8</size>
<use f='tvm/src/tir/schedule/primitive/loop_transformation.cc' l='86' c='_ZN3tvm3tir27IterMapSimplifyBlockBinding16SimplifyBindingsENS0_4StmtERKNS_7runtime5ArrayINS0_8StmtSRefEvEEPNS3_7MapNodeEb'/>
<use f='tvm/src/tir/schedule/primitive/loop_transformation.cc' l='93' c='_ZN3tvm3tir27IterMapSimplifyBlockBinding16SimplifyBindingsENS0_4StmtERKNS_7runtime5ArrayINS0_8StmtSRefEvEEPNS3_7MapNodeEb'/>
<use f='tvm/src/tir/schedule/primitive/loop_transformation.cc' l='197' c='_ZN3tvm3tir33HasAnnotationOrThreadBindingErrorC1ENS_8IRModuleENS0_3ForE'/>
<use f='tvm/src/tir/schedule/primitive/loop_transformation.cc' l='213'/>
<use f='tvm/src/tir/schedule/primitive/loop_transformation.cc' l='218' c='_ZN3tvm3tir19OuterNotInnerParentC1ENS_8IRModuleENS0_3ForES3_'/>
<use f='tvm/src/tir/schedule/primitive/loop_transformation.cc' l='218' c='_ZN3tvm3tir19OuterNotInnerParentC1ENS_8IRModuleENS0_3ForES3_'/>
<use f='tvm/src/tir/schedule/primitive/loop_transformation.cc' l='234'/>
<use f='tvm/src/tir/schedule/primitive/loop_transformation.cc' l='235'/>
<use f='tvm/src/tir/schedule/primitive/loop_transformation.cc' l='240' c='_ZN3tvm3tir17NotOnlyChildErrorC1ENS_8IRModuleENS0_3ForES3_'/>
<use f='tvm/src/tir/schedule/primitive/loop_transformation.cc' l='240' c='_ZN3tvm3tir17NotOnlyChildErrorC1ENS_8IRModuleENS0_3ForES3_'/>
<use f='tvm/src/tir/schedule/primitive/loop_transformation.cc' l='256'/>
<use f='tvm/src/tir/schedule/primitive/loop_transformation.cc' l='257'/>
<use f='tvm/src/tir/schedule/primitive/loop_transformation.cc' l='280' c='_ZN3tvm3tir23WrongFactorProductErrorC1ENS_8IRModuleENS0_3ForE'/>
<use f='tvm/src/tir/schedule/primitive/loop_transformation.cc' l='295'/>
<use f='tvm/src/tir/schedule/primitive/loop_transformation.cc' l='300' c='_ZN3tvm3tir24LoopMultiAppearanceErrorC1ENS_8IRModuleENS0_3ForE'/>
<use f='tvm/src/tir/schedule/primitive/loop_transformation.cc' l='314'/>
<use f='tvm/src/tir/schedule/primitive/loop_transformation.cc' l='355' c='_ZN3tvm3tir18DependentLoopErrorC1ENS_8IRModuleENS0_3ForENS_7runtime6StringENS1_13PrimitiveKindE'/>
<use f='tvm/src/tir/schedule/primitive/loop_transformation.cc' l='380'/>
<use f='tvm/src/tir/schedule/primitive/loop_transformation.cc' l='394' c='_ZN3tvm3tir5SplitENS0_13ScheduleStateERKNS0_8StmtSRefERKNS_7runtime5ArrayINS_8PrimExprEvEEb'/>
<use f='tvm/src/tir/schedule/primitive/loop_transformation.cc' l='438' c='_ZN3tvm3tir5SplitENS0_13ScheduleStateERKNS0_8StmtSRefERKNS_7runtime5ArrayINS_8PrimExprEvEEb'/>
<use f='tvm/src/tir/schedule/primitive/loop_transformation.cc' l='469' c='_ZN3tvm3tir4FuseENS0_13ScheduleStateERKNS_7runtime5ArrayINS0_8StmtSRefEvEEb'/>
<use f='tvm/src/tir/schedule/primitive/loop_transformation.cc' l='473' c='_ZN3tvm3tir4FuseENS0_13ScheduleStateERKNS_7runtime5ArrayINS0_8StmtSRefEvEEb'/>
<use f='tvm/src/tir/schedule/primitive/loop_transformation.cc' l='473' c='_ZN3tvm3tir4FuseENS0_13ScheduleStateERKNS_7runtime5ArrayINS0_8StmtSRefEvEEb'/>
<use f='tvm/src/tir/schedule/primitive/loop_transformation.cc' l='475' c='_ZN3tvm3tir4FuseENS0_13ScheduleStateERKNS_7runtime5ArrayINS0_8StmtSRefEvEEb'/>
<use f='tvm/src/tir/schedule/primitive/loop_transformation.cc' l='476' c='_ZN3tvm3tir4FuseENS0_13ScheduleStateERKNS_7runtime5ArrayINS0_8StmtSRefEvEEb'/>
<use f='tvm/src/tir/schedule/primitive/loop_transformation.cc' l='476' c='_ZN3tvm3tir4FuseENS0_13ScheduleStateERKNS_7runtime5ArrayINS0_8StmtSRefEvEEb'/>
<use f='tvm/src/tir/schedule/primitive/loop_transformation.cc' l='491' c='_ZN3tvm3tir4FuseENS0_13ScheduleStateERKNS_7runtime5ArrayINS0_8StmtSRefEvEEb'/>
<use f='tvm/src/tir/schedule/primitive/loop_transformation.cc' l='535' c='_ZN3tvm3tir4FuseENS0_13ScheduleStateERKNS_7runtime5ArrayINS0_8StmtSRefEvEEb'/>
<use f='tvm/src/tir/schedule/primitive/loop_transformation.cc' l='558' c='_ZN3tvm3tir19CollectLoopsIntoSetERKNS0_13ScheduleStateERKNS_7runtime5ArrayINS0_8StmtSRefEvEE'/>
<use f='tvm/src/tir/schedule/primitive/loop_transformation.cc' l='633' c='_ZN3tvm3tir22GetLoopsInReorderRangeERKNS0_13ScheduleStateEPKNS0_12StmtSRefNodeES6_'/>
<use f='tvm/src/tir/schedule/primitive/loop_transformation.cc' l='653' c='_ZN3tvm3tir21ConstructNewLoopChainERKNS0_13ScheduleStateESt6vectorIPKNS0_12StmtSRefNodeESaIS7_EERKNS_7runtime5ArrayINS0_8StmtSRefEvEERKSt13unordered_s3784274'/>
<use f='tvm/src/tir/schedule/primitive/loop_transformation.cc' l='658' c='_ZN3tvm3tir21ConstructNewLoopChainERKNS0_13ScheduleStateESt6vectorIPKNS0_12StmtSRefNodeESaIS7_EERKNS_7runtime5ArrayINS0_8StmtSRefEvEERKSt13unordered_s3784274'/>
<use f='tvm/src/tir/schedule/primitive/loop_transformation.cc' l='684' c='_ZN3tvm3tir21ConstructNewLoopChainERKNS0_13ScheduleStateESt6vectorIPKNS0_12StmtSRefNodeESaIS7_EERKNS_7runtime5ArrayINS0_8StmtSRefEvEERKSt13unordered_s3784274'/>
<use f='tvm/src/tir/schedule/primitive/loop_transformation.cc' l='688' c='_ZN3tvm3tir21ConstructNewLoopChainERKNS0_13ScheduleStateESt6vectorIPKNS0_12StmtSRefNodeESaIS7_EERKNS_7runtime5ArrayINS0_8StmtSRefEvEERKSt13unordered_s3784274'/>
<use f='tvm/src/tir/schedule/primitive/loop_transformation.cc' l='715' c='_ZN3tvm3tir7ReorderENS0_13ScheduleStateERKNS_7runtime5ArrayINS0_8StmtSRefEvEE'/>
<use f='tvm/src/tir/schedule/primitive/loop_transformation.cc' l='721' c='_ZN3tvm3tir11AddUnitLoopENS0_13ScheduleStateENS0_8StmtSRefE'/>
<use f='tvm/src/tir/schedule/primitive/loop_transformation.cc' l='732' c='_ZZN3tvm3tir11AddUnitLoopENS0_13ScheduleStateENS0_8StmtSRefEEN14NewLoopCreator10VisitStmt_EPKNS0_16BlockRealizeNodeE'/>
<use f='tvm/src/tir/schedule/primitive/loop_transformation.cc' l='739' c='_ZN3tvm3tir11AddUnitLoopENS0_13ScheduleStateENS0_8StmtSRefE'/>
<size>8</size>
<use f='tvm/src/tir/schedule/primitive/pad_einsum.cc' l='234' c='_ZN3tvm3tir17PadEinsumRewriter10VisitStmt_EPKNS0_7ForNodeE'/>
<use f='tvm/src/tir/schedule/primitive/pad_einsum.cc' l='234' c='_ZN3tvm3tir17PadEinsumRewriter10VisitStmt_EPKNS0_7ForNodeE'/>
<size>8</size>
<use f='tvm/src/tir/schedule/primitive/reduction.cc' l='38' c='_ZN3tvm3tir31DecomposeReductionBlockReplacer7ReplaceENS0_5BlockENS0_3ForENS0_4StmtES2_'/>
<use f='tvm/src/tir/schedule/primitive/reduction.cc' l='47' c='_ZN3tvm3tir31DecomposeReductionBlockReplacerC1ENS0_3ForENS0_4StmtENS0_5BlockE'/>
<use f='tvm/src/tir/schedule/primitive/reduction.cc' l='99'/>
<use f='tvm/src/tir/schedule/primitive/reduction.cc' l='127' c='_ZN3tvm3tir15LoopHeightError30CheckLoopHigherThanReduceLoopsERKNS_8IRModuleEPKNS0_9BlockNodeEPKNS0_16BlockRealizeNodeERKNS_7runtime5ArrayINS0_8StmtSRefEvEERKSD_'/>
<use f='tvm/src/tir/schedule/primitive/reduction.cc' l='133' c='_ZN3tvm3tir15LoopHeightErrorC1ENS_8IRModuleENS0_3ForENS0_5BlockE'/>
<use f='tvm/src/tir/schedule/primitive/reduction.cc' l='152'/>
<use f='tvm/src/tir/schedule/primitive/reduction.cc' l='193' c='_ZN3tvm3tir18DecomposeReductionENS0_13ScheduleStateERKNS0_8StmtSRefES4_'/>
<use f='tvm/src/tir/schedule/primitive/reduction.cc' l='272' c='_ZN3tvm3tir18DecomposeReductionENS0_13ScheduleStateERKNS0_8StmtSRefES4_'/>
<use f='tvm/src/tir/schedule/primitive/reduction.cc' l='282' c='_ZN3tvm3tir18DecomposeReductionENS0_13ScheduleStateERKNS0_8StmtSRefES4_'/>
<use f='tvm/src/tir/schedule/primitive/reduction.cc' l='431' c='_ZN3tvm3tir22NotSerialLoopKindErrorC1ENS_8IRModuleENS0_3ForE'/>
<use f='tvm/src/tir/schedule/primitive/reduction.cc' l='451'/>
<use f='tvm/src/tir/schedule/primitive/reduction.cc' l='503' c='_ZN3tvm3tir17LoopPropertyErrorC1ENS_8IRModuleENS0_3ForENS1_9ErrorTypeE'/>
<use f='tvm/src/tir/schedule/primitive/reduction.cc' l='547' c='_ZN3tvm3tir17LoopPropertyError17CheckLoopPropertyERKNS0_13ScheduleStateERKNS_7runtime5ArrayINS0_3ForEvEEPKNS0_7ForNodeERKNS0_5BlockERKSt13unordered_se12529618'/>
<use f='tvm/src/tir/schedule/primitive/reduction.cc' l='558' c='_ZN3tvm3tir17LoopPropertyError17CheckLoopPropertyERKNS0_13ScheduleStateERKNS_7runtime5ArrayINS0_3ForEvEEPKNS0_7ForNodeERKNS0_5BlockERKSt13unordered_se12529618'/>
<use f='tvm/src/tir/schedule/primitive/reduction.cc' l='582'/>
<use f='tvm/src/tir/schedule/primitive/reduction.cc' l='592' c='_ZN3tvm3tir18GetLoopVar2LoopMapERKNS_7runtime5ArrayINS0_3ForEvEE'/>
<use f='tvm/src/tir/schedule/primitive/reduction.cc' l='592' c='_ZN3tvm3tir18GetLoopVar2LoopMapERKNS_7runtime5ArrayINS0_3ForEvEE'/>
<use f='tvm/src/tir/schedule/primitive/reduction.cc' l='593' c='_ZN3tvm3tir18GetLoopVar2LoopMapERKNS_7runtime5ArrayINS0_3ForEvEE'/>
<use f='tvm/src/tir/schedule/primitive/reduction.cc' l='595' c='_ZN3tvm3tir18GetLoopVar2LoopMapERKNS_7runtime5ArrayINS0_3ForEvEE'/>
<use f='tvm/src/tir/schedule/primitive/reduction.cc' l='638' c='_ZN3tvm3tir16BaseBlockCreatorC1ENS0_12BlockRealizeENS0_3ForENS_7runtime5ArrayINS0_11BufferStoreEvEENS0_11CommReducerENS5_INS0_6BufferEvEEb'/>
<use f='tvm/src/tir/schedule/primitive/reduction.cc' l='766'/>
<use f='tvm/src/tir/schedule/primitive/reduction.cc' l='825' c='_ZN3tvm3tir19RFactorBlockCreatorC1ENS0_12BlockRealizeENS0_3ForENS_7runtime5ArrayINS0_11BufferStoreEvEENS0_11CommReducerENS5_INS0_6BufferEvEESt13unorde4725904'/>
<use f='tvm/src/tir/schedule/primitive/reduction.cc' l='828' c='_ZN3tvm3tir19RFactorBlockCreatorC1ENS0_12BlockRealizeENS0_3ForENS_7runtime5ArrayINS0_11BufferStoreEvEENS0_11CommReducerENS5_INS0_6BufferEvEESt13unorde4725904'/>
<use f='tvm/src/tir/schedule/primitive/reduction.cc' l='870' c='_ZN3tvm3tir19RFactorBlockCreator17CreateNormalItersEi'/>
<use f='tvm/src/tir/schedule/primitive/reduction.cc' l='929'/>
<use f='tvm/src/tir/schedule/primitive/reduction.cc' l='948' c='_ZN3tvm3tir21WriteBackBlockCreatorC1ENS0_12BlockRealizeENS0_3ForENS_7runtime5ArrayINS0_11BufferStoreEvEENS0_11CommReducerENS5_INS0_6BufferEvEENS0_7Ite3424326'/>
<use f='tvm/src/tir/schedule/primitive/reduction.cc' l='1026' c='_ZN3tvm3tir29CreateLoopOutsideRfactorBlockENS0_12BlockRealizeERKNS_7runtime5ArrayINS0_3ForEvEE'/>
<use f='tvm/src/tir/schedule/primitive/reduction.cc' l='1030' c='_ZN3tvm3tir29CreateLoopOutsideRfactorBlockENS0_12BlockRealizeERKNS_7runtime5ArrayINS0_3ForEvEE'/>
<use f='tvm/src/tir/schedule/primitive/reduction.cc' l='1034' c='_ZN3tvm3tir29CreateLoopOutsideRfactorBlockENS0_12BlockRealizeERKNS_7runtime5ArrayINS0_3ForEvEE'/>
<use f='tvm/src/tir/schedule/primitive/reduction.cc' l='1057' c='_ZN3tvm3tir29CreateLoopOutsideRfactorBlockENS0_12BlockRealizeERKNS_7runtime5ArrayINS0_3ForEvEE'/>
<use f='tvm/src/tir/schedule/primitive/reduction.cc' l='1087' c='_ZN3tvm3tir13BlockReplacer7ReplaceENS0_5BlockENS0_4StmtENS0_3ForENS0_12BlockRealizeES5_S4_St13unordered_setIPKNS0_7VarNodeESt4hashIS9_ESt8equal_toIS9_12847655'/>
<use f='tvm/src/tir/schedule/primitive/reduction.cc' l='1088' c='_ZN3tvm3tir13BlockReplacer7ReplaceENS0_5BlockENS0_4StmtENS0_3ForENS0_12BlockRealizeES5_S4_St13unordered_setIPKNS0_7VarNodeESt4hashIS9_ESt8equal_toIS9_12847655'/>
<use f='tvm/src/tir/schedule/primitive/reduction.cc' l='1090' c='_ZN3tvm3tir13BlockReplacer7ReplaceENS0_5BlockENS0_4StmtENS0_3ForENS0_12BlockRealizeES5_S4_St13unordered_setIPKNS0_7VarNodeESt4hashIS9_ESt8equal_toIS9_12847655'/>
<use f='tvm/src/tir/schedule/primitive/reduction.cc' l='1105' c='_ZN3tvm3tir13BlockReplacerC1ENS0_4StmtENS0_3ForENS0_12BlockRealizeES4_S3_St13unordered_setIPKNS0_7VarNodeESt4hashIS8_ESt8equal_toIS8_ESaIS8_EESt13unor8704007'/>
<use f='tvm/src/tir/schedule/primitive/reduction.cc' l='1106' c='_ZN3tvm3tir13BlockReplacerC1ENS0_4StmtENS0_3ForENS0_12BlockRealizeES4_S3_St13unordered_setIPKNS0_7VarNodeESt4hashIS8_ESt8equal_toIS8_ESaIS8_EESt13unor8704007'/>
<use f='tvm/src/tir/schedule/primitive/reduction.cc' l='1108' c='_ZN3tvm3tir13BlockReplacerC1ENS0_4StmtENS0_3ForENS0_12BlockRealizeES4_S3_St13unordered_setIPKNS0_7VarNodeESt4hashIS8_ESt8equal_toIS8_ESaIS8_EESt13unor8704007'/>
<use f='tvm/src/tir/schedule/primitive/reduction.cc' l='1122' c='_ZN3tvm3tir13BlockReplacer10VisitStmt_EPKNS0_7ForNodeE'/>
<use f='tvm/src/tir/schedule/primitive/reduction.cc' l='1160'/>
<use f='tvm/src/tir/schedule/primitive/reduction.cc' l='1163'/>
<use f='tvm/src/tir/schedule/primitive/reduction.cc' l='1165'/>
<use f='tvm/src/tir/schedule/primitive/reduction.cc' l='1182' c='_ZN3tvm3tir7RFactorENS0_13ScheduleStateERKNS0_8StmtSRefEi'/>
<use f='tvm/src/tir/schedule/primitive/reduction.cc' l='1193' c='_ZN3tvm3tir7RFactorENS0_13ScheduleStateERKNS0_8StmtSRefEi'/>
<use f='tvm/src/tir/schedule/primitive/reduction.cc' l='1194' c='_ZN3tvm3tir7RFactorENS0_13ScheduleStateERKNS0_8StmtSRefEi'/>
<use f='tvm/src/tir/schedule/primitive/reduction.cc' l='1234' c='_ZN3tvm3tir7RFactorENS0_13ScheduleStateERKNS0_8StmtSRefEi'/>
<use f='tvm/src/tir/schedule/primitive/reduction.cc' l='1240' c='_ZN3tvm3tir7RFactorENS0_13ScheduleStateERKNS0_8StmtSRefEi'/>
<use f='tvm/src/tir/schedule/primitive/reduction.cc' l='1257' c='_ZN3tvm3tir7RFactorENS0_13ScheduleStateERKNS0_8StmtSRefEi'/>
<size>8</size>
<use f='tvm/src/tir/schedule/primitive/rolling_buffer.cc' l='429' c='_ZN3tvm3tir13RollingBufferENS0_13ScheduleStateERKNS0_8StmtSRefEi'/>
<use f='tvm/src/tir/schedule/primitive/rolling_buffer.cc' l='429' c='_ZN3tvm3tir13RollingBufferENS0_13ScheduleStateERKNS0_8StmtSRefEi'/>
<size>8</size>
<use f='tvm/src/tir/schedule/state.cc' l='639' c='_ZN3tvm3tir14SRefTreePruner10VisitStmt_EPKNS0_7ForNodeE'/>
<use f='tvm/src/tir/schedule/state.cc' l='891' c='_ZN3tvm3tir13ChildReplacer19CopyOnWriteAndVisitEPKNS0_8StmtNodeE'/>
<size>8</size>
<use f='tvm/src/tir/schedule/transform.cc' l='335' c='_ZN3tvm3tir20TileWithTensorIntrinERKNS0_8ScheduleERKNS0_7BlockRVERKNS_7runtime6StringEb'/>
<size>8</size>
<use f='tvm/src/tir/transforms/common_subexpr_elim.cc' l='622' c='_ZN3tvm3tir29CommonSubexpressionEliminator10VisitStmt_EPKNS0_7ForNodeE'/>
<size>8</size>
<use f='tvm/src/tir/transforms/compact_buffer_region.cc' l='280' c='_ZN3tvm3tir27BufferAccessRegionCollector17VisitBufferAccessERKNS0_12BufferRegionE'/>
<use f='tvm/src/tir/transforms/compact_buffer_region.cc' l='324' c='_ZN3tvm3tir27BufferAccessRegionCollector15NeedRelaxThreadERKNS0_3ForERKNS_7runtime12StorageScopeE'/>
<size>8</size>
<use f='tvm/src/tir/transforms/convert_for_loops_serial.cc' l='44' c='_ZN3tvm3tir22ForLoopSerialConverter10VisitStmt_EPKNS0_7ForNodeE'/>
<size>8</size>
<use f='tvm/src/tir/transforms/inject_double_buffer.cc' l='152' c='_ZN3tvm3tir20DoubleBufferInjector10VisitStmt_EPKNS0_7ForNodeE'/>
<size>8</size>
<use f='tvm/src/tir/transforms/inject_rolling_buffer.cc' l='56'/>
<use f='tvm/src/tir/transforms/inject_rolling_buffer.cc' l='72' c='_ZN3tvm3tir21RollingBufferInjector10VisitStmt_EPKNS0_7ForNodeE'/>
<use f='tvm/src/tir/transforms/inject_rolling_buffer.cc' l='84' c='_ZN3tvm3tir21RollingBufferInjector10VisitStmt_EPKNS0_7ForNodeE'/>
<size>8</size>
<use f='tvm/src/tir/transforms/inject_software_pipeline.cc' l='91' c='_ZN3tvm3tir17software_pipeline28PipelineOpaqueAccessRewriterC1ERKNS_7runtime3MapINS0_3VarENS0_6BufferEvvEERKNS4_IS6_S6_vvEERKNS0_3ForERKSt13unordered_3907376'/>
<use f='tvm/src/tir/transforms/inject_software_pipeline.cc' l='189'/>
<use f='tvm/src/tir/transforms/inject_software_pipeline.cc' l='211' c='_ZN3tvm3tir17software_pipeline20PipelineBodyRewriterC1ERKNS_7runtime3MapINS0_3VarENS0_6BufferEvvEERKNS4_IS6_S6_vvEENS0_3ForEbRKSt13unordered_mapIPKNS016128990'/>
<use f='tvm/src/tir/transforms/inject_software_pipeline.cc' l='296'/>
<use f='tvm/src/tir/transforms/inject_software_pipeline.cc' l='309' c='_ZN3tvm3tir17software_pipeline16PipelineRewriter7RewriteENS_7runtime3MapINS0_3VarENS0_6BufferEvvEERKSt13unordered_setIS6_NS3_13ObjectPtrHashENS3_14Obj9846108'/>
<use f='tvm/src/tir/transforms/inject_software_pipeline.cc' l='322' c='_ZN3tvm3tir17software_pipeline16PipelineRewriterC1ENS_7runtime3MapINS0_3VarENS0_6BufferEvvEERKSt13unordered_setIS6_NS3_13ObjectPtrHashENS3_14ObjectPtr8750948'/>
<use f='tvm/src/tir/transforms/inject_software_pipeline.cc' l='920' c='_ZN3tvm3tir17software_pipeline16PipelineRewriter8EmitImplENS_8PrimExprES3_b'/>
<use f='tvm/src/tir/transforms/inject_software_pipeline.cc' l='949'/>
<use f='tvm/src/tir/transforms/inject_software_pipeline.cc' l='1054' c='_ZN3tvm3tir17software_pipeline16PipelineInjector10VisitStmt_EPKNS0_7ForNodeE'/>
<use f='tvm/src/tir/transforms/inject_software_pipeline.cc' l='1054' c='_ZN3tvm3tir17software_pipeline16PipelineInjector10VisitStmt_EPKNS0_7ForNodeE'/>
<use f='tvm/src/tir/transforms/inject_software_pipeline.cc' l='1144' c='_ZN3tvm3tir17software_pipeline16PipelineInjector10VisitStmt_EPKNS0_7ForNodeE'/>
<size>8</size>
<use f='tvm/src/tir/transforms/inject_virtual_thread.cc' l='466' c='_ZN3tvm3tir10VTInjector12InjectVTLoopENS0_4StmtEb'/>
<size>8</size>
<use f='tvm/src/tir/transforms/install_debug_spans.cc' l='125' macro='1' c='_ZN3tvm3tir18DebugInfoInstaller10VisitStmt_EPKNS0_7ForNodeE'/>
<size>8</size>
<use f='tvm/src/tir/transforms/ir_utils.cc' l='205' c='_ZN3tvm3tir12IRConvertSSA10VisitStmt_EPKNS0_7ForNodeE'/>
<size>8</size>
<use f='tvm/src/tir/transforms/loop_partition.cc' l='601' c='_ZN3tvm3tir15LoopPartitioner12TryPartitionERKNS0_4StmtENS0_3VarENS_8PrimExprES6_S2_b'/>
<use f='tvm/src/tir/transforms/loop_partition.cc' l='707' c='_ZN3tvm3tir15LoopPartitioner7MakeForEPKNS_7runtime6ObjectENS_8PrimExprENS0_4StmtE'/>
<size>8</size>
<use f='tvm/src/tir/transforms/lower_cross_thread_reduction.cc' l='201' c='_ZN3tvm3tir20InThreadReducerMaker10VisitStmt_EPKNS0_7ForNodeE'/>
<use f='tvm/src/tir/transforms/lower_cross_thread_reduction.cc' l='201' c='_ZN3tvm3tir20InThreadReducerMaker10VisitStmt_EPKNS0_7ForNodeE'/>
<use f='tvm/src/tir/transforms/lower_cross_thread_reduction.cc' l='202' c='_ZN3tvm3tir20InThreadReducerMaker10VisitStmt_EPKNS0_7ForNodeE'/>
<use f='tvm/src/tir/transforms/lower_cross_thread_reduction.cc' l='307' c='_ZN3tvm3tir23TransformReductionBlockEPKNS0_16BlockRealizeNodeERKNS_7runtime8OptionalINS4_5ArrayINS0_6BufferEvEEEERKS8_SD_RKNS6_INS_8PrimExprEvEERKNS0_10264619'/>
<use f='tvm/src/tir/transforms/lower_cross_thread_reduction.cc' l='307' c='_ZN3tvm3tir23TransformReductionBlockEPKNS0_16BlockRealizeNodeERKNS_7runtime8OptionalINS4_5ArrayINS0_6BufferEvEEEERKS8_SD_RKNS6_INS_8PrimExprEvEERKNS0_10264619'/>
<use f='tvm/src/tir/transforms/lower_cross_thread_reduction.cc' l='427' c='_ZN3tvm3tir23TransformReductionBlockEPKNS0_16BlockRealizeNodeERKNS_7runtime8OptionalINS4_5ArrayINS0_6BufferEvEEEERKS8_SD_RKNS6_INS_8PrimExprEvEERKNS0_10264619'/>
<use f='tvm/src/tir/transforms/lower_cross_thread_reduction.cc' l='547' c='_ZNK3tvm3tir31CrossThreadReductionTransformer33CheckCanApplyCrossThreadReductionEPKNS0_9BlockNodeERKSt6vectorIPKNS0_7ForNodeESaIS8_EE'/>
<size>8</size>
<use f='tvm/src/tir/transforms/lower_opaque_block.cc' l='97' c='_ZN3tvm3tir16OpaqueBlockLower10VisitStmt_EPKNS0_7ForNodeE'/>
<size>8</size>
<use f='tvm/src/tir/transforms/manifest_shared_memory_local_stage.cc' l='140' c='_ZN3tvm3tir25IntermediateStageRewriter14MakeLocalStageEPKNS0_9BlockNodeERKNS0_6BufferENS_7runtime5ArrayINS_8PrimExprEvEESt6vectorIPKNS0_7ForNodeESaISF9837013'/>
<size>8</size>
<use f='tvm/src/tir/transforms/plan_update_buffer_allocation_location.cc' l='144' c='_ZN3tvm3tir23BufferAllocationLocator10VisitStmt_EPKNS0_7ForNodeE'/>
<size>8</size>
<use f='tvm/src/tir/transforms/storage_flatten.cc' l='1631' c='_ZN3tvm3tir16StorageFlattener10VisitStmt_EPKNS0_12PrefetchNodeE'/>
<use f='tvm/src/tir/transforms/storage_flatten.cc' l='1638' c='_ZN3tvm3tir16StorageFlattener10VisitStmt_EPKNS0_12PrefetchNodeE'/>
<size>8</size>
<use f='tvm/src/tir/transforms/storage_rewrite.cc' l='536' c='_ZN3tvm3tir19StoragePlanRewriter10VisitStmt_EPKNS0_7ForNodeE'/>
<size>8</size>
<use f='tvm/src/tir/transforms/unify_thread_binding.cc' l='67' c='_ZN3tvm3tir20ThreadBindingUnifier10VisitStmt_EPKNS0_7ForNodeE'/>
<use f='tvm/src/tir/transforms/unify_thread_binding.cc' l='67' c='_ZN3tvm3tir20ThreadBindingUnifier10VisitStmt_EPKNS0_7ForNodeE'/>
<use f='tvm/src/tir/transforms/unify_thread_binding.cc' l='141' c='_ZN3tvm3tir20ThreadBindingUnifier17EmitLaunchThreadsERKNS0_4StmtE'/>
<size>8</size>
<use f='tvm/src/tir/transforms/unroll_loop.cc' l='128' c='_ZN3tvm3tir12LoopUnroller10VisitStmt_EPKNS0_7ForNodeE'/>
<size>8</size>
<use f='tvm/src/tir/transforms/vectorize_loop.cc' l='477' c='_ZN3tvm3tir10Vectorizer10VisitStmt_EPKNS0_7ForNodeE'/>
<use f='tvm/src/tir/transforms/vectorize_loop.cc' l='565' c='_ZN3tvm3tir10Vectorizer9ScalarizeENS0_4StmtE'/>
<use f='tvm/src/tir/transforms/vectorize_loop.cc' l='675' c='_ZN3tvm3tir16VectorizeSkipper10VisitStmt_EPKNS0_7ForNodeE'/>
<size>8</size>
<use f='tvm/src/tir/usmp/analysis/extract_buffer_info.cc' l='150'/>
<use f='tvm/src/tir/usmp/analysis/extract_buffer_info.cc' l='355' c='_ZN3tvm3tir4usmp19BufferInfoExtractor10VisitStmt_EPKNS0_7ForNodeE'/>
<size>8</size>
