<use f='tvm/arith/const_fold.h' l='109' c='_ZN3tvm5arith12TryConstFoldENS_8PrimExprES1_'/>
<size>8</size>
<use f='tvm/arith/pattern_match.h' l='392' c='_ZN3tvm5arithmiERKNS0_7PatternIT_EERKNS1_IT0_EE'/>
<use f='tvm/arith/pattern_match.h' l='392' c='_ZN3tvm5arithmiERKNS0_7PatternIT_EERKNS1_IT0_EE'/>
<use f='tvm/arith/pattern_match.h' l='392' c='_ZN3tvm5arithmiERKNS0_7PatternIT_EEl'/>
<use f='tvm/arith/pattern_match.h' l='392' c='_ZN3tvm5arithmiElRKNS0_7PatternIT_EE'/>
<use f='tvm/arith/canonical_simplify.cc' l='744' c='_ZN3tvm5arith19CanonicalSimplifier4Impl10VisitExpr_EPKNS_3tir7SubNodeE'/>
<size>8</size>
<use f='tvm/arith/int_set.cc' l='141' c='_ZN3tvm5arith7CombineEPNS0_8AnalyzerENS0_11IntervalSetES3_NS_7runtime8DataTypeE'/>
<use f='tvm/arith/int_set.cc' l='398' c='_ZN3tvm5arith20IntervalSetEvaluator10VisitExpr_EPKNS_3tir7SubNodeE'/>
<size>8</size>
<use f='tvm/arith/iter_affine_map.cc' l='1243' c='_ZN3tvm5arith15IterMapRewriter10VisitExpr_EPKNS_3tir7SubNodeE'/>
<use f='tvm/arith/iter_affine_map.cc' l='1251' c='_ZN3tvm5arith15IterMapRewriter10VisitExpr_EPKNS_3tir7SubNodeE'/>
<size>8</size>
<use f='tvm/arith/rewrite_simplify.cc' l='261' c='_ZN3tvm5arith17RewriteSimplifier4Impl10VisitExpr_EPKNS_3tir7SubNodeE'/>
<size>8</size>
<use f='tvm/relay/backend/contrib/example_target_hooks/relay_to_tir.cc' l='138' c='_ZN3tvm5relay7contrib20example_target_hooks12_GLOBAL__N_120ConvertAddToSubtract30ReplaceAddWithSubtractPrimFuncERKNS0_8FunctionE'/>
<use f='tvm/relay/backend/contrib/example_target_hooks/relay_to_tir.cc' l='138' c='_ZN3tvm5relay7contrib20example_target_hooks12_GLOBAL__N_120ConvertAddToSubtract30ReplaceAddWithSubtractPrimFuncERKNS0_8FunctionE'/>
<use f='tvm/relay/backend/contrib/example_target_hooks/relay_to_tir.cc' l='141' c='_ZN3tvm5relay7contrib20example_target_hooks12_GLOBAL__N_120ConvertAddToSubtract30ReplaceAddWithSubtractPrimFuncERKNS0_8FunctionE'/>
<size>8</size>
<use f='tvm/te/autodiff/ad_simplify.cc' l='200' c='_ZN3tvm2te23NonzeroConditionFunctor10VisitExpr_EPKNS_3tir7SubNodeE'/>
<size>8</size>
<use f='tvm/te/autodiff/jacobian.cc' l='103' c='_ZN3tvm2te15JacobianMutator10VisitExpr_EPKNS_3tir8CallNodeE'/>
<use f='tvm/te/autodiff/jacobian.cc' l='107' c='_ZN3tvm2te15JacobianMutator10VisitExpr_EPKNS_3tir8CallNodeE'/>
<use f='tvm/te/autodiff/jacobian.cc' l='128' c='_ZN3tvm2te15JacobianMutator10VisitExpr_EPKNS_3tir7SubNodeE'/>
<use f='tvm/te/autodiff/jacobian.cc' l='135' c='_ZN3tvm2te15JacobianMutator10VisitExpr_EPKNS_3tir7DivNodeE'/>
<use f='tvm/te/autodiff/jacobian.cc' l='141' c='_ZN3tvm2te15JacobianMutator10VisitExpr_EPKNS_3tir12FloorDivNodeE'/>
<size>8</size>
<use f='tvm/tir/ir/expr.cc' l='261'/>
<size>8</size>
<fun r='_ZN3tvm3tir3SubC1ENS_8PrimExprES2_NS_4SpanE'/>
<use f='tvm/tir/ir/expr_functor.cc' l='193' c='_ZN3tvm3tir11ExprMutator10VisitExpr_EPKNS0_7SubNodeE'/>
<size>8</size>
<use f='tvm/tir/op/op.cc' l='352' c='_ZN3tvm3subENS_8PrimExprES0_NS_4SpanE'/>
<use f='tvm/tir/op/op.cc' l='354' c='_ZN3tvm3subENS_8PrimExprES0_NS_4SpanE'/>
<size>8</size>
