<def f='tvm/meta_schedule/feature_extractor/per_store_feature.cc' l='627' ll='765'/>
<use f='tvm/meta_schedule/feature_extractor/per_store_feature.cc' l='1236'/>
<use f='tvm/meta_schedule/feature_extractor/per_store_feature.cc' l='1299' c='_ZN3tvm3tir24PerStoreFeatureCollector10VisitStmt_EPKNS0_15BufferStoreNodeE'/>
<size>24</size>
<doc f='tvm/meta_schedule/feature_extractor/per_store_feature.cc' l='626'>/*! \brief Group 2 features */</doc>
