<use f='tvm/printer/relay_text_printer.cc' l='551' u='r' c='_ZN3tvm5relay16RelayTextPrinter10VisitExpr_EPKNS0_9MatchNodeE'/>
<use f='tvm/relay/analysis/match_exhaustion.cc' l='286' u='r' c='_ZN3tvm5relay14UnmatchedCasesERKNS0_5MatchERKNS_8IRModuleE'/>
<use f='tvm/relay/analysis/match_exhaustion.cc' l='295' u='r' c='_ZN3tvm5relay14UnmatchedCasesERKNS0_5MatchERKNS_8IRModuleE'/>
<use f='tvm/relay/analysis/util.cc' l='454' u='r' c='_ZZN3tvm5relay9TypeSubstERKNS_9RelayExprERKNS_7runtime3MapINS_7TypeVarENS_4TypeEvvEEEN16TypeSubstMutator11VisitClauseERKNS0_6ClauseE'/>
<use f='tvm/relay/analysis/well_formed.cc' l='136' u='r' c='_ZN3tvm5relay17WellFormedChecker11VisitClauseERKNS0_6ClauseE'/>
<use f='tvm/relay/backend/interpreter.cc' l='870' u='r' c='_ZN3tvm5relay11Interpreter10VisitExpr_EPKNS0_9MatchNodeE'/>
<use f='tvm/relay/backend/vm/compiler.cc' l='197' u='r' c='_ZN3tvm5relay2vm27BuildDecisionTreeFromClauseESt10shared_ptrINS1_10MatchValueEENS0_6ClauseES2_INS0_8TreeNodeIS2_INS1_13ConditionNodeEEEEE'/>
<use f='tvm/relay/backend/vm/manifest_lifetimes.cc' l='220' u='m' c='_ZN3tvm5relay9transform15AliasEliminator10VisitExpr_EPKNS0_9MatchNodeE'/>
<use f='tvm/relay/backend/vm/manifest_lifetimes.cc' l='223' u='r' c='_ZN3tvm5relay9transform15AliasEliminator10VisitExpr_EPKNS0_9MatchNodeE'/>
<use f='tvm/relay/ir/adt.cc' l='102' u='w' c='_ZN3tvm5relay6ClauseC1ENS0_7PatternENS_9RelayExprE'/>
<use f='tvm/relay/ir/adt.cc' l='108' u='r' c='_ZN3tvm5relay10WithFieldsENS0_6ClauseENS_7runtime8OptionalINS0_7PatternEEENS3_INS_9RelayExprEEE'/>
<use f='tvm/relay/ir/adt.cc' l='111' u='r' c='_ZN3tvm5relay10WithFieldsENS0_6ClauseENS_7runtime8OptionalINS0_7PatternEEENS3_INS_9RelayExprEEE'/>
<use f='tvm/relay/ir/adt.cc' l='115' u='w' c='_ZN3tvm5relay10WithFieldsENS0_6ClauseENS_7runtime8OptionalINS0_7PatternEEENS3_INS_9RelayExprEEE'/>
<use f='tvm/relay/ir/adt.cc' l='130' u='r'/>
<use f='tvm/relay/ir/expr_functor.cc' l='280' u='r' c='_ZN3tvm5relay11ExprMutator11VisitClauseERKNS0_6ClauseE'/>
<use f='tvm/relay/ir/expr_functor.cc' l='395' u='r' c='_ZN3tvm5relay11ExprVisitor11VisitClauseERKNS0_6ClauseE'/>
<use f='tvm/relay/ir/expr_functor.cc' l='462' u='r' c='_ZN3tvm5relay10ExprBinder11VisitClauseERKNS0_6ClauseE'/>
<use f='tvm/relay/ir/indexed_graph.cc' l='155' u='r' c='_ZZN3tvm5relay18CreateIndexedGraphERKNS_9RelayExprEEN7Creator10VisitExpr_EPKNS0_9MatchNodeE'/>
<use f='tvm/relay/ir/indexed_graph.cc' l='297' u='r' c='_ZZN3tvm5relay18CreateIndexedGraphERKNS_9RelayExprEEN9Annotator10VisitExpr_EPKNS0_9MatchNodeE'/>
<use f='tvm/relay/ir/indexed_graph.cc' l='374' u='r' c='_ZZN3tvm5relay18CreateIndexedGraphERKNS_9RelayExprEEN7Blocker10VisitExpr_EPKNS0_9MatchNodeE'/>
<use f='tvm/relay/transforms/dead_code.cc' l='296' u='r' c='_ZN3tvm5relay12_GLOBAL__N_113PurityVisitor10VisitExpr_EPKNS0_9MatchNodeE'/>
<use f='tvm/relay/transforms/device_planner.cc' l='645' u='r' c='_ZN3tvm5relay9transform12_GLOBAL__N_114DeviceAnalyzer10VisitExpr_EPKNS0_9MatchNodeE'/>
<use f='tvm/relay/transforms/device_planner.cc' l='1180' u='r' c='_ZN3tvm5relay9transform12_GLOBAL__N_114DeviceCapturer10VisitExpr_EPKNS0_9MatchNodeE'/>
<use f='tvm/relay/transforms/partial_eval.cc' l='950' u='r' c='_ZN3tvm5relay12partial_eval16PartialEvaluator10VisitExpr_EPKNS0_9MatchNodeEPNS0_7LetListE'/>
<use f='tvm/relay/transforms/partial_eval.cc' l='961' u='r' c='_ZN3tvm5relay12partial_eval16PartialEvaluator10VisitExpr_EPKNS0_9MatchNodeEPNS0_7LetListE'/>
<use f='tvm/relay/transforms/partial_eval.cc' l='967' u='r' c='_ZN3tvm5relay12partial_eval16PartialEvaluator10VisitExpr_EPKNS0_9MatchNodeEPNS0_7LetListE'/>
<use f='tvm/relay/transforms/to_a_normal_form.cc' l='372' u='r' c='_ZN3tvm5relay12_GLOBAL__N_14Fill10VisitExpr_EPKNS0_9MatchNodeERKNS0_3VarE'/>
<use f='tvm/relay/transforms/to_cps.cc' l='195' u='r' c='_ZZN3tvm5relay5ToCPSERKNS0_8FunctionERKNS_8IRModuleEPSt13unordered_mapINS_9GlobalVarES8_NS_7runtime13ObjectPtrHashENS9_14ObjectPtrEqualESaISt4pairIKS814013644'/>
<use f='tvm/relay/transforms/type_infer.cc' l='330' u='r' c='_ZN3tvm5relay14TypeInferencer10VisitExpr_EPKNS0_9MatchNodeE'/>
