<use f='tvm/relay/backend/vm/compiler.cc' l='317' c='_ZN3tvm5relay2vm18VMFunctionCompiler4EmitERKNS_7runtime2vm11InstructionE'/>
<use f='tvm/runtime/vm/bytecode.cc' l='49' c='_ZN3tvm7runtime2vm11InstructionC1ERKS2_'/>
<use f='tvm/runtime/vm/bytecode.cc' l='149' c='_ZN3tvm7runtime2vm11InstructionaSERKS2_'/>
<use f='tvm/runtime/vm/bytecode.cc' l='244' c='_ZN3tvm7runtime2vm11InstructionD1Ev'/>
<use f='tvm/runtime/vm/bytecode.cc' l='495' u='r' c='_ZN3tvm7runtime2vm11Instruction4MoveEll'/>
<use f='tvm/runtime/vm/bytecode.cc' l='538' c='_ZN3tvm7runtime2vm16InstructionPrintERSoRKNS1_11InstructionE'/>
<use f='tvm/runtime/vm/executable.cc' l='515' c='_ZN3tvm7runtime2vm20SerializeInstructionERKNS1_11InstructionE'/>
<use f='tvm/runtime/vm/executable.cc' l='809' c='_ZN3tvm7runtime2vm22DeserializeInstructionERKNS1_23VMInstructionSerializerE'/>
<use f='tvm/runtime/vm/vm.cc' l='532' c='_ZN3tvm7runtime2vm14VirtualMachine7RunLoopEv'/>
