<dec f='tvm/relay/analysis/call_graph.h' l='58' type='tvm::IRModule'/>
<use f='tvm/relay/analysis/call_graph.h' l='63' u='a' c='_ZN3tvm5relay13CallGraphNode10VisitAttrsEPNS_11AttrVisitorE'/>
<use f='tvm/relay/analysis/call_graph.h' l='105' u='m' c='_ZNK3tvm5relay13CallGraphNodeixERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE'/>
<use f='tvm/relay/analysis/call_graph.h' l='115' u='m' c='_ZN3tvm5relay13CallGraphNodeixERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE'/>
<use f='tvm/relay/analysis/call_graph.cc' l='44' u='w' c='_ZN3tvm5relay9CallGraphC1ENS_8IRModuleE'/>
<use f='tvm/relay/analysis/call_graph.cc' l='45' u='m' c='_ZN3tvm5relay9CallGraphC1ENS_8IRModuleE'/>
<use f='tvm/relay/analysis/call_graph.cc' l='102' u='m' c='_ZNK3tvm5relay13CallGraphNode17GetGlobalFunctionERKNS_9GlobalVarE'/>
<use f='tvm/relay/analysis/call_graph.cc' l='104' u='m' c='_ZNK3tvm5relay13CallGraphNode17GetGlobalFunctionERKNS_9GlobalVarE'/>
<use f='tvm/relay/analysis/call_graph.cc' l='144' u='m' c='_ZN3tvm5relay13CallGraphNode25RemoveGlobalVarFromModuleEPNS0_14CallGraphEntryEb'/>
<use f='tvm/relay/analysis/call_graph.cc' l='176' u='m' c='_ZNK3tvm5relay13CallGraphNode16TopologicalOrderEv'/>
<use f='tvm/relay/analysis/call_graph.cc' l='177' u='m' c='_ZNK3tvm5relay13CallGraphNode16TopologicalOrderEv'/>
<use f='tvm/relay/analysis/call_graph.cc' l='183' u='m' c='_ZNK3tvm5relay13CallGraphNode16TopologicalOrderEv'/>
<use f='tvm/relay/analysis/call_graph.cc' l='317' u='r'/>
<offset>128</offset>
<doc f='tvm/relay/analysis/call_graph.h' l='57'>/*! \brief The IR module for creating a CallGraphNode. */</doc>
<use f='tvm/relay/transforms/inline.cc' l='193' u='m' c='_ZN3tvm5relay6InlineERKNS_8IRModuleE'/>
<use f='tvm/relay/transforms/inline.cc' l='215' u='r' c='_ZN3tvm5relay6InlineERKNS_8IRModuleE'/>
