<def f='tvm/meta_schedule/feature_extractor/per_store_feature.cc' l='1112' ll='1141'/>
<use f='tvm/meta_schedule/feature_extractor/per_store_feature.cc' l='1238'/>
<use f='tvm/meta_schedule/feature_extractor/per_store_feature.cc' l='1270' c='_ZN3tvm3tir24PerStoreFeatureCollector7CollectEbllRKNS_8IRModuleE'/>
<use f='tvm/meta_schedule/feature_extractor/per_store_feature.cc' l='1316' c='_ZN3tvm3tir24PerStoreFeatureCollector17HandleBufferAllocERKNS0_6BufferE'/>
<size>24</size>
<doc f='tvm/meta_schedule/feature_extractor/per_store_feature.cc' l='1111'>/*! \brief Group 4 feature */</doc>
