<use f='tvm/ir/module.cc' l='229' u='w' c='_ZN3tvm12IRModuleNode20RegisterConstructorsERKNS_13GlobalTypeVarERKNS_8TypeDataE'/>
<use f='tvm/ir/module.cc' l='230' u='r' c='_ZN3tvm12IRModuleNode20RegisterConstructorsERKNS_13GlobalTypeVarERKNS_8TypeDataE'/>
<use f='tvm/relay/backend/interpreter.cc' l='775' u='r' c='_ZN3tvm5relay11Interpreter10VisitExpr_EPKNS0_8CallNodeE'/>
<use f='tvm/relay/backend/interpreter.cc' l='881' u='r' c='_ZN3tvm5relay11Interpreter13VisitPattern_EPKNS0_22PatternConstructorNodeERKNS_7runtime9ObjectRefE'/>
<use f='tvm/relay/backend/interpreter.cc' l='883' u='r' c='_ZN3tvm5relay11Interpreter13VisitPattern_EPKNS0_22PatternConstructorNodeERKNS_7runtime9ObjectRefE'/>
<use f='tvm/relay/backend/vm/compiler.cc' l='173' u='r' c='_ZN3tvm5relay2vm28BuildDecisionTreeFromPatternESt10shared_ptrINS1_10MatchValueEENS0_7PatternES2_INS0_8TreeNodeIS2_INS1_13ConditionNodeEEEEESA_'/>
<use f='tvm/relay/backend/vm/compiler.cc' l='694' u='r' c='_ZN3tvm5relay2vm18VMFunctionCompiler21DeviceAwareVisitExpr_EPKNS0_8CallNodeE'/>
<use f='tvm/relay/transforms/partial_eval.cc' l='994' u='r' c='_ZN3tvm5relay12partial_eval16PartialEvaluator13VisitPattern_EPKNS0_22PatternConstructorNodeERKNS1_7PStaticE'/>
<use f='tvm/relay/transforms/partial_eval.cc' l='995' u='r' c='_ZN3tvm5relay12partial_eval16PartialEvaluator13VisitPattern_EPKNS0_22PatternConstructorNodeERKNS1_7PStaticE'/>
<use f='tvm/relay/transforms/partial_eval.cc' l='996' u='r' c='_ZN3tvm5relay12partial_eval16PartialEvaluator13VisitPattern_EPKNS0_22PatternConstructorNodeERKNS1_7PStaticE'/>
<use f='tvm/relay/transforms/partial_eval.cc' l='996' u='r' c='_ZN3tvm5relay12partial_eval16PartialEvaluator13VisitPattern_EPKNS0_22PatternConstructorNodeERKNS1_7PStaticE'/>
