<def f='tvm/meta_schedule/feature_extractor/per_store_feature.cc' l='1039' ll='1105'/>
<use f='tvm/meta_schedule/feature_extractor/per_store_feature.cc' l='1237'/>
<use f='tvm/meta_schedule/feature_extractor/per_store_feature.cc' l='1302' c='_ZN3tvm3tir24PerStoreFeatureCollector10VisitStmt_EPKNS0_15BufferStoreNodeE'/>
<size>24</size>
<doc f='tvm/meta_schedule/feature_extractor/per_store_feature.cc' l='1038'>/*! \brief Group 3 feature */</doc>
