<use f='tvm/script/printer/doc.cc' l='190' u='w' c='_ZN3tvm6script7printer9AssertDocC1ENS1_7ExprDocENS_7runtime8OptionalIS3_EE'/>
<use f='tvm/script/printer/python_doc_printer.cc' l='570' u='m' c='_ZN3tvm6script7printer16PythonDocPrinter13PrintTypedDocERKNS1_9AssertDocE'/>
<use f='tvm/script/printer/python_doc_printer.cc' l='572' u='m' c='_ZN3tvm6script7printer16PythonDocPrinter13PrintTypedDocERKNS1_9AssertDocE'/>
