<use f='tvm/ir/diagnostic.cc' l='118' u='w' c='_ZN3tvm17DiagnosticContextC1ERKNS_8IRModuleERKNS_18DiagnosticRendererE'/>
<use f='tvm/ir/diagnostic.cc' l='233' u='m' c='_ZN3tvm8ReportAtERKNS_17DiagnosticContextERSoRKNS_4SpanERKNS_10DiagnosticE'/>
<use f='tvm/ir/diagnostic.cc' l='234' u='m' c='_ZN3tvm8ReportAtERKNS_17DiagnosticContextERSoRKNS_4SpanERKNS_10DiagnosticE'/>
<use f='tvm/ir/diagnostic.cc' l='237' u='m' c='_ZN3tvm8ReportAtERKNS_17DiagnosticContextERSoRKNS_4SpanERKNS_10DiagnosticE'/>
<use f='tvm/relay/analysis/type_solver.cc' l='531' u='r' c='_ZN3tvm5relay10TypeSolverC1ERKNS_9GlobalVarENS_17DiagnosticContextE'/>
