<def f='tvm/meta_schedule/feature_extractor/per_store_feature.cc' l='1232' ll='1243'/>
<use f='tvm/meta_schedule/feature_extractor/per_store_feature.cc' l='1242' c='_ZNK3tvm3tir7FeatureltERKS1_'/>
<use f='tvm/meta_schedule/feature_extractor/per_store_feature.cc' l='1248' c='_ZN3tvm3tir24PerStoreFeatureCollector7CollectEbllRKNS_8IRModuleE'/>
<use f='tvm/meta_schedule/feature_extractor/per_store_feature.cc' l='1260' c='_ZN3tvm3tir24PerStoreFeatureCollector7CollectEbllRKNS_8IRModuleE'/>
<use f='tvm/meta_schedule/feature_extractor/per_store_feature.cc' l='1263' c='_ZN3tvm3tir24PerStoreFeatureCollector7CollectEbllRKNS_8IRModuleE'/>
<use f='tvm/meta_schedule/feature_extractor/per_store_feature.cc' l='1292' c='_ZN3tvm3tir24PerStoreFeatureCollector10VisitStmt_EPKNS0_15BufferStoreNodeE'/>
<use f='tvm/meta_schedule/feature_extractor/per_store_feature.cc' l='1315' c='_ZN3tvm3tir24PerStoreFeatureCollector17HandleBufferAllocERKNS0_6BufferE'/>
<use f='tvm/meta_schedule/feature_extractor/per_store_feature.cc' l='1332'/>
<use f='tvm/meta_schedule/feature_extractor/per_store_feature.cc' l='1359' c='_ZN3tvm13meta_schedule19PerStoreFeatureNode13ExtractSingleENS_8IRModuleEbPSt6vectorIS3_IdSaIdEESaIS5_EE'/>
<use f='tvm/meta_schedule/feature_extractor/per_store_feature.cc' l='1364' c='_ZN3tvm13meta_schedule19PerStoreFeatureNode13ExtractSingleENS_8IRModuleEbPSt6vectorIS3_IdSaIdEESaIS5_EE'/>
<size>72</size>
<doc f='tvm/meta_schedule/feature_extractor/per_store_feature.cc' l='1231'>/*! \brief The feature extracted */</doc>
