name: Woboq Codebrowser
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'


jobs:
  codebrowser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "14.0"
      - name: Checkout codebrowser
        run: |
          set -eux
          git clone --depth=1 https://github.com/driazati/codebrowser
          cd codebrowser
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release ..
          cmake --build . -- -j$(nproc)
      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3
      - name: Build TVM
        run: |
          set -eux
          git clone --depth=1 https://github.com/apache/tvm --recursive --jobs 0
          cd tvm
          mkdir build
          cd build
          cmake -DUSE_MICRO=1 -DUSE_LLVM=1 ..
          # building the code isn't actually necessary
          # cmake --build . -- -j$(nproc)
      - name: Generate site
        run: |
          set -eux
          cd codebrowser
          SOURCE_DIR=$(pwd)/../tvm
          BUILD_DIR=$(pwd)/../tvm/build
          OUT_DIR=tvm
          VERSION=$(cd "$SOURCE_DIR" && git describe --always --tags)
          ./build/generator/codebrowser_generator -b $BUILD_DIR -a -o $OUT_DIR -p tvm:$SOURCE_DIR:$VERSION -d ./data
          ./build/indexgenerator/codebrowser_indexgenerator $OUT_DIR
          cd ..
          mkdir deploy
          cp -r ./codebrowser/tvm deploy
          cp -r ./codebrowser/data deploy
          cp -r ./codebrowser/data deploy/tvm
          cp index.html deploy
          cp index.html deploy/tvm
      - name: Deploy site
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: deploy 

